### ISSUE TITLE
java.lang.RuntimeException in IntercomMessengerActivity

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#1000]
## Error in MittAtb

**java.lang.RuntimeException** in **IntercomMessengerActivity**
Unable to start activity ComponentInfo{no.mittatb.store/io.intercom.android.sdk.activities.IntercomMessengerActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0700ca

[View on Bugsnag](https://app.bugsnag.com/atb-as/mittatb/errors/60503c35eed29b00075fc2fb?event_id=60503c350073ade6d42d0000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:2778 - android.app.ActivityThread.performLaunchActivity

[View full stacktrace](https://app.bugsnag.com/atb-as/mittatb/errors/60503c35eed29b00075fc2fb?event_id=60503c350073ade6d42d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gorandalum** [comment]
Utdatert
