### ISSUE TITLE
[Improvement] Endre begrepsbruk til "reise i sone" i stedet for "reise gjennom sone"

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1003]
## Origin

_Links to received feedback, user research or other findings._

Feedback from Julia/Marked that one does not travel "through" a zone, but within.

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

Update both norwegian and english language on the ticketing screens.

New text:
Reise i 1 sone
Travel in 1 zone

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by hildeor** [comment]
Putting this on hold - we need a complete view of affected texts before implementing.

**Comment by gorandalum** [comment]
Tekster etter gjennomgang og endring:

**Norsk**
Oversiktsbildet en sone: “Reise i 1 sone (A)”
Bekreftelsesbildet en sone: “Gyldig i sone A”
Oversiktsbildet to soner: “Reise fra sone A til sone C6”
Bekreftelsesbildet to soner: “Gyldig fra sone A til sone C6"

**Engelsk**
Oversiktsbildet en sone: “Travel in 1 zone (A)”
Bekreftelsesbildet en sone: “Valid in zone A”
Oversiktsbildet to soner: “Travel from zone A to zone C6”
Bekreftelsesbildet to soner: “Valid from zone A to zone C6"

**Comment by tormoseng** [comment]
Testet OK på iOS 14 og Android 7.0 i staging
