### ISSUE TITLE
[Improvement] UU-forbedring på billettkjøpsopplevelsen

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1008]
## Origin

_Links to received feedback, user research or other findings._
After field testing with representatives from Blindeforbundet  18th march we got some feedback on specifically the ticketing experience

- [x] Fokus plasseres i toppen på page title når man kommer til billettvalg-vinduet
- [x] Minus-ikon bør aldri forsvinne
- [x] Default valg for passasjerkategori kan settes som innstilling av brukeren selv
- [ ] Bruke rotor (?) her for å redusere antall fokusfelter. F. eks "dobbeltrykk for å øke antall. Sveip ned for å redusere antall)
- [ ] Endre begrepsbruk fra "aktiver" til dobbeltrykk (gjelder generelt i appen)
- [x] Slå sammen fokusområder slik at det bare er ett for kjøpsoppsummeringen. Tekst blir lest opp i sin helhet
- [ ] Etter man har valgt både fra/til soner så hopper fokus til "tilbake"-knappen. Burde vært beholdt på feltet man nettopp valgte sone for slik at man kan bekrefte at det var riktig.

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by gorandalum** [comment]
Minus icon not disappearing fixed in https://github.com/AtB-AS/mittatb-app/pull/1025

**Comment by gorandalum** [comment]
>Slå sammen fokusområder slik at det bare er ett for kjøpsoppsummeringen. Tekst blir lest opp i sin helhet

Improved by https://github.com/AtB-AS/mittatb-app/pull/1026

**Comment by hildeor** [comment]
@gorandalum Er ikke første punktet her også løst?

**Comment by gorandalum** [comment]
- Jess. Fokus i toppen er fikset. Jeg huket av nå.
- Rotor sjekket jeg opp, og det har ikke støtte i react-native (enda).
- Begrepet dobbelttrykk ble vi vel enige om å ikke bruke siden brukere kan aktivere knapper på forskjellige måter som ikke behøver å være dobbelttrykk.
- Fokus på knapp som førte til subscreen ved navigering tilbake er ikke fikset. Fokus kommer alltid i toppen.
