### ISSUE TITLE
[Feature] Improve contrast in dark mode

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1012]
## Origin

_Links to received feedback, user research or other findings._

We have received some feedback via both Intercom and survey that the contrast when using darkmode is not sufficient and makes it hard to process the different sections of information. 
Examples where this is especially prominent are:
- Travel search: Main background color and background color of each travel suggestion
- Departures: Main background color and background color of each platform

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

- @pettersuul Look at how we can change the colors in dark mode to increase contrast
- Change the colors according to suggested design

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by pettersuul** [comment]
Suggested new background colors:
level1: '#242B30',
level2: '#37424A',
level3: '#555E65',

![image](https://user-images.githubusercontent.com/56530785/112333867-40457980-8cbb-11eb-9891-00fa71687eab.png)

**Comment by gorandalum** [comment]
QA: Looks better with the improved contrast :+1:
