### ISSUE TITLE
com.facebook.react.bridge.JSApplicationIllegalArgumentException in MainActivity

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#1043]
## Error in MittAtb

**com.facebook.react.bridge.JSApplicationIllegalArgumentException** in **MainActivity**
Error while updating property 'endNode' of a view managed by: RNSharedElementTransition

[View on Bugsnag](https://app.bugsnag.com/atb-as/mittatb/errors/6064337b0c4e230007330b7d?event_id=6064337b0075fd2af28a0000&i=gh&m=ci)

## Stacktrace

    ViewManagersPropertyCache.java:100 - com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp

[View full stacktrace](https://app.bugsnag.com/atb-as/mittatb/errors/6064337b0c4e230007330b7d?event_id=6064337b0075fd2af28a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gorandalum** [comment]
Utdatert
