### ISSUE TITLE
[BUG] Time to travel vs travel time in Assistant overview

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#1045]
**Describe the bug**

> Tenkte bare jeg skulle si fra at jeg synes det hadde vært mer naturlig om antall minutter på høyresiden når en søker opp en bussrute hadde vært minutter til bussen går, i stedet for hvor lang tid busseturen tar :)

From https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/all/conversations/159245400006386

**Application version**
Version number: production

**Comment by pettersuul** [comment]
Both Entur and RuterReise places the total travel time in the top right of the suggestion, so it seems this is an established pattern.
There may also be some confusion around if this when the user has to start walking or when the bus leaves.
Also, will there be a problem to use relative time (# minutes) with regards to keeping it updated?

**Comment by hildeor** [comment]
Foreslår at vi lukker denne basert på @pettersuul sin kommentar over her og at det ikke har kommet mange tilbakemeldinger på akkurat dette.
