### ISSUE TITLE
[Feature] Suggested improvements after quality assessment

### ISSUE THREAD

**Issue by LineLuna** [AtB-AS/mittatb-app#1050]
## Origin

Small issues or suggestions of improvement in the APP

## Proposed solution

Smaller observations: 
* Privacy statement leads to a page outside the app, this should be marked with a different arrow
* Clear search history could possibly have a bin as an icon instead of arrow. 
* Is it no longer an option to define direction of the buss stop as a favourite? E.g I _never_ take the buss from my house to a place further away from down town, I always take the buss to down town. Therefore it is not interesting for me to see both options if I don't state end station.
* The sorting of departures is not very logical if there is several busses you can use, or even if there is another buss stop you can walk to nearby (e.g Prinsenkrysset).
* Selecting travellers: Could there be a note about categories with relevant information connected to it? E.g how old can my child be without me having to pay? When is a person youth, and so on. This note could appear below all traveler categories when one of them is chosen, since there is a lot of dead space there.

Zone selection:
* Choosing a zone, the one you are going to select (from or to) should have a heavy font-weight to make it more intuitive what happens when you press the map each time. 
* Also if you pressed the wrong zone, your intuition would probably be to press once more to correct this. It could then be frustrating not knowing you are changing the other direction. Using a heavy font-weight on the direction you are currently choosing, could fix this issue as well. 
* Not sure "same zone" is clear enough if you are traveling inside one zone. Thinking the zone name should appear regardless. 
* Red and green as colours. Red is a colour with a lot of connotations. User could think the choice is not valid or the zone not active? 

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [ ] Renders colors as expected in dark and light mode.
- [ ] Is translatable to English and Norwegian.
- [ ] Does not drain battery
- [ ] Works in up to 200% font size
- [ ] Is operable and perceivable using screen reader

**Comment by mikaelbr** [comment]
@gorandalum see suggested improvements for zone selection ☝️

**Comment by mikaelbr** [comment]
> Is it no longer an option to define direction of the buss stop as a favourite? E.g I never take the buss from my house to a place further away from down town, I always take the buss to down town. Therefore it is not interesting for me to see both options if I don't state end station.

@LineLuna Alternative solution for this is marking departure as favorite and only showing favorites.

**Comment by mikaelbr** [comment]
> The sorting of departures is not very logical if there is several busses you can use, or even if there is another buss stop you can walk to nearby (e.g Prinsenkrysset).

This is something we've discussed before without finding a good solution currently. For context @pettersuul @hildeor

**Comment by mikaelbr** [comment]
> Selecting travellers: Could there be a note about categories with relevant information connected to it? E.g how old can my child be without me having to pay? When is a person youth, and so on. This note could appear below all traveler categories when one of them is chosen, since there is a lot of dead space there.

There's been some work on descriptions for these categories. cc @vidtil

**Comment by gorandalum** [comment]
Maybe you can take a look at the suggested improvements for zone selection @pettersuul?

**Comment by pettersuul** [comment]
Added prototype with zone-selection improvements here: https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=4921%3A1694&viewport=799%2C220%2C0.7115080952644348&scaling=min-zoom&page-id=3577%3A6873

**Comment by gorandalum** [comment]
Zone improvements implemented in #1071
