### ISSUE TITLE
Error in MainActivity

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#1053]
## Error in MittAtb

**Error** in **MainActivity**
Geolocation error: No location provider available.

[View on Bugsnag](https://app.bugsnag.com/atb-as/mittatb/errors/606df4bc684ad500075d4514?event_id=606df4bc00770ad666b30000&i=gh&m=ci)

## Stacktrace

    src/GeolocationContext.tsx:100 - anonymous
    src/GeolocationContext.tsx:98 - anonymous

[View full stacktrace](https://app.bugsnag.com/atb-as/mittatb/errors/606df4bc684ad500075d4514?event_id=606df4bc00770ad666b30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by monopoint** [comment]
probably a snag
