### ISSUE TITLE
Set up simulated routes to easier debug location in development

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#109]
Already tested with `gpx` format in XCode, and seems to work fine.

Drew up map with alltrails.com and export to file:
![image](https://user-images.githubusercontent.com/4932625/77848132-d5a25080-71c2-11ea-91ae-5679377395df.png)

The coordinates do change in simulator. Need to find some way to control speed.
![image](https://user-images.githubusercontent.com/4932625/77858329-25a10780-7203-11ea-8b23-aa5272572b1e.png)

**Comment by gorandalum** [comment]
Closing until we receive feedback regarding infrequent update rate from users.
