### ISSUE TITLE
Gjøre det mulig for kunden å velge at en mobiltelefon skal overta som aktivt token 

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1090]
## Opprinnelse

Krav fra Entur + I tråd med avklaringer om idbasert-konsept hos AtB avklart i møte 17.3.21 med bl.a. Grethe.

## Motivasjon

En gitt billettkonto skal bare være tilgjengelig fra den mobilen som er registrert som et aktivt token på billettkontoen. Gjennom https://github.com/AtB-AS/mittatb-app/issues/1089 introduserte vi to ulike visninger av billetter avhengig av om mobilen er aktivt token eller ikke. 

I denne saken gjør vi det mulig for kunden å velge at en ny mobiltelefon skal overta som aktivt token. Dette er for eksempel relevant ved bytte av en mobiltelefon. 

## Hypoteser og antagelser

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Løsningsforslag

[Prototype](https://www.figma.com/proto/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?page-id=617%3A17654&node-id=1072%3A31996&viewport=334%2C48%2C0.33&scaling=scale-down&starting-point-node-id=1072%3A31996&show-proto-sidebar=1)
[Skisser](https://www.figma.com/file/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?node-id=1072%3A31996)

<img width="1392" alt="Skjermbilde 2021-09-15 kl  10 27 49" src="https://user-images.githubusercontent.com/8980523/133398470-af3ba049-660e-4bce-8fb0-52a9cd9993c7.png">

## Akseptansekriterier

- [] Farger vises som forventet i både lys og mørk visningsmodus.
- [] Fungerer både for norsk og engelsk språk.
- [] Trekker ikke unødvendig batterikapasitet.
- [] Fungerer med opptil 200% fontstørrelse
- [] Kan brukes og forstås med skjermleser

**Comment by hildeor** [comment]
Overlapp med #1398 . Lukker denne og så åpner vi heller nye hvis det blir behov for å dele opp i mindre oppgaver.
