### ISSUE TITLE
[Android] Small Android viewport on some screens

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#111]
Testing on an older Android device shows that parts of the UI is obscured by the tab.

The first thought here is, "ScrollView!". But that is a cheap solution. And on a screen which might be used every day, it is very bad UX.

We might want to scale fonts differently [depending on available space](https://reactnative.dev/docs/dimensions), maybe render less dots. And if all else fails, enable a ScrollView if content still is obscured.

![Screenshot_2020-03-30-07-36-23](https://user-images.githubusercontent.com/4932625/77879370-90316200-725a-11ea-9309-bc7bac351f6b.png)

**Comment by gorandalum** [comment]
Closing as this issue is outdated. The current design works good on Nexus 4.
