### ISSUE TITLE
[Feature] Øk mellomrom mellom bunn-navigasjon og soft-buttons på Android

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#1110]
## Origin

Både selvopplevd og innspill fra bruker på Intercom.

## Motivation
Minske risiko for å trykke på feil knapp.

## Proposed solution
Sjekk at det i underkant av bunn-navigasjon er minimum et visst antall piksler (12?). Jeg mistenker at dette gjelder på Android telefoner hvor safe are bottom blir evaluert til 0.

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Litt luft mellom bunn-navigasjon-knapper og soft-touch-buttons slik at det ikke er stor fare for misclick.
- [] Mellomrom også tilstede ved 200% font size.

<img width=400 src="https://user-images.githubusercontent.com/675421/116278626-f69ef180-a786-11eb-9633-79464a642a23.jpeg"/>

**Comment by monopoint** [comment]
Safe area kalkuleres riktig på android, men på IOS så har bunn-navigasjonen en litt mer generøs padding som gir mer naturlig avstand til appen. 
La på en ekstra padding på android på 12 pikseler som foreslått, endringen er godkjent av @pettersuul

**Comment by tormoseng** [comment]
Ser greit ut i staging på Android 7.0
