### ISSUE TITLE
[Feature] Gjøre det mulig å betale med betalingskort og lagre kortet

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1112]
**Konseptuell beskrivelse og behov som skal løses**
Gjøre det mulig for kunder å betale med et betalingskort, og lagre kortet slik at de slipper å taste inn alle kartdetaljer hver gang.  

**Lenker til brukerinnsikt eller brukerrapport**
(vi har fått noe feedback fra pilotkunder som reagerte på at vi kun hadde vipps som betalingsmåte. må letes fram)

**Hypotese og foreslått løsning**
Vi antar at vi kan løse dette teknisk sett på samme måte som Entur har løst det i sin app, og at det vil dekke behovene, 

**Annen nyttig kontekst**
Vi har implementert betaling med kort i app, men har ikke fått på plass mulighet til å lagre kortet. Entur har denne muligheten i sin app - for kunder som har opprettet brukerprofil, så vi antar at det er løsbart i vår app også for kunder som har brukerprofil.

**Comment by hildeor** [comment]
Duplikat av #1497
