### ISSUE TITLE
[Feature] Mulighet for å vise fram billetter/qr-kode uten mobildatatilgang

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1116]
**Konseptuell beskrivelse og behov som skal løses**
Kunder som mangler mobildata må likevel kunne vise fram QR-kode ved billettkontroll, slik at kontrollører kan verifisere at de har gyldig billett.

Det må avklares om det også skal være mulig å vise fram billett til sjåfør uten mobildatatilgang. 

**Lenker til brukerinnsikt eller brukerrapport**

**Hypotese og foreslått løsning**

**Annen nyttig kontekst**

**Comment by vidtil** [comment]
Kanskje allerede ivaretatt godt nok. Bør verifiseres.

**Comment by tormoseng** [comment]
@vidtil Ved å sette på flymodus når appen har lastet med billetter så kunne QR-kode hentes frem fra alle aktive billetter.
