### ISSUE TITLE
[BUG] WCAG: tastaturfelle på reisesøk

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1153]
### Observasjon
Hvis man navigerer TIL reisesøk fra f. eks Billetter-fanen så havner fokus på overskrift "Reisesøk" men herfra klarer man ikke navigere voiceover hverken frem eller tilbake. Man må fysisk trykke på et annet element på skjermen for å komme ut av tastaturfellen, mens sveip til høyre/venstre ikke fungerer i dette tilfellet. Forekommer kun hvis man navigerer til reisesøk fra en annen fane.

**Kun IOS**

**Comment by monopoint** [comment]
@gorandalum kan du ta en titt på denne?

**Comment by cbrevik** [comment]
Kjent "feil" på bakgrunn av denne endringen er at "alternativ tittel" leses opp rett etter header. Skal se på om den kan gjemmes i en separat PR. Ikke blocking slik jeg ser det.

**Comment by tormoseng** [comment]
Testet OK på iOS i staging! Enig med @cbrevik at "alternativ tittel" ikke er blokkerende.
