### ISSUE TITLE
[BUG] WCAG: Disablede input-felter er mulig å aktivere med skjermleser

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1155]
### Observasjon
- I kjøp billett-modalen så er disablede komponenter mulig å aktivere og navigere inn i
- Ser ut til å bare gjelde Android

**Testbeskrivelse**
Gå til billetter
Klikk ny bilett
her er (per nå) 2 felter disabled.
med aktiv skjermleser er det mulig å navigere til disse feltene og aktivere dem, som navigerer til modalen for valg på feltene.

**Comment by hildeor** [comment]
Regner med dette er på Android? Går ikke an å navigere inn på dem på iOS.

**Comment by tormoseng** [comment]
Testet OK på Android og iOS

@monopoint Forskjellen mellom Android og iOS er at iOS sier "lenke", mens Android sier "Lenke slått av"

**Comment by tormoseng** [comment]
Denne er grei.
