### ISSUE TITLE
[BUG] WCAG: Skjermleser leser ikke opp verdiene i kjøp-billett-skjemaet

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1158]
### Observasjon
Når man prøver å kjøpe billett med skjermleser, leses ikke verdiene som er valgt i skjeamet.
dette er problematisk fordi vi freslås verdier i alle feltene, men disse blir ikke kommunisert til synshemmede.

**Comment by tormoseng** [comment]
Testet OK på Android og iOS
