### ISSUE TITLE
[Feature] Gå fra "beta-design" til "lanseringsdesign"

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1168]
Petter detaljerer denne...
Husk å ta med endringer i onboarding.

**Comment by pettersuul** [comment]
# Oppsummert:
- Cyan headere og forsidebakgrunner blir nå mørkegra med tilhørende lys tekstfarge
- Cyan knapper blir nå blå med tilhørende mørk tekstfarge
- Blå infobokser blir cyan
- "Posisjon" og "velg i kart" byttes til secondary-knapper i lys tekstfarge
- Ny onboarding med velkomst-tekst og eventuell intercom-tekst

## Components 1.0

### Ny bakgrunnsfarge
- Header = Secondary / 1
- Buttons / Tab-group = Secondary / 1
- Inputs / Patterns / Assistant + Search + Departure  = Secondary / 1

### Ny tekstfarge
- Header = Text / Light / Primary
- Header / Tab-bar / Inactive = Text / Light / Primary
- Infobox / Highlight = Text / Light / Primary
- Infobox / Message / Info = Text / Dark / Primary
- Buttons / Block / Primary = Text / Light / Primary
- Buttons / Inline / Primary = Text / Light / Primary
- Buttons / Compact / Primary = Text / Light / Primary

## Ny bakgrunnsfarge på favoritt-knapper
- Inputs / Patterns / Assistant + Search + Departure  = Primary / 2

## Endret knappetype
- Inputs / Patterns / Search / "Posisjon" + " Velg i kart" = Secondary

## Theme 1.0

### Endring av themefarge
Light-mode / Primary / 2 = #007C92 - Blue / 500
Light-mode / Primary / 3 = #71D6E0 - Cyan / 500
Light-mode / Secondary / 3 = #5F686E - Gray / 400
Light-mode / Status / Info = #71D6E0 - Cyan / 500

## Onboarding

App 1.0 / Action / Onboarding:
![image](https://user-images.githubusercontent.com/56530785/119142877-418aec80-ba47-11eb-8e55-ef0adc80f13d.png)

**Comment by gorandalum** [comment]
Klar for testing i staging. Testingen går da i hovedsak ut på å gå gjennom alle kriker og kroker av appen og se at det er i tråd med designet i Fima.

**Comment by tormoseng** [comment]
Har gått gjennom light- og dark-mode på Android og iOS, og har ikke funnet noe - bortsett fra kommentarene postet på Slack #a-app-qa.

Fint om flere går gjennom denne.

**Comment by tormoseng** [comment]
Denne har blitt testet mer i staging. OK!
