### ISSUE TITLE
[Feature] Ta bort "beta"- og "pilot"-begreper i tekster

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1169]
Apple tillater ikke at apper i App Store beskrives som "beta" eller "pilot". Vi må derfor endre tekstene slik at vi unngår disse begrepene, men likevel får fram riktig budskap til kundene. 

Vedlegget inneholder oppdaterte tekster for app store, og oppdaterte tekster i selve appen.

**Comment by vidtil** [comment]
[Tekster i app og App-store ved lansering.docx](https://github.com/AtB-AS/mittatb-app/files/6537361/Tekster.i.app.og.App-store.ved.lansering.docx)

**Comment by monopoint** [comment]
I tillegg til vedlegget har jeg endret følgende:
Mitt AtB: 
"Beta-funksjonalitet" -> "Ny funksjonalitet"
"Beta features" -> "New features"

**Comment by tormoseng** [comment]
Spash på Android er testet OK i staging

**Comment by tormoseng** [comment]
Ser ikke se at det henger igjen noen beta i tekstene nå.
