### ISSUE TITLE
[Feature] Sikre at betingelser for billettkjøp er tilgjengelig i appen

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1173]
**Konseptuell beskrivelse og behov som skal løses**
Kunder som kjøper billetter i appen, må ha mulighet til å finne beskrivelser av ulike betingelser som gjelder for billettkjøp og reiser med appen som "billettbærer". Vi må vurdere alt innhold som i dag vises i menyvalget "Info og priser" i dagens Mobillett:
![IMG_766195C0E44C-1](https://user-images.githubusercontent.com/34686997/119650682-635be900-be24-11eb-9657-4e71be4d6297.jpeg)
  

**Lenker til brukerinnsikt eller brukerrapport**
(Eventuelle lenker til Intercom eller annen feedback.)

**Hypotese og foreslått løsning**
Vurderinger gjort i møte 25.5.21:

- Vi kan plassere dette innholdet nederst i "Mitt AtB" der vi i dag har et valg for "Personvernerklæring". "Mitt AtB" er den mest naturlige plasseringen i forhold til de andre "fanene" vi har i dag. 
- Vi vurderer alt innholdet som ligger i Mobillett i dag, men det kan hende at vi slår sammen innholdet i noen av sidene som finnes der i dag. 
- Vi må avklare om tekstene skal ligge i appen eller på atb.no. En mulig fordel ved å ha de i appen er at de blir tilgjengelige også uten nettilgang. Fordelen ved å ha de på atb.no er at de er enklere å oppdatere, og kan gjenbrukes på tvers av nettbutikk og app. 

**Annen nyttig kontekst**
(Nevn annen nyttig informasjon og lenker som kan være viktig for denne oppgaven)

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by vidtil** [comment]
Julia spesifiserer hvilke tekster som skal inn.

**Comment by JuliaOppegard** [comment]
[Tekster til app_NOR.docx](https://github.com/AtB-AS/mittatb-app/files/6561242/Tekster.til.app_NOR.docx)
[Tekster til app_ENG.docx](https://github.com/AtB-AS/mittatb-app/files/6561243/Tekster.til.app_ENG.docx)

**Comment by JuliaOppegard** [comment]
[Tekster til app_ENG.docx](https://github.com/AtB-AS/mittatb-app/files/6574416/Tekster.til.app_ENG.docx)
[Tekster til app_NOR.docx](https://github.com/AtB-AS/mittatb-app/files/6574417/Tekster.til.app_NOR.docx)

Ny setning lagt til på engelsk:
If you uninstall the app, the tickets will be removed. We recommend that you do not uninstall once you have purchased tickets. If you uninstall, you will not be able to present a valid ticket.

**Comment by tormoseng** [comment]
@gorandalum Noen kommentarer
- Tekst for billettkontroll: "Ved billettkontroll vil kontrolløren trykke på noen aktive felter på skjermbildet for billett, for å verifisere at billetten er en aktiv billett og ikke et skjermbilde (screenshot)." Dette har vi vel ikke i dag.

- Lenke for billettrefusjon/ticket refund (under Billettkjøp) kommer ikke frem på min Samsung A5 (2016) Android 7.0. Den forsvinner bak manyknappene
![192028952_201668341689413_1255562582614005386_n](https://user-images.githubusercontent.com/5812433/120324974-80426180-c2e7-11eb-8180-31feb095f821.jpg)

- Samme for Ticket inspection: Her faller lenkene under Transport regulations bort. Får ikke scrollet ned.

**Comment by tormoseng** [comment]
Re-testet OK i staging.

Evt tekstendringer på billettkontroll vil komme.

**Comment by JuliaOppegard** [comment]
[Tekster til app_ENG.docx](https://github.com/AtB-AS/mittatb-app/files/6592103/Tekster.til.app_ENG.docx)
[Tekster til app_NOR.docx](https://github.com/AtB-AS/mittatb-app/files/6592104/Tekster.til.app_NOR.docx)

Tekster ligger vedlagt. Oppdatert tekst om billettkontroll erstatter første avsnitt på norsk og engelsk:

During ticket inspections, open your app and select the main menu "Tickets" at the bottom of the app. Select the "Valid" tab. Here you will find your valid ticket. Select "Show details / inspection". You will now receive information about the ticket and a QR code. Show this QR code to the ticket inspector who will scan it with his own equipment to check if the ticket is valid.

Ved billettkontroll, åpne appen din og velg hovedmenyen «Billetter» nederst i appen. Velg fanen «Aktive». Her finner du din gyldige billett. Velg «Vis detaljer/kontroll».  Du får nå opp informasjon om billetten og en QR-kode. Vis denne QR-koden til kontrollør som vil scanne denne med eget utstyr for å kontrollere om billetten er gyldig.
