### ISSUE TITLE
[BUG] Bedre beskrivelse og UU ved Reisesøk

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1174]
### Observasjon
Resultatene i resiseøk leses opp som "Aktiver for å få flere reisedetaljer", istedet burde linjenummer og navn, avgangstid ved nærmeste holdeplass og avgansdetaljer leses opp.

Resultat-elementet burde være atomisk og ikke gi mulighet for å navigere seg inn i sub-elementer, men swipe til neste burde istedet gå til neste resultat.

**Comment by tormoseng** [comment]
Testet OK på iOS 14 og Android 7.0 i staging
