### ISSUE TITLE
[Feature] Sikre at kunder som tar i bruk billettering i åpen beta er informert om gjeldende muligheter og begrensninger. 

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1177]
**Konseptuell beskrivelse og behov som skal løses**
Ved lansering av appen skal enkeltbilletter være tilgjengelig for alle kunder. Vi avventer imidlertid innloggingsfunksjonaliteten, noe som betyr at kunder må få informasjon om begrensningene ved anonyme billettkjøp. 
I tillegg ønsker AtB å informere om status for billetteringsfunksjonaliteten, og planer videre. Dette for å unngå at kundene har feil forventninger til "modenheten" for denne funksjonaliteten. 

**Lenker til brukerinnsikt eller brukerrapport**
n/a

**Hypotese og foreslått løsning**
Forslaget er at innholdet i Billettfanen ved installasjon av appen kun viser en komponent med informasjon om billetteringsfunksjonaliteten. Kunden må klikke på en knapp for å akseptere budskapet i denne siden før den faktiske billetteringsfunksjonaliteten kommer til syne.  

Illustrasjon:
![image](https://user-images.githubusercontent.com/34686997/119620831-bbcfbe00-be05-11eb-927b-830a5785276a.png)

**Annen nyttig kontekst**
(Nevn annen nyttig informasjon og lenker som kan være viktig for denne oppgaven)

---

## Akseptansekriterier
- [ ] Etter installasjon av appen skal informasjonskomponenten vises når kunden navigerer til "Billetter". Fanene for "Kjøp", "Aktive" og "Utløpte" skal ikke være tilgjengelige. Knappen(e) for å kjøpe billetter skal heller ikke være tilgjengelige. 
- [ ] Idet kunden klikker på knappen for å akseptere budskapet i informasjonskomponenten, skal fanene for "Kjøp", "Aktive" og "Utløpte", med tilhørende funksjonalitet, bli tilgjengelig.  
- [ ] Etter at kunden har klikket på knappen for å akseptere budskapet i informasjonskomponenten, skal denne komponenten ikke vises flere ganger. Dette gjelder også ved omstart av appen. Ved sletting av appen og reinstallasjon kan komponenten vises på nytt og kreve ny aksept fra brukeren. 
- [ ] Teksten må vises på riktig språk (norsk/engelsk)
- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by hildeor** [comment]
Bør det være mulig å lese disse begrensningene senere? Bør vi også skrive noe på AtBeta om det?
Ellers tenker jeg det ser greit ut.

**Comment by magnusolderoesaether** [comment]
Ny copy på NO og EN er lagt til i skissene til @pettersuul .
![image](https://user-images.githubusercontent.com/50573205/119790336-22bba880-bed4-11eb-8466-7f130d3624fe.png)

**Comment by tormoseng** [comment]
Testet OK i staging med iOS og Android på NO og ENG
