### ISSUE TITLE
[BUG] UU Testaturfelle: tastatur skjules ikke ved skjermleser-navigasjon

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1181]
### Observasjon
I søkemodal: Hvis man begynner å skrive i søkefelt, og deretter flytter fokus til søkeresultat listen, så blir tastaturet liggende oppå listen og man får ikke navigert ved swipe nedover listen til de resultatene som ligger under tastatur. (Gjelder både på reisesøk og Avganger)

**Comment by monopoint** [comment]
Denne tror jeg ikke det er så mye å gjøre med. Skjermleser er en egen layer som ligger over appen, og skjermleserens fokus er ikke en del av appen på en slik måte at vi kan reagere på det programmatisk.
Jeg mistenker at skjermleser-brukere veldig vant med at de må skjule tastaturet for å navigere videre i appen.

**Comment by monopoint** [comment]
Sjekk hva apper fra NRK og Ruter gjør i disse tilfellene

**Comment by cbrevik** [comment]
Kjører blur på input-feltet ved escape-gesture. Dette vil også skje selv om input ikke er focused, så hvis vi skal ha flere actions på escape må vi i framtiden håndtere noe bedre i view-hiarchy her. Altså f. eks. "navigate back" hvis input ikke er focused. La også til at header ikke skulle fokuseres først i søk-modalen, som betyr at input fokuseres først.

**Comment by tormoseng** [comment]
Testet OK på iOS i staging
