### ISSUE TITLE
[BUG] UU feil fokus ved nav til Be-om-kvittering

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1187]
### Observasjon

Når man navigerer til Be om kvittering så flyttes fokus direkte til inputfelt.

### Analyse
Vi tvinger fokus programmatisk til inputfeltet som en tjeneste for brukeren, fordi det er den oppgaven brukeren skal gjøre på denne skjermen. men for en skjermleser, blir dette lite inuituvtt fordi skjermleseren hopper da over title, og det poppes et tastatur.
Vi kan løse dette ved å teste for skjermleser, men her avsløres det da et annet problem. Hvis vi prøver å sjekke screenreaderEnabled via accessibilityInfo, får vi timing issues. AccessibilityInfo er asynkron, som betyr at den returnerer false umiddlebart, og så settes til true etter noen millisekunder. dermed settes fokus til input uansett, og tastur poppes, og deretter settes UU-fokus til header, og brukeren er i en ganske forvirret state.
For å løse dette må vi enten pause appen til AccessibilityInfo returnere skikkelig, eller vi må teste AccessibilitiInfo før vi prøver å rendre skjermen. Den siste løsningen lar seg ganske elegant implementeres med ContextAPI. 

### Implementasjon
Lage en context-provider som tester for skjermleser.
Komponenter som tester AccessibilityInfo for screenReaderEnabled, må ikke benytte context, men det er en fordel at vi tester for skjermleser på en konsistent måte. Det gjelder følgende komponenter:
- Ticket Receipt (prøver å sette fokus til input hvis SR ikke er aktiv)
- Sort favorites (viser drag-and-drop-sortering hvis SR ikke er aktiv)
- Sonevelger (viser liste istedet for kart når SR er aktiv)
- Compact Map (f.eks på reisedetaljer. Kart er slått av hvs SR er på og brukeren har Iphone)
-

**Comment by monopoint** [comment]
@cbrevik påpeker at denne omskrivingen kan påvirke en kjent feil der autofokus ikke settes på enkelte skjermer. Vi har tidligere en issue der autofokus ikke blir satt fordi skjermen ikke var ferdig rendret, og for å fikse dette ble det lagt til en timeout på noen millisekunder. @tormoseng Det kan derfor være ekstra lurt å teste at autofokus funker på alle skjermer der brukeren skal fylle inn et skjema som et naturlig første steg.

**Comment by tormoseng** [comment]
Ser bra ut for meg i staging for både iOS og Android
