### ISSUE TITLE
[BUG] UU Tittel får ikke fokus ved scale transitions

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1189]
### Observasjon

Endre favorittsted: hvis man endrer navn på en favoritt og trykker 'retur' på tastaturet, hopper fokus til "lukk". Burde heller vært tittel av siden.

ikke samme men liknende problem på Android, der fokus flyttes til en system-meny.

### Analyse

Det er flere symptomer som går litt på det samme. Det ser ut som ved transitions er ikke header tilgjengelig for setFocusOnLoad når funksjonen fyres av. i ios er det gjort tiltak for å forsinke setFocus, men ikke på android. Det ser ut til at forsinkelsen må økes en del og på begge platformer, for å sikre at elementene som skal ha focus eksisterer. Testing på Android tyder på at denne bør være 200ms for å funke i alle situasjoner.

### Fix
Setter timout til 200ms for setFocusOnLoad

#### Testbeskrivelse
Testes kanskje lettest på redigering av favoritter
- Gjør klar noen favoritter og favorittsteder.
- Aktiver Talkback / Voice Over
- Naviger til Mitt Atb
- Naviger til Favoritter / Steder
- Observer at tittel "Favorittsteder" får fokus
- rediger en favoritt
- Observer at Tittel "Endre Favorittsted" får fokus
- Gi favoritten et nytt navn og velg lagre
- Observer at du navigeres til forrige skjerm
- Observer at tittel "Favorittsteder" har fokus

**Comment by tormoseng** [comment]
Testet OK med VoiceOver/iOS + TalkBack/Android på staging
