### ISSUE TITLE
[BUG] UU bedre brukervennlighet ved Endre/Legg til Favorittsted

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1190]
### Observasjon

Endre/legg til favorittsted: felt for å endre sted bør annonsere noe om at man kan aktivere for å endre sted. Når man så kommer inn på søk er det først info om tekstfeltet "Sted" som leses først, deretter kommer "søk, overskrift". Dette til tross for at det er overskrift som faktisk er i fokus.

### Analyse
1. legg til bedre a11y-labels
2. Søk etter steder har en timer som automatisk setter fokus (ikke SR-fokus, men vanlig fokus) som forstyrrer opplevelsen med skjermleser, som da får både header og søk i fokus samtidg som tastatur popper opp. autofikus bør bare settes hvis skjermleser er av

### Fix
La til a11ylabel "Steder, Endre favorittsteder"
Ikke aktiver timer for autofokus hvis skjermleser er aktiv

**Comment by tormoseng** [comment]
Denne høres fin ut på TalkBack og VoiceOver
