### ISSUE TITLE
[BUG] UU brukeropplevelse på endre rekkefølge på favorittsted

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1191]
### Observasjon
Endre rekkefølge på favorittsteder: kan være fordelaktig om vi dropper eget fokusfelt for emojis her

### Fix
Ikon er ikke lenger fokusbart ved skjermleser
La til opacity for disablede piler på slik at de ikke blir usynlige slik at layout ser mye mer ryddig ut

**Comment by tormoseng** [comment]
OK på VO/iOS + TB/Android
