### ISSUE TITLE
[BUG] UU feil fokus ved slett-favorittavgang

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1192]
### Observasjon

Hvis man sletter en favorittavgang flyttes også fokus til "Tilbake" i stedet for pagetitle

Oppdatering:
Klarer ikke å gjenskape denne som beskrevet på android. Istedet leses den slettede favoritten opp, og SR-fokus forsvinner fra skjermbildet.

Fikses mest sannsynlig av #1189

**Comment by tormoseng** [comment]
OK i staging med VO/iOS + TB/Android
