### ISSUE TITLE
[BUG] UU Ikke fokuserbare betalingsknapper

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1194]
### Observasjon
På Kjøp billett er betalingsknappene disablet for focus også hvis man f eks ikke klarer å hente billett fra Entur. De bør være mulig å flytte fokus til, selv om de ikke er klikkbare. ~~Se f. eks "Velg reisende"-modalen for eks på disablet knapp men som fortsatt er en del av focus~~. Dette gjelder både ved bruk av hurtigkjøp via Siste kjøp og via Kjøp ny enkeltbillett/periode-flytene.

### Analyse
Dette er et problem som gjelder alle våre buttons. Vi implementerer selv en Button-komponent som rendrer en React Native TouchcableOpacity (TO). 
disabled=true på TO disabled knappen for vanlige, men ikke for UU. så det betyr at selv om knappen ser disabled ut, så kan man utføre handlingen som er koblet til knappen med en skjermleser (1).
Mulig at det var forsøkt en workaround for dette ved å sette importantForAccessibility=false når disabled er true, men dette gjør at knappen blir usynlig for skjermleseren hvis den er diabled (2).

### Implementasjon
(1) Løses ved å kun tilegne onPress-funksjonen hvis knappen ikke er disabled. Så hvis disabled == false så blir onPress = undeined.
(2) Løses ved å ta bort mekanismene som setter importantForAccessibility = false, og erstatte det med accessibilityState: disabled når disabled == true.

### Testbeskrivelse
Litt usikker på hvordan man best kan få disablet knappene i Ticketing, men de vil bli satt disabled hvis man ikke får svar fra url = 'ticket/v1/search/zones'
Sjekk at knappene funker som de skal når de ikke er disabled, og alt er normalt, både med og uten skjermleser.
når de er disabled skal 
- de være fokuserbare med skjermleser. 
- Talkback/voice over skal opplyse om at knappen er deaktivert.
- Når bruker med skjermleser prøver å aktivere knappen skal det ikke skje noe.

**Comment by tormoseng** [comment]
Testet OK i staging
