### ISSUE TITLE
[BUG] UU Utidig varsel om "Søkeresultater er lastet inn"

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1197]
### Observasjon

Send kvittering: Ved navigering til "Send"-knappen på send kvittering får man annonsert "Søkeresultater er lastet inn"

### Analyse
Dette skjer fordi reisesøk er en asynkron prosess som kan returnere reisesøk etter brukeren har navigert bort. Vi kan gjøre en mer aggressiv kansellering av søk hvis brukeren navigerer bort, men vi vil da istedet få beskjed om at ingen resultater er lastet. Jeg synes uansett at det er bra at søket kan gå i bakgrunnen, for da viser vi det fram når brukeren navigerer tilbake. 

I begge tilfellene er løsningen å sørge for at skjermleseren bare annonserer søkeresultat-status når Søkeresultat-skjermen vises.

### Implementasjon
bruker en navigation hook som forteller om skjermen har fokus, og oppdaterer skjermleser-meldingen kun hvis den har det.

**Comment by tormoseng** [comment]
Testet OK i staging
