### ISSUE TITLE
[BUG] Knotete bytte mellom lys/mørk bakgrunn

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#1198]
## Bakgrunn

I ny theme er det både mørk og lys bakgrunnsfarge på forskjellige skjermbilder, som igjen krever lys og mørk tekst. Det krever da også at fargen på teksten i statusbar endrer seg, noe som ikke fungerer så bra med animasjoner i appen.

Konstruert eksempel:
<img width=400 src="https://user-images.githubusercontent.com/675421/119662124-51347780-be31-11eb-8449-d98a52560881.gif"/>

## Løsningsforslag
Jeg vil tro vi sparer oss mye trøbbel hvis vi klarer å få themen til å fungere med kun en statusbar-tekstfarge. Altså kan være forskjellig for light/dark-mode, men ikke forskjellig fra skjermbilde til skjermbilde.

**Comment by hildeor** [comment]
Lurer på om denne er utdatert nå? @gorandalum

**Comment by gorandalum** [comment]
Ja. Denne ble "fikset" ved at headerfarge er lik både i light og dark mode.
