### ISSUE TITLE
Fjern ticketing splash før lansering

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1201]
Ticketing splash scrren med info om beta-kode etc skal fjernes før lansering

**Comment by gorandalum** [comment]
Selv med nyinstallert app skal man komme rett til billetteringsfunksjonaliteten uten at man må skrive inn betakode.

**Comment by tormoseng** [comment]
Ingen info om beta-kode for å kjøpe billett nå. Testet OK i staging.
