### ISSUE TITLE
[Feature] Oppdatere onboarding-tekst

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/mittatb-app#1211]
Tekst:

**Velkommen til AtB appen**
Her kan du planlegge reiser og sjekke avgangstider i hele Trøndelag. Snart kan du også kjøpe dine billetter i appen. Følg med!

**Bidra til å gjøre appen bedre**
Vi ønsker dine tilbakemeldinger for å gjøre appen bedre. Dette gjør du enklest i chatten i høyre hjørne. Chatten er anonym.

![image](https://user-images.githubusercontent.com/56530785/120196277-f4193700-c21f-11eb-9370-b1cc7f1fbc86.png)

https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=5222%3A21656

**Comment by tormoseng** [comment]
Testet OK med iOS/Android i staging
