### ISSUE TITLE
[Feature] Bakgrunnsbilde på tomt reisesøk

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/mittatb-app#1213]
Når brukeren står på forsiden av reisesøk (ikke gjennomført et søk enda) vil bakgrunnen være et bilde.
Bildet skal ha en lineær fargegradient i "Background / Gray" (#37424A) som går fra 100% gjennomsiktighet i bunn, til 0% i topp.
Headeren får en gjennomsiktighet på 75% "Background / Gray" (#37424A) for å garantere kontrast mot tekst.

![image](https://user-images.githubusercontent.com/56530785/120162545-cbca1200-c1f8-11eb-8b27-55da63b30902.png)

I videre versjoner ønskes det at bildet kan byttes i forhold til sesonger eller datoer (f.eks. jul, 17. mai, vår, osv.) men det er ikke nødvendig nå.

Bilde som skal inn:
![jeswin-thomas-uwNj0GN4ioU-unsplash](https://user-images.githubusercontent.com/56530785/120162406-a2a98180-c1f8-11eb-8f3f-ecd28a7c85ab.jpg)

Figma:
https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=5393%3A191

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by tormoseng** [comment]
Testet fint på Android.

@gorandalum siste versjon av iOS-appen (1.8 (1622553411)) har ikke bakgrunnsbilde, men heller ikke den vanlige grå fargen.
![189560600_571555017166756_47023616912681180_n](https://user-images.githubusercontent.com/5812433/120334556-03b48080-c2f1-11eb-8774-f750570511c1.jpg)

**Comment by tormoseng** [comment]
Testet OK på Android/iOS i staging
