### ISSUE TITLE
Appikon for Android

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1214]
Appikonet må oppdateres med nye farger

**Comment by tormoseng** [comment]
Laster ned siste fra staging (1.7 (1622465933)) og får da mr Android opp som ikon. Dette er en Samsung A5 (2016) med Android 7.0.
![189252212_4200119216676748_4844798992159759798_n](https://user-images.githubusercontent.com/5812433/120204196-d69c9b00-c228-11eb-87eb-c75bed1ec366.jpg)
