### ISSUE TITLE
Appikon for ios

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1215]
appikonet må oppdateres med nye farger

**Comment by tormoseng** [comment]
Laster ned nyeste fra staging (1.7 (1622465825)) og får da samme ikon som tidligere; blå AtB med QA.
![189139496_901888070543959_2780692964978522741_n](https://user-images.githubusercontent.com/5812433/120203964-950bf000-c228-11eb-8ca9-bf3824606b00.jpg)

**Comment by tormoseng** [comment]
Oppdatert versjon har nå nye farger. Da er denne grei!
![189593176_835673440367517_6312833863191841682_n](https://user-images.githubusercontent.com/5812433/120280103-8ddff300-c2b7-11eb-9600-513aa5f40a67.jpg)
