### ISSUE TITLE
[BUG] Manglende hurtigbåt frem i tid

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#1248]
Ved søk så skal det skje minst 24 timer frem i tid, men søk på "Nå" viser ikke avganger for hurtigbåten i morgen, men kun reise med buss og kun ette resultat.

**Comment by tormoseng** [comment]
@mikaelbr Spørsmål: Ved reisesøk Trondheim hurtigbåtterminal - Vanvikan på tidspunkt nå så listes de 4 neste avgangene opp. Endrer jeg retning (bytter avgangssted) på søket så listes alle i dag + i morgen opp. Er det en årsak for dette?

**Comment by mikaelbr** [comment]
Godt spørsmål. Det som er spesifisert er opp til 2 dager med resultater begrenset til 10 resultater. Jeg opplever det ikke fungerer med 2 dager og at det er 1 dag som er grensen. Ellers er resultatet noen ganger litt snodig og returnerer uventede ting osv. Foreløpig er det formelle svaret at vi må oppgradere til Open Trip Planner 2 om det er tilfeller hvor søkeresultatet er uventet..

**Comment by tormoseng** [comment]
Da er denne testet OK i staging!
