### ISSUE TITLE
[BUG] UU: Endre fra AtB til ATB for a11y

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1254]
### Observasjon
Talk back klarer ikke å uttale AtB slik vi forventer, men sier istedet Atb eller noe som høres ut som Att eller bare Æ.

### Fix
Endre a11y-labels til ATB

**Comment by tormoseng** [comment]
@monopoint Henger fortsatt igjen "Att" ved oppstart. Både ved åpningssplash, og på onboarding "Velkommen til Att appen". Ellers fint med "Mitt AtB" og overskrift her.

**Comment by monopoint** [comment]
Nei, det er ingen måte å sette a11y tittel på selve appen. Vi kunne ha brukt ATB som app-navn, men da går det ut over merkevaren vil jeg tro

**Comment by tormoseng** [comment]
Joda, app-tittelen ved oppstart er en ting, men etter installasjon kommer onboardingsstegene med info. Og her er det en “Velkommen til AtB…” mld hvor brukeren trykker seg videre før reisesøk åpenbarer seg. det var her jeg tenkte at man evt også burde si “AtB” og ikke “Att”.

**Comment by monopoint** [comment]
fikset!

**Comment by tormoseng** [comment]
Denne er nå fin!
