### ISSUE TITLE
Kartlegge omfang av å gå over til OTP2

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1258]
**Konseptuell beskrivelse og behov som skal løses**
Vi har opplevd et tilfelle der en kunde etterlyste et reiseforslag i appen. Da vi tok det opp med Entur svarte de at de var obs på at dette kunne skje, og at dette var forbedret i OTP2. 

Vi vet at OTP2 har noen forbedringer på andre områder også, og at det er OTP 2 som er i fokus hos Entur framover - og ikke OTP1. 

Vi bør derfor finne ut mer om omfang/konsekvenser av å gå over til OTP2. 

**Lenker til brukerinnsikt eller brukerrapport**
(Legge inn svaret fra Entur om at reiseforslag mangler i OTP1, men vil vises i OTP2?) 

**Hypotese og foreslått løsning**
Vi gjør en kartlegging av omfanget av å gå over fra OTP1 til OTP2 slik at vi letter kan vurdere hva som er et hensiktsmessig tidspunkt for å gå over til OTP2. 

**Annen nyttig kontekst**
...

---

**Comment by rosvik** [comment]
Etter å ha sett en del på ruteforslag, kan jeg si at reiseforslagene til OTP1 og OTP2 veldig ofte er forskjellige. Hypotesen er jo at OTP2 er "bedre", men dette er veldig vanskelig å måle objektivt, og det er kanskje bare brukerne som kan svare på om forslagene fungerer bedre i deres situasjon.


## Søkevindu

En konkret forandring derimot, er et nytt parameter i JourneyPlanner `searchWindow`, som bestemmer hvor langt frem i tid det skal søkes etter reiser. Fra dokumentasjonen:

> searchWindow: The length of the search-window in minutes. This is normally dynamically calculated by the server, but you may override this by setting it. The search-window used in a request is returned in the response metadata. To get the "next page" of trips use the metadata(searchWindowUsed and nextWindowDateTime) to create a new request. If not provided the value is resolved depending on the other input parameters, available transit options and realtime changes.

Mine søkeforsøk brukte som standard ofte et søkevindu på 80 minutter, mens det kan se ut som om OTP1 har et mye større søkevindu, og gir ofte reiseforslag for neste dag hvis der er få muligheter.

Dette krever en litt annen tilnærming for reisesøk enn vi har i dag, kanskje slik som Entur løser det:

> 1. Gjer eit kall uten å spesifisere searchWindow
> 2. Bruk metadata.nextDateTime og metadata.searchWindowUsed i responsen frå første kall i dei neste kalla. Då står JourneyPlanner for generering av search windows, og burde få med seg alle resultat. Det blir paginering av søkeresultat, sånn nesten.
> 3. Dersom metadata ikkje blir returnert, avslutt søket.


## Korrespondanser

Det jeg har sett på mest de siste dagene, er forskjell i korrespondanser mellom OTP1 og OTP2. Her er resultatet ikke helt krystallklart, men det kan se ut som om OTP1 kommer med forslag om korrespondanse marginalt oftere enn OTP2. Mistanken er at dette henger sammen med søkevindu, og at det egentlig ikke er særlig forskjell på korrespondanser mellom de to versjonene. 

Resultat og fremgangsmåte for analysen kan finnes her: https://github.com/AtB-AS/korrespondanse-check/blob/main/interchanges.ipynb
