### ISSUE TITLE
Sikre at Roboto brukes som font på Android

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1259]
## Observasjon
Flere brukere  observerer at grafiske elementer og tekst kuttes på Oneplus telefoner

- legg inn stoff fra Slack
- vil det fortsatt være mulig å overstyre for brukere som ønsker en annen font (f.eks. dyslektikere)? 

## Analyse
Innrapporterte saker gjelder eldre Oneplus-telefoner. fysisk test på nyere oneplus-telefoner har ikke denne feilen.
Oneplus har anerkjent problemet og har sagt at de skal komme med en fiks, hvorvidt de har pushet denne fiksen til alle telefoner vet jeg ikke. Graving på internett sier at oppo-telefoner også har denne feilen, men det er ikke ven veldig vanlig telefon i norge.
Feilen oppstår fordi det er en bug i fonten til Oneplus. Feilen kan omgås ved at brukere setter systemfont til Roboto, og dette er bekreftet av brukere på intercom.
Siden gangske mange brukere er berørt av feilen, kan vi fikse dette ved å bundle Roboto og overstyre systemfonten i vår app. Da legger vi samtidig inn en toggle slik at brukeren kan benytte systemfont likevel, slik at vi ivaretar støtte for de som vil benytte en dysleksi-font eller har spesifikke ønsker til font.

### Android
Denne er litt tricky å teste. For å teste at den opprinnelige feilen faktisk er fikset, må vi få tak i en gammel oneplus som har denne feilen, og det har vi pt ikke tilgjengelig.
Finn en måte å endre systemfont. Dette er mulig på f.eks samsung, LG og oneplus-telefoner (ymmv)
- Sett en systemfont som er lett å kjenne igjen
- Åpne appen og observer at Robot brukes i appen (ikke systemfont)
- Gå til Mitt AtB / Utseende og toggle "Bruk telefonens skrifttype"
- Observer at systemfont brukes over alt i appen
- Sjekk at engelske oversettelser i Mitt AtB / Utseende er ok
- toggle tilbake og observer at Robot igjen blir brukt.

### iPhone
- Observer at systemfont benyttes
- Observer at det ikke finnes noen instillinger for å overstyre systemfont. Disse skal kun vises på android.

**Comment by gorandalum** [comment]
**Bakgrunn**
Flere saker fra Intercom som denne: 
https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400008523

Tekst kuttes. Det virker som alle innmeldte tilfeller er Android OnePlus.

En tråd som beskriver trolig lignende problem her:
https://github.com/facebook/react-native/issues/15114

**Comment by gorandalum** [comment]
**Løsningsforslag**
Virker som vi har tre valg basert på tråden fra RN Github over

- Embedde med roboto-font slik at den er tilgjengelig for OnePlus-devicer. Som nevnt [her](https://github.com/facebook/react-native/issues/15114#issuecomment-335797756).
- Legge inn en små-hackish overstyring på Text sin render slik at lucida grande brukes hvis spesifisert font ikke er tilgjengelig. Som nevnt [her](https://github.com/facebook/react-native/issues/15114#issuecomment-360029841).
- Sjekke om `textBreakStrategy: 'simple'` kan fikse problemet. Som nevnt [her](https://github.com/facebook/react-native/issues/15114#issuecomment-576313266).

Uansett tror jeg vi trenger et test-device for å finne en god løsning.

**Comment by monopoint** [comment]
Dette er en kjent feil på Oneplus' custom font, og er egentlig et problem som oneplus skal fikse. jeg stemmer for at denne utgår. Brukere som klager kan få beskjed om å bytte font til Roboto inntil videre.

**Comment by monopoint** [comment]
https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/search/conversations/159245400000076?q=one%20plus&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all

**Comment by monopoint** [comment]
Det virker som det gjelder eldre oneplus-telefoner (6 og 5T)

**Comment by monopoint** [comment]
må nedgradere cocoapods til 1.10.1 før det merges
