### ISSUE TITLE
[Feature] Ved markering av favorittavgang skal brukeren få mulighet til å valge om det skal gjelde kun en tur eller alle turer for det linjenummeret.

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#1260]

**Comment by tormoseng** [comment]
@gorandalum Dette er forsåvidt en kommentar som evt kan tas som en forbedring. Har det vært tenkt på å oppdatere søk ved endring av favoritter når favoritt-toggling er på i Avganger? F.ex om favoritt er en spesifikk tur for et linjenummer, filtrer kun favoritter, for deretter å endre favoritten til alle turer for linjenummeret.

https://user-images.githubusercontent.com/5812433/123313968-4cdfa500-d52a-11eb-9655-235a6a14371f.mp4

**Comment by tormoseng** [comment]
Dette ser ut til å fungere veldig bra!

@gorandalum En liten detalj som skiller seg med VoiceOver (iPhone 12 mini) vs TalkBack (Android 7.0)
- VO: markerer favoritt og velger alle variasjoner av en linje, så flyttes fokus til Avganger nede på menyen. Upraktisk hvis man da sveiper til siden for å kunne markere f.ex Vis kun mine favoritter.
- TB: markerer favoritt og velger alle variasjoner av en linje, så leses det opp "Lagt til", men ingenting har fokus. Sveip til siden gir fokus på AtB-logo.
