### ISSUE TITLE
[BUG] Rette feil beskrivelse av gyldighetsperiode i billettbetingelser

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1273]
Gjelder teksten som kommer fram når man trykker på "Mitt AtB", og scroller ned til valget "Billettkjøp" under "Info og priser":

**Avsnitt som skal endres:**
Reiser i én sone: 90 minutter
Reiser i to soner: 2 timer
Reiser i tre eller flere soner: 4 timer og 30 minutter

**Ny tekst:** 
Reiser i én sone: 1 time og 30 minutter
Reiser i to soner: 2 timer og 30 minutter
Reiser i tre soner: 3 timer og 30 minutter
Reiser i fire soner: 4 timer og 30 minutter

Ta kontakt med sjåføren om du har behov for en overgangsbillett.

**Comment by vidtil** [comment]
@JuliaOppegard: Ok å endre teksten slik? Skal vi ha med fem soner også? Jeg stoppet på fire soner fordi pristabellen under denne teksten bare går opp til fire soner...

**Comment by JuliaOppegard** [comment]
@vidtil Dette ser bra ut! Vi har ikke med 5-sonereiser som eksempel fordi en slik reise i realiteten ikke finnes.

**Comment by monopoint** [comment]
Engelsk oversettelse for
" Ta kontakt med sjåføren om du har behov for en overgangsbillett"
"Please contact the driver if you need a transfer ticket."

**Comment by monopoint** [comment]
![image](https://user-images.githubusercontent.com/1464594/123057682-5e309080-d408-11eb-8a5c-feb8345c3ce8.png)
![image](https://user-images.githubusercontent.com/1464594/123057767-70123380-d408-11eb-9bc4-78368b3fa0ce.png)

**Comment by tormoseng** [comment]
Testet OK
