### ISSUE TITLE
Gjøre det mulig å få fram igjen "onboarding"-budskapet for billettering etter å ha klikket det bort

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1274]
**Konseptuell beskrivelse og behov som skal løses**
Vi får en del henvendelser på Intercom fra kunder som etterlyser periodebilletter og betaling med kort. Dette til tross for at de har passert "onboarding"-skjermbildet for billettering der det er informert om disse begrensningene. 

Det er naturlig at en del kunder klikker seg forbi onboarding-skjermbildet uten å lese, eller få med seg, budskapet. Pr i dag er det ikke mulig å få fram denne informasjonen igjen etter at den er klikket bort. 

**Hypotese og foreslått løsning**
Vi antar at det er vil være nyttig å synliggjøre en mulighet til å få fram igjen onboarding-skjermbildet. Forslaget er å løse dette ved å alltid vise en informasjonstekst øverst i billettkjøp-fanen.

**Akseptansekriterier**

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by vidtil** [comment]
@pettersuul: Legger du inn skisse på denne saken? Pluss eventuelle endringer i teksten dersom den bør oppdateres for å fungere både initielt og ved ny visning. 

Vi snakket også om å legge inn en lenke til en webside som inneholder ofte spurte spørsmål. I såfall må vi avklare hvordan en slik lenke skal vises, og hvor den skal lede hen.

**Comment by pettersuul** [comment]
Direkte gjenbruk av onboardingskjermen:
https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=5609%3A22444
![Screenshot 2021-06-22 at 08 20 03](https://user-images.githubusercontent.com/56530785/122874206-02e09e80-d333-11eb-9e3b-86922527999c.png)

Tenker det funker greit, og man må trykke Godta for å "åpne" billettfanen igjen.

**Comment by tormoseng** [comment]
@monopoint Ser bra ut. 

Små kommentarer:
- TalkBack/Android 7.0: Etter å ha hentet opp betingelsene på nytt og trykket Godta, så settes ikke fokus noe sted. Sveip til siden fokuserer på "Billetter - overskrift". Gjentas hver gang.
- VoiceOver/iOS 14: Etter å ha hentet opp betingelsene på nytt og trykket Godta, så settes fokus på en av mine tidligere billetter. Hos meg den midterste hver gang. Gjentas hver gang.

**Comment by monopoint** [comment]
Takk, @tormoseng !
skal se på det
