### ISSUE TITLE
Tekstendring for å lettere forstå funksjonaliteten for å gjenta "siste kjøp"

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#1275]
Hypotese: 
Listen under ledeteksten "Siste kjøpte billetter" kan misforstås til å være kjøpshistorikken. For å tydeliggjøre at innslagene i listen egentlig fungerer som snarveier til å gjenta tidligere kjøp, bør ledeteksten endres til f.eks. "Kjøp på nytt:" eller "Gjenta tidligere kjøp".

Jeg tror ikke vi har fått tilbakemeldinger fra kunder på dette, så det er ikke sikkert hypotesen stemmer. Misforståelsen har imidlertid dukket opp internt i AMP/AtB et par ganger.

**Comment by vidtil** [comment]
@hildeor / @pettersuul: Hva tror dere om denne? Var det noen indikasjoner i brukertestene på at dette kunne misforstås? Skal vi vente på evt feedback før vi gjør noe, eller er dette en kurant endring?

**Comment by pettersuul** [comment]
Kan ikke huske at det har vært noen spesielle tilbakemeldinger rundt det, men tenker at det ikke kan skade å heller kalle det f.eks. "Kjøp på nytt"

**Comment by tormoseng** [comment]
Testet OK i staging
