### ISSUE TITLE
com.facebook.react.bridge.JSApplicationIllegalArgumentException in MainActivity

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#1295]
## Error in MittAtb

**com.facebook.react.bridge.JSApplicationIllegalArgumentException** in **MainActivity**
Error while updating property 'endNode' of a view managed by: RNSharedElementTransition

[View on Bugsnag](https://app.bugsnag.com/atb-as/mittatb/errors/60daed44bb496c000825156e?event_id=60daed44007f581c33f70000&i=gh&m=ci)

## Stacktrace

    ViewManagersPropertyCache.java:100 - com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp

[View full stacktrace](https://app.bugsnag.com/atb-as/mittatb/errors/60daed44bb496c000825156e?event_id=60daed44007f581c33f70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by cbrevik** [comment]
Rydder opp i gamle issues
