### ISSUE TITLE
[Feature] Huske "Vis bare favorittavganger" i app

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1316]
## Origin

Ref: https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400043037#part_id=initial-part-159245400043037-904108040

## Motivation

Vi har snakket om dette tidligere også, men vi har fått konkret tilbakemelding om at det er ønskelig at dette huskes i appen når det settes.

## Hypotheses and assumptions

- De som bruker favoritter på Avganger vil ofte ønske å få raskere oversikt over disse favorittene
- De tar ofte buss fra holdeplasser hvor de har valgt favorittavganger, og vil ofte ønske å ha den på

## Proposed solution

Vi kan lagre når dette valget er skrudd av og på. 

## Acceptance Criteria

- [ ] Valget om å skru av / på favorittavganger er gjeldende på tvers av appsesjoner
- [ ] Hvis du skrur på "Vis bare favorittavganger", og det er ingen på valgt holdeplass, så kommer det opp en info-melding om at vi ikke fant noen favorittavganger

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by tormoseng** [comment]
Testet OK i staging!
