### ISSUE TITLE
[BUG] Treg geolocation uthenting overskriver valgt "fra" på Reisesøk

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1317]
### Observasjon
Ref: https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400042975#part_id=comment-159245400042975-9836135235

Treg geolocation uthenting overskriver valgt "fra" på Reisesøk. Må reproduseres.

### Analyse
Når appen starter, setter vi igang geolocation-spørring, og med en gang vi får en geolocation fra OSet, så  setter vi geolocation som fra-posisjon.
For å løse dette bør vi sjekke om det står noe i fra-feltet før vi setter geolocation her. 

### implementasjon
la inn en sjekk på om fra-feltet allerede er satt, i funksjonen som prøver å sette geolocation ved oppstart

### Testbskrivelse
Litt vanskelig å teste denne siden det ikke finnes noen gode utvikler-strategier for å simuere treg geolocation resolveing. Jeg la inn litt logging i dev-versjonen og løp ned i parkeringskjelleren for å kunne gjenskape at posisjonering gikk litt tregt, og da klarte jeg å verifisere at det funker som tiltenkt.

Når appen starter og posisjonering begynner, skal man klare å sette "fra"-posisjon manuelt ganske raskt ved å trykke på en favoritt. favoritten vil legge seg inn i fra eller til-feltet avhengig av hva som er tomt. hvis man klarer å gjøre dette før geolocation er resolvet, skal man havne i den situasjonen som denne saken dreier seg om. Tidligere ble fra-feltet overskrevet med geoposisjon, men nå skal bruker-verdien bevares.

**Comment by monopoint** [comment]
logikken her er ganske tydelig, vi setter "fra" når vi får geolocation, uansett om brukeren har fylt inn noe eller ikke. det er derimot litt vanskelig å gjenskape og teste situasjonen

**Comment by tormoseng** [comment]
Fikk delvis fremprovosert å sette favoritt som Fra på en gammel Android 7.0. Fungerte som tiltenkt. Forøvrig regresjonstest OK.
