### ISSUE TITLE
NSInvalidArgumentException in RNSScreenContainer.m:144

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1341]
## Error in MittAtb

**NSInvalidArgumentException** in **RNSScreenContainer.m:144**
*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil

[View on Bugsnag](https://app.bugsnag.com/atb-as/mittatb/errors/60e8272defbd720007f66358?event_id=60e8272d007f81f459f00000&i=gh&m=ci)

## Stacktrace

    /Users/runner/work/mittatb-app/mittatb-app/node_modules/react-native-screens/ios/RNSScreenContainer.m:144 - -[RNSScreenContainerView attachScreen:atIndex:]
    /Users/runner/work/mittatb-app/mittatb-app/node_modules/react-native-screens/ios/RNSScreenContainer.m:189 - -[RNSScreenContainerView updateContainer]
    /Users/runner/work/mittatb-app/mittatb-app/node_modules/react-native-screens/ios/RNSScreenContainer.m:282 - __41-[RNSScreenContainerManager markUpdated:]_block_invoke

[View full stacktrace](https://app.bugsnag.com/atb-as/mittatb/errors/60e8272defbd720007f66358?event_id=60e8272d007f81f459f00000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by cbrevik** [comment]
Denne er det samme som #1247 og #1236 - bare med dSYMs applied

Ser ut som det er relatert til https://github.com/software-mansion/react-native-screens/issues/943

Vi må se på å oppgradere fra `react-native-screens` `2.17.1` til `3.4.0` - det kan ha bieffekt/konsekvenser, så dette utsettes til høsten.

**Comment by cbrevik** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**NSInvalidArgumentException** in **RNSScreenContainer.m:144**](https://app.bugsnag.com/atb-as/mittatb/errors/60e8272defbd720007f66358?event_id=61078264007f83d1f7b30000&i=gh&m=fx)

**Comment by tormoseng** [comment]
Har ikke funnet noe galt rundt om på iOS (14.4) og Android (7.0). Sender denne saken videre siden denne saken vil testes videre gjennom andre saker + regresjonstest i QA
