### ISSUE TITLE
[BUG] [UU] SR leser opp forrige valgte ankomstested når feltet er blankt

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1349]
### Observasjon
Ved reisesøk på startskjermen, hvis man f.eks klikker en favoritt slik at det blir satt som ankomststed og gjennmfører et søk, for deretter å klikke reset (logo øverst til venstre) oppstår denne buggen.
Nå er skjemaet resatt, og feltet for ankomstested er tomt. Men hvis man setter fokus på dette feltet med skjermleser, leses det opp at ankomststed er satt til det du brukte sist.

### Analyse
accessibiliy label blir ikke resatt skikkelig når location er undefined.

### Implementasjon
accessibilitylabel settes til tom streng når location er undefined

### Testbeskrivelse
se Observasjon

**Comment by tormoseng** [comment]
Testet OK i staging
