### ISSUE TITLE
[BUG] Spinner vises ikke ved første innlasting av søkeresultater

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1359]
### Observasjon
Hvis man trykker på en favoritt på startsiden, scroller header opp og resultater lastes inn. Vi kan så vidt se spinneren før den brått forsvinner, og skjermen er blank, uten indikator på at resultater lastes inn, helt til resultatene vises. Her er det meningen at spinneren skal vises hele tiden mens resultater lastes inn. Hvis man sveiper ned for å laste inn på nytt oppfører spinneren seg som den skal, så dette gjelder bare når man går fra startskjermen.

### Analyse
Grunnen til at Spinneren forsvinner er at HeaderContentHeight endrer seg mellom start skjerm og resultatsskjerm. Når spinneren animeres benyttes HeaderContentHeigh for å evaluere hvor animasjonen skal gå fra, og når den brått endres, feiler animasjonen og spinneren forsvinner. 

Grunnen til at HeaderContentHeight endrer seg mellom startskjerm og resultatskjerm, er fordi headeren bytter mellom å vise Favoritter og AvgangsTid-Knapp. Disse elementene har forskjellig høyde, som spesifisert i Figma, men det fører til at vi får ett hopp i høyden på HeaderContent.
Dette hoppet fører også til at animasjonen mellom startskjerm og resultatskjerm ikke matcher helt, og Header-animeres til feil posisjon før den brått flyttes til rett posisjon.

Byttet mellom favoritter og avgangstid bugger også ut, fordi det her benyttes et triks med position: absolute for å tvinge disse to elementene til å ligge oppå hverandre istedet for etter hverandre vertikalt, men problemet er at avgangstid ikke håndterer å vises med position: absolute, og rendres feil, og fører til at vi får et blink og at knappen vises som en for firkant uten tekst nederst i venstre hjørne ved animering (se screenshot)

![image](https://user-images.githubusercontent.com/1464594/125940096-ae739bf6-b603-4d4a-b859-d42eda1703d3.png)

Hele denne animasjonen tar bare 400 millisekunder, så det er ikke så lett å få med seg alt det rare som skjer, men man får definitivt et inntrykk av at noe er galt i tillegg til at spinner ikke vises.

### Implementasjon
- FadeBetween komponenten får en attribute "preserveHeightFrom" som tar in key til det barnet som skal diktere høyden for FadeBetween-komponenten. perserveHeight settes til det elementet som har størst høyde. Da bevares høyden gjennom hele animasjonen og vi unngår at vi får hopp i layout etter animasjonen er ferdig, pluss at spinneren ikke får satt ny (forskjellig) verdi i mens søket er i gang. 
- Barnene i FadeBetween får satt bredde til 100% for å unngå at layoutet kollapser hvis et barn får satt position:absolute
- Logikken i FadeBetween skrives om slik at man ikke får race conditions når animasjonen reverseres. Nå bevares Opacity-verdien for hvert enkelt barn gjennom hele livstiden til komponentene ved å styres eksplisitt av parent.

**Comment by monopoint** [comment]
Denne fikser også at scroll overshoot blir feil i ios med mindre skjermer (iphone 8), som er rapportert av flere brukere.

Den introduserer en liten feil der topp og bunn padding i scrollView blir for store.

**Comment by tormoseng** [comment]
Spinner-problematikk er testet OK i staging for både iOS og Android
