### ISSUE TITLE
Avganger som passerer/har passert er ikke leselig nok

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1392]
**Describe the bug**
Når en avgang endres til "Nå" blir knappen etter hvert disablet og grå. Har fått feedback fra kunde om at denne er dårlig universelt utformet via Kundeservice.

Eksempel (dark mode, men gjelder også light mode):
![544E67A3-2690-4127-807A-F30E46D14650](https://user-images.githubusercontent.com/8980523/127854774-fbee661e-3f5e-4e32-a7c7-8f97491c1892.png)

**Forslag til endring:**

I stedet for at disse knappene blir helt grå, så blir teksten "Nå" gjennomstreket. Selv om knappen er inaktiv da, så er den meningsbærende.

**Comment by tormoseng** [comment]
Testet OK i staging på iOS + Android
