### ISSUE TITLE
Gjøre det mulig å toggle mellom tokens (reisebevis)

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1398]
## Opprinnelse
Når mobil token introduseres trenger man en måte å angi hvilket token som skal være aktivt. Et token kan være t:kort eller mobiltelefon.
Krav fra Entur + I tråd med avklaringer om idbasert-konsept hos AtB avklart i møte 17.3.21 med bl.a. Grethe.

## Motivation
_A short description of what user needs or business goals this feature will solve._

En gitt billettkonto skal bare være tilgjengelig fra den mobilen som er registrert som et aktivt token på billettkontoen. Gjennom #1089 introduserte vi to ulike visninger av billetter avhengig av om mobilen er aktivt token eller ikke.

I denne saken gjør vi det mulig for kunden å velge at en ny mobiltelefon skal overta som aktivt token. Dette er for eksempel relevant ved bytte av en mobiltelefon.

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

### App: 

~- [ ] #1621~

[Prototype](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=6218%3A24406&node-id=6242%3A34004&viewport=406%2C48%2C0.51&scaling=min-zoom&starting-point-node-id=6242%3A34004&show-proto-sidebar=1)
[Skisser](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6242%3A34004)

<img width="1392" alt="Skjermbilde 2021-09-15 kl  10 27 49" src="https://user-images.githubusercontent.com/8980523/133398470-af3ba049-660e-4bce-8fb0-52a9cd9993c7.png">

### Nettbutikk:

[Prototype](https://www.figma.com/proto/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?page-id=1105%3A15144&node-id=1969%3A23028&viewport=334%2C48%2C0.16&scaling=scale-down&starting-point-node-id=1969%3A23028&show-proto-sidebar=1)
[Skisser](https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=1969%3A23028)

<img width="1763" alt="Skjermbilde 2021-09-15 kl  12 42 38" src="https://user-images.githubusercontent.com/8980523/133419460-f3ba9a67-bac8-473c-a1cb-bdf73f1453ff.png">

**Comment by hildeor** [comment]
Duplikat av #1621 ?

**Comment by rosvik** [comment]
> Duplikat av #1621 ?

Tanken var vel at 1621 skulle være app spesifikk (derav "... i app"), siden denne også nevner webshop. Mulig der er bedre å lukke en av de, og så heller ha en egen issue under AtB-as/webshop.

**Comment by hildeor** [comment]
Aha. Jeg antok denne var bare app fordi den ligger i mittatb. Vi har separate issues i webshop-repoet også:

- https://github.com/AtB-AS/webshop/issues/60
- https://github.com/AtB-AS/webshop/issues/454
- https://github.com/AtB-AS/webshop/issues/455

**Comment by rosvik** [comment]
Like greit å lukke denne da, og bruke 1621 fremover?

**Comment by hildeor** [comment]
Jepp, lukker
