### ISSUE TITLE
[BUG] Avganger påfølgende dager bør vise dato

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#1401]
Ved søk etter avganger henter vi avganger opp til 48t frem i tid, men maks 7 per linje. I visse tilfeller kan dette føre til at man får opp avganger som er to dager senere, uten at det er spesifisert hvilken dato det gjelder.

Eksempel her hvor søk er gjort på torsdag, så får man opp nattbuss som går 02:28 natt til lørdag.
<div>
<img width="400" src="https://user-images.githubusercontent.com/675421/128365456-6ff8aef7-c13e-49ad-87c9-10220858c2e0.jpg"/>
<img width="400" src="https://user-images.githubusercontent.com/675421/128365463-f94a3982-60c4-4774-a636-bcf50ee113e9.jpg"/>
</div>

Mulige løsninger:
- Vis dato på avganger som er påfølgende dag.
- Vis dato på avganger som er mer enn 24t frem i tid.
- Kun hent avganger 24t frem i tid (krever kun endring i bff).
- Mer omstendelig løsning, som for eksempel en ny rekke per dato. 

Jeg heller mot at vi nå kun henter 24t frem i tid, som har blitt mer aktuelt etter at man la inn datovelger på Avganger-fanen også.

**Comment by tormoseng** [comment]
Overtatt av #1800
