### ISSUE TITLE
Endre fra AM/PM til 24h ved engelsk systemspråk/appspråk

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/mittatb-app#1403]
### Observasjon
I dag bruker appen AM/PM dersom systemspråk er satt til engelsk. Dette er uhensiktsmessig siden få engelskspråklige brukere benytter dette systemet. Vi har også tilbakemeldinger fra norske brukere med norsk språk i app som av ulike årsaker benytter engelsk systemspråk som fra AM/PM.  Vi må derfor endre til 24H

### Analyse
Feilen oppstår kun på IOS og kun ved engelsk språk.
På Android kan man manuelt overstyre om tid skal vises som 12h/24h, og det er allerede gjort (alltid 24h)
På IOS kan man styre hvordan tid vises ved å sette locale. Dette er gjort, men locale-strengen vi benytter i appen spesifiserer bare språk og ikke område. IOS defaulter dermed til US som område når EN er satt som språk, og US benytter 12h.
(med andre ord bruker vi ikke en ekte locale-streng i appen)

### Implementasjon
Innfører en LocaleProvider som henter Locale fra systeminstillinger.
Vi benytter alltid region fra system-locale, mens språk hentes enten fra instillinger eller fra system-locale, hvis system-språket støttes i appen. Hvis system-språk er ukjent, defaulter vi til engelsk språk.
LanguageProvider forenkles og henter nå språk fra LocaleProvider.
IOS time picker endres til å ta med locale, slik at systemets locale bestemmer om tidsvelger skal vise 12h eller 24h.
android er uendret og viser alltid 24h.

### Testbeskrivelse
- Test at språk hentes fra system, hvis systemspråk er satt i instillinger
- Test at språk defaulter til engelsk hvis et språk som ikke er støttet appen er valgt i system (f.eks svensk)
- ios:
  - sett system-region til US
  - naviger til avganger og velg tidspunkt. observer at tidsvelgeren viser AM/PM uanvhengig av valgt språk i app.
  - sett system-region til NO. observer at tidsvelgeren viser 24H uavhengig av valgt språk i app.

**Comment by cbrevik** [comment]
Konkret tilfelle: https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400043555#part_id=comment-159245400043555-10298277911

**Comment by monopoint** [comment]
Ser ut som dette gjelder kun dato/tidsvelgeren, alle andre tidspunkt i appen er 24h ved engelsk språk.
Ser også ut som dette kun gjelder IOS. Dato/tidsvelger er ikke en react nativ komponent, men en OS-komponent.

**Comment by monopoint** [comment]
Denne feilen oppstår kun når man har valgt engelsk som spåk på IOS.
Feilen oppstår fordi locale-strengen vi bruker i appen kun spesifiserer språk og ikke region. dermed blir regionen satt til US når man har valgt engelsk som språk, og US bruker AM/PM.
Alle regionene definert under norsk locale, har 24h.

**Comment by tormoseng** [comment]
Testet OK på iOS i staging
