### ISSUE TITLE
[BUG] Visuell strek mellom DisappearingHeader og søkefelt for noen tekststørrelser

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1423]
**Describe the bug**
På reisesøk dukker det opp en strek mellom DisappearingHeader og søkefelt når enheten er satt til noen tekststørrelser globalt. Dette ser ut til å være `useCalculateHeaderContentHeight` som ikke gir heltall høyde.

**Application version**
Version number: 1.10

**To Reproduce**
1. Gå til Reisesøk
1. Juster enheten sin tekststørrelse
	- iOS: Settings > Display & Brightness > Text Size
	- Simulator: Features > Decrease Preferred Text Size
3. Streken dukker kun opp ved noen av tekststørrelsene

**Screenshots**
![IMG_5752](https://user-images.githubusercontent.com/1774972/128675305-d414789b-dd57-4ec9-a239-43629364d45e.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 7, iPhone 11
 - OS: 14.4

**Comment by tormoseng** [comment]
Testet OK i staging

**Comment by tormoseng** [comment]
Denne er grei i QA for iOS, men henger litt igjen for Android 7.0. Buggen er såpass liten at release går og ny sak er opprettet i #1491
