### ISSUE TITLE
[BUG] Tab-navbar blokkerer deler av innhold når tekststørrelse er mindre enn normalen

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1425]
**Describe the bug**
Når tekststørrelsen er satt til mindre enn normalen (fontScale er mindre enn 1), skjules nedre del av innhold, fordi kalkulert høyde på navbar er for liten. Problemet er synlig på reisesøk-skjermen, ved at der er for lite avstand mellom favoritter og navbar, når tekststørrelsen er liten.

**Application version**
Version number: v1.10

**To Reproduce**
1. Sett enheten sin tekststørrelse til minimum
	- iOS: Settings > Display & Brightness > Text Size
	- Simulator: Features > Decrease Preferred Text Size
2. Åpne reisesøk i appen og observer avstand mellom favoritter og navbar

**Expected behavior**
Forventer at der er like stor avstand over og under favoritter, slik som ved større tekststørrelser.

**Screenshots**

<img width="482" alt="fontscalebug" src="https://user-images.githubusercontent.com/1774972/128681228-ae98d143-d8f7-49cb-a0af-1bdc52c81f82.png">

https://user-images.githubusercontent.com/1774972/128681053-575d2836-afc3-4e16-81da-18afa27b197d.mov

**Smartphone (please complete the following information):**
 - Device: iPhone 7, iPhone 11
 - OS: iOS 14.4

**Comment by tormoseng** [comment]
Testet OK i staging
