### ISSUE TITLE
Strukturere kontaktinfo og kanaler

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1429]
## Origin

_Links to received feedback, user research or other findings._

Brukes endel tid på å sluse videre henvendelser som kommer via Intercom til kundeservice. Ønsker derfor å strukturere henvendelsene i større grad ved å sluse henvendelsene til riktig sted.

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

![Contact](https://user-images.githubusercontent.com/8980523/128700326-ffe1faab-8d44-4c03-a06f-fb2024c0cf23.png)

- Tekst kommer fra @magnusolderoesaether 
- Lenke til kundeservice skal lede til https://www.atb.no/kundeservice/ 
- Lenke til Figma: https://www.figma.com/file/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?node-id=677%3A26278

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by magnusolderoesaether** [comment]
Har endret tekstene - OK

**Comment by tormoseng** [comment]
Testet OK på iOS i staging

@rosvik På Android 7.0 får jeg opp en feilmelding når jeg trykker på Intercom. Får valg dismiss eller reload. Relod gir en ny feilmeldingsside, mens dismiss låser hele appen.
![234254223_347227130217399_4455957427443365654_n](https://user-images.githubusercontent.com/5812433/129539763-12ca6221-ac20-418f-ba82-e2f87e87176b.jpg)
![229671285_197798285587022_7449395505994902686_n](https://user-images.githubusercontent.com/5812433/129539787-4e784365-22e9-43e2-bf36-e9155b84a238.jpg)

**Comment by tormoseng** [comment]
@rosvik Ser samme feil også i bygg 1629109499 (som inkluderer https://github.com/AtB-AS/mittatb-app/pull/1464)

**Comment by tormoseng** [comment]
Fikset av #1482 og re-testet OK
