### ISSUE TITLE
[BUG] Når man legger til "alle versjoner" av linje som favoritt, slettes linjens favorittmarkeringer ved andre holdeplasser

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1445]
**Describe the bug**
Når man lagrer alle variasjoner av en linje som favoritt, fjernes favorittmarkeringen av samme linje ved andre holdeplasser.

https://user-images.githubusercontent.com/1774972/128999876-59f6b357-1d5a-461e-b0e9-7c008d560777.MP4

I videoen kan man se at når alle variasjoner av linje 1 blir lagt til som favoritt på Prinsens gate P2, fjerner det markeringen linje 1 som favoritt på Prinsens gate P1.

Annet eksempel, med samme linje i to forskjellige retninger ved samme holdeplass.

https://user-images.githubusercontent.com/1774972/129020072-636ad377-58f1-4a56-9113-6c4d18e2b80d.MP4

**Application version**
Version number: v1.11

**To Reproduce**
1. Gå til Avganger
2. Legg til linje som favoritt ("Alle variasjoner av X" eller "Kun X")
3. Naviger til en annen holdeplass hvor samme linje også passerer
4. Legg til samme linje som favoritt, og velg "Alle variasjoner av linje X"
5. Observer at den første favoritten har blitt slettet

**Expected behavior**
Forventer at valget "Alle variasjoner av X" ikke overskriver favorittmarkeringer fra andre holdeplasser.

**Smartphone (please complete the following information):**
 - Device: iPhone 7, iPhone 11
 - OS: iOS 14.4

**Comment by tormoseng** [comment]
Testet OK i staging på iOS og Android
