### ISSUE TITLE
[BUG] Reiseplanleggeren, korrespondanse blir ikke vektlagt i reiseforslag

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1446]
**Describe the bug**
Et eksempel er søk fra Orkanger skysstasjon til Stjørdal stasjon. Linje 310 kjører fra Orkanger til Trondheim og linje 311 kjører fra Trondheim til Stjørdal.
Bussbytte er definert til Dronningens gate D2. Dette er definert i Interchanges i NeTEx.

**Application version**
Version number: 1.x

**To Reproduce**
1. Gå til Reisesøk
2. Velg Orkanger skysstasjon som avreisested
3. Velg Stjørdal som ankomststed
4. Se detaljer reiseforslag linje 310 + linje 311
5. Se at Trondheim S 13 som sted for bussbytte 

**Expected behavior**
Reiseforslaget burde være at Dronningens gate D2 er bussbytte, siden det er her disse to linjene korresponderer.

**Screenshots**
Vår app:
![image](https://user-images.githubusercontent.com/4932625/129032369-5fa100ab-f065-484a-95e6-89ed63fe470e.png)

Se forskjell fra Entur sin app:
![image](https://user-images.githubusercontent.com/4932625/129032407-2461c086-2f1b-4974-9e49-7d96bc977f15.png)

**Smartphone (please complete the following information):**
 - Device: Alle
 - OS: Alle

**Comment by rosvik** [comment]
Ser ut som om det ikke er så enkelt å vektlegge overganger høyere i reisesøk. Der finnes en [InterchangeWeighting](https://github.com/AtB-AS/atb-bff/blob/fcdf29d0bd71230a16bb2711766ffaf6894ef93f/src/graphql/journey-types.ts#L927), men ikke som kan settes av et reisesøk.

Forskjellen mellom våre resultater ser ut til å komme fra forskjeller i OTP1/journey-planner v2 og OTP2/journey-planner v3.

Eksempel på søk: [OTP1/v2 https://api.entur.io/journey-planner/v2/ide/](https://api.entur.io/journey-planner/v2/ide/?query=%7B%0A%20%20trip%28%0A%20%20%20%20from%3A%20%7B%0A%20%20%20%20%20%20place%3A%20%22NSR%3AStopPlace%3A43583%22%0A%20%20%20%20%20%20name%3A%20%22Orkanger%20skysstasjon%22%0A%20%20%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20%20%20latitude%3A%2063.29835%0A%20%20%20%20%20%20%20%20longitude%3A%209.847545%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20to%3A%20%7B%0A%20%20%20%20%20%20place%3A%20%22NSR%3AStopPlace%3A44483%22%0A%20%20%20%20%20%20name%3A%20%22Stj%C3%B8rdal%20stasjon%22%0A%20%20%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20%20%20latitude%3A%2063.469667%0A%20%20%20%20%20%20%20%20longitude%3A%2010.913716%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20numTripPatterns%3A%205%2C%0A%20%20%20%20dateTime%3A%20%222021-08-13T09%3A00%3A43.785%2B02%3A00%22%2C%0A%20%20%20%20walkSpeed%3A%201.3%2C%0A%20%20%20%20arriveBy%3A%20false%0A%20%20%29%20%7B%0A%20%20%20%20tripPatterns%20%7B%0A%20%20%20%20%20%20expectedStartTime%0A%20%20%20%20%20%20duration%0A%20%20%20%20%20%20walkDistance%0A%20%20%20%20%20%20legs%20%7B%0A%20%20%20%20%20%20%20%20mode%0A%20%20%20%20%20%20%20%20distance%0A%20%20%20%20%20%20%20%20line%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20toPlace%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20interchangeTo%20%7B%0A%20%20%20%20%20%20%20%20%20%20guaranteed%0A%20%20%20%20%20%20%20%20%20%20staySeated%0A%20%20%20%20%20%20%20%20%20%20ToServiceJourney%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20privateCode%0A%20%20%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20interchangeFrom%20%7B%0A%20%20%20%20%20%20%20%20%20%20guaranteed%0A%20%20%20%20%20%20%20%20%20%20staySeated%0A%20%20%20%20%20%20%20%20%20%20ToServiceJourney%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=) vs [OTP2/v3 https://api.entur.io/graphql-explorer/journey-planner-v3-beta](https://api.entur.io/graphql-explorer/journey-planner-v3-beta?query=%7B%0A%20%20trip%28%0A%20%20%20%20from%3A%20%7B%0A%20%20%20%20%20%20place%3A%20%22NSR%3AStopPlace%3A43583%22%0A%20%20%20%20%20%20name%3A%20%22Orkanger%20skysstasjon%22%0A%20%20%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20%20%20latitude%3A%2063.29835%0A%20%20%20%20%20%20%20%20longitude%3A%209.847545%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20to%3A%20%7B%0A%20%20%20%20%20%20place%3A%20%22NSR%3AStopPlace%3A44483%22%0A%20%20%20%20%20%20name%3A%20%22Stj%C3%B8rdal%20stasjon%22%0A%20%20%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20%20%20latitude%3A%2063.469667%0A%20%20%20%20%20%20%20%20longitude%3A%2010.913716%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20numTripPatterns%3A%205%2C%0A%20%20%20%20dateTime%3A%20%222021-08-13T09%3A00%3A43.785%2B02%3A00%22%2C%0A%20%20%20%20walkSpeed%3A%201.3%2C%0A%20%20%20%20arriveBy%3A%20false%0A%20%20%29%20%7B%0A%20%20%20%20tripPatterns%20%7B%0A%20%20%20%20%20%20expectedStartTime%0A%20%20%20%20%20%20duration%0A%20%20%20%20%20%20walkDistance%0A%20%20%20%20%20%20legs%20%7B%0A%20%20%20%20%20%20%20%20mode%0A%20%20%20%20%20%20%20%20distance%0A%20%20%20%20%20%20%20%20line%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20toPlace%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20interchangeTo%20%7B%0A%20%20%20%20%20%20%20%20%20%20guaranteed%0A%20%20%20%20%20%20%20%20%20%20staySeated%0A%20%20%20%20%20%20%20%20%20%20ToServiceJourney%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20privateCode%0A%20%20%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20interchangeFrom%20%7B%0A%20%20%20%20%20%20%20%20%20%20guaranteed%0A%20%20%20%20%20%20%20%20%20%20staySeated%0A%20%20%20%20%20%20%20%20%20%20ToServiceJourney%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

Kan altså virke som om denne er avhengig av #1258, hvis vi ikke finner noen annen måte å løse det på.

**Comment by rosvik** [comment]
Kan tyde på at dette er et enkelttilfelle som ble ordnet av å redusere byttekostnad for Dronningens gate hos Entur. Det ser ut som om korrespondanser i de fleste tilfeller vektlagt som de skal. Ref. https://github.com/AtB-AS/mittatb-app/issues/1258#issuecomment-911319007

> Resultatet er ikke helt krystallklart, men det kan se ut som om OTP1 kommer med forslag om korrespondanse marginalt oftere enn OTP2. Mistanken er at dette henger sammen med søkevindu, og at det egentlig ikke er særlig forskjell på korrespondanser mellom de to versjonene.
>
> Resultat og fremgangsmåte for analysen kan finnes her: https://github.com/AtB-AS/korrespondanse-check/blob/main/interchanges.ipynb

Jobber nå med å få inn informasjon i tilfeller der det skjer en korrespondanse (#1541), så vil det bli mulig for brukeren å se forskjell på reiseforslag med og uten.
