### ISSUE TITLE
Gjøre tidsvelger for avganger-visningen mer synlig

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1451]
## Origin

_Links to received feedback, user research or other findings._

Mange oppdager ikke at det er mulig å sette spesifikt tidsrom for når man vil se avganger. Dette har vært tilbakemeldinger både til kundeservice og via Intercom.

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

Gjøre det tydeligere at man kan velge mellom enten å vise avganger "nå" eller på en gitt dato og tidspunkt frem i tid ved å dele det opp i en toggle-knapp.

Figma-prototype: https://www.figma.com/proto/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?page-id=775%3A21581&node-id=775%3A21624&viewport=664%2C642%2C0.8187588453292847&scaling=min-zoom&starting-point-node-id=775%3A21624

Skisser: https://www.figma.com/file/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?node-id=775%3A21624

![Nå - valgt](https://user-images.githubusercontent.com/8980523/129178753-890f1a2b-f6f4-40f8-a49b-cfd60378a06f.png)
![Senere - valgt](https://user-images.githubusercontent.com/8980523/129178758-adef6517-5c22-4c27-a557-675a5fb94723.png)
![Senere- velg dato](https://user-images.githubusercontent.com/8980523/129178759-f0d0c6df-2055-4dd4-bcb4-903a30ae24ed.png)

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by tormoseng** [comment]
Testet forsåvidt OK i QA, men laget #1492 for en observasjon på iOS
