### ISSUE TITLE
Force-refresh Remote Config ved app-oppgradering

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1456]
Hvis bruker har fetchet ny config rett før hen oppgraderer versjon, så kan det være at enkelte conditionals som vurderes på versjon ikke blir oppdatert før senere. Så eksempelvis beskjed om at "bruker må oppgradere versjon" fjernes ikke selv om bruker har oppgradert versjon. 

Her burde vi potensielt legge inn en force-refresh gitt at bruker oppgraderer versjon, samt senke cache-tid på Remote Config (justert etter hvor stor pågang vi har på fetches nå).

**Comment by tormoseng** [comment]
Har verifisert så langt jeg kan ved å oppgradere mellom versjoner.
