### ISSUE TITLE
Android Switch bug

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1457]
### Observasjon
Switch komponenten i toggle mode bugger i android
det oppstår 2 feil med knappen.
- Animasjoner virker ikke alltid
- Knappen hopper frem og tilbake en ekstra gang før den settes i riktig posisjon

### Analyse
Animering av Switch har en kjent feil på android når Switch brukes innenfor React Navigation (se https://github.com/react-navigation/react-navigation/issues/8658) . Jeg har ikke klart å finne årsaken, men det er mistenkelig at Switch-knapper som rendres etter initial render ikke har denne buggen. Ved å introdusere en liten render delay i wrapperen til Switch (ActionItem) så ser det ut som om bugen motvirkes uten synlige bieffekter.

At knappen hopper fram og tilbake ser ut til å ha noe med hvordan toggle-verdien settes igjenom property inheritance istedet for å bruke local state. Nar man trykker på knappen sendes den nye verdien som en callback til parent som håndterer ny state og leverer ny state nedover i component stacken. dette ser ut til å ta litt tid.
Ved å istedet håndetere Switch state som local state forsvinner denne delayen og knappen virker som den skal

### Implementasjon 
- La inn en liten delay i ActionItem slik at rendring av Switch skjer 10ms etter initial render.
- La inn Switch state håndtering som local state

**Comment by tormoseng** [comment]
Testet OK i staging med Android + regresjon på iOS
