### ISSUE TITLE
Oppdatere informasjonsmelding i toppen av billettkjøpsfane

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/mittatb-app#1458]
Vi får svært mange spørsmål om kjøp av periodebillett fra appbrukerne våre, og vi har behov for å tydeliggjøre begrensningene. Foreslår derfor at infofeltet øverst i billettkjøpsfanen endres fra å kun lenke til forutsetninger, til å fortelle brukerene at kun enkeltbillett er tilgjengelig per nå, og at AtB Mobilett er et alternativ. Vi må IKKE lenke til AtB Mobilett siden det vil hindre godkjennelse i AppStore. 

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)
![image](https://user-images.githubusercontent.com/50573205/129206113-c833e9df-f5a9-4a7b-97f7-4ed27c2f2c1b.png)

**Comment by magnusolderoesaether** [comment]
![image](https://user-images.githubusercontent.com/50573205/129362417-f553da21-30e2-47c7-894b-d1e7efa0c6aa.png)

Tekster:  NO: Foreløpig kan du kjøpe enkeltbillett for buss/trikk i appen. Andre billettyper finner du i appen AtB Mobilett.
EN: Right now, the app offers single tickets for bus/tram only. Use the app AtB Mobilett to purchase other ticket types.

Husk bold-formatering på enkeltord

**Comment by tormoseng** [comment]
Testet OK i staging
