### ISSUE TITLE
[BUG] manglende emoji-støtte for android

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1489]
### Observasjon
Enkelte av emojiene fremstår som firkant med kryss i på android

### Analyse
Støtte for de forskjellige offisielle emoji-versjonene blir rullet ut til android per API-level. Dette er delvis støttet i appen, ved at vi sjekker emoji-versjon mot API-level, men det er enkelte hull som gjør at emojis som ennå ikke er støttet blir forsøkt vist.
Vi sjekker eksempelvis mot versjon 11.0, men ikke mot 11.1, og 11.1-emojiene kommer da gjennom filteret. Pixel telefoner støtter emoji-versjoner tidligere enn andre androids. Det blir overkill  støtte spesifikke brands for denne funksjonaliteten, så pixel-versjoner bør ignoreres. Enkelte brands har sine egne stiler for emojis, men Android har offisiell støtte for spesifikke emoji-versjoner, og for de brandsene som velger å fjerne den offisielle støtten må vi bare ignorere for nå.
Eldre Androids støtter ikke emoji-standarden slik den er i dag, men støtter versjoner av unicode istedet. For versjoner av android som ikke støtter emoji-standarden faller vi tilbake til en tidlig versjon av unicode, som i emojistandarden blir emoji-versjon 0.7
se https://emojipedia.org/google/android-12.0/new/ for mer info.

### Implementasjon
caster emoji-versjon til float og sjekker om emoji-versjonen er mindre eller lik, dermed unngår vi at minor-versjoner ikke blir filtrert ut.
Støtter emojis tilbake til Android 8. før det er emojis et såre kaos så da faller vi tilbake til emoji version 0,7 som ser ut til å ha 100% støtte i hvert fall helt tilbake til Android API level 22 (Android 5)

### Testing
Jeg har testet på emulator helt tilbake til android 5 Lollipop

**Comment by tormoseng** [comment]
Denne er grei. Testet OK på Android 7.0 med mye bedre støtte enn tidligere.
