### ISSUE TITLE
[Feature] Kunne lagre bankkort og bruke dette ved senere kjøp

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1497]
## Motivation

Betaling med bankkort oppleves som tungvint når man må taste inn alle kortdetaljene hver gang. For å strømlinjeforme og effektivisere betaling med bankkort bør det være mulig å velge å lagre et bankkort slik at det enklere kan brukes til å betale med i senere kjøp.

Relatert til #1498 .
## Proposed solution
- Prototype - Har et lagret kort: https://www.figma.com/proto/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?page-id=884%3A25161&node-id=976%3A31244&viewport=313%2C48%2C0.34&scaling=min-zoom&starting-point-node-id=976%3A31244&show-proto-sidebar=1
- Prototype - Førstegangslagring: https://www.figma.com/proto/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?page-id=884%3A25161&node-id=976%3A30525&viewport=313%2C48%2C0.34&scaling=min-zoom&starting-point-node-id=976%3A30525&show-proto-sidebar=1
- Skisser: https://www.figma.com/file/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?node-id=884%3A25180

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by tormoseng** [comment]
@brorhb Ser at lagret betalingskort blir lagret med en måned feil på utløpstid. Innsetting "12/22" blir "11/22" (se video under). Testet det samme med "01/22" som blir "12/21".

https://user-images.githubusercontent.com/5812433/133981142-60dc2a99-697e-4d56-9fc4-cbd09848b4e4.mp4

**Comment by tormoseng** [comment]
@brorhb Hvis man har lagret 2 kort så går det fint å klikke på bakgrunn for å komme tilbake.

Hvis man har 3 kort så begynner det å bli vanskelig å klikke seg bort. Se bildet under

![241397863_179553417637222_2805386489798615306_n](https://user-images.githubusercontent.com/5812433/133981683-511b5656-8848-4727-a117-22c98f070de0.jpg)

Hvis man videre har 4 kort lagret så er det i hvertfall umulig å avbryte og komme seg bort

https://user-images.githubusercontent.com/5812433/133981763-ec8d725b-61ad-423a-823c-47b235b7ea5f.mp4

**Comment by tormoseng** [comment]
@brorhb Noen kommentarer rundt testing med skjermleser.

**Generelt**
- Det står "Betal med Visa/Mastercard", men kun "Vipps". Er dette med vilje?
- Ingen kortsymboler for Visa/Mastercard, kun for Vipps

**Uten innlogging**
- Med VoiceOver så leser valgmodul opp "Betal med ... - aktiver for å betale med ..." uavhengig av om denne allerede er valgt.
- Markering av en betalingsmåte gir ingen feedback på VoiceOver at denne er valgt.

**Med innlogging**
- Med VoiceOver: Aktivering av "Betal med Visa" leser opp alt inne i denne boksen i ett. Kunne kanskje med fordel lest opp kun "Betal med Visa" og heller lest opp "Lagre bankkortet ..." når denne blir markert
- Med VoiceOver så får jeg ikke markert lagre-kort-checkbox. Sveip til høyre og venstre veksler kun mellom betalingsmåtene og kommer ikke innom lagre-kort-checkbox.
- Med VoiceOver så får jeg ikke markert lagre-kort-checkbox. Ikke med enkelttrykk eller dobbelttrykk. Henger sammen med observasjon over?

**Comment by rosvik** [comment]
@brorhb @tormoseng Merget PR #1635 nå

**Comment by brorhb** [comment]
Støtter den, sjekken som skjer for å se om appen skal bruke lagret kort er på om den innloggede brukeren har et telefonnummer. Anonyme brukere bør jo ikke ha det (?) 🤷‍♂️ Ser på dato og Voiceover når jeg får tiden 😊 Tipper logikken må være noe i mellom det den var først, og det den er nå 😊
