### ISSUE TITLE
[BUG] Feil overskrift på forside når man kommer tilbake fra reisesøk

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1502]
**Describe the bug**

Etter man har gjort et reisesøk og går tilbake til forsiden, forandres overskriften ikke tilbake til "Reisesøk", men viser til/fra verdiene i søkefeltet. 

**Application version**
Version number: v1.11

**To Reproduce**
1. Gå til Reisesøk
2. Utfør et reisesøk
3. Scroll ned til headeren oppdateres med status på søk
4. Trykk på AtB-logo for å gå tilbake til startside
5. Observer at tittelen fortsatt viser (deler av) reisesøket.

**Expected behavior**

Tittelen bør forandres tilbake til "Reisesøk"

**Screenshots**

![IMG_5778](https://user-images.githubusercontent.com/1774972/130075701-c5feb18c-a8bb-4d8f-a2dd-36d7259d2291.PNG)

https://user-images.githubusercontent.com/1774972/130074574-613ea9f6-1a39-4e6c-ba64-57c6eae18ef9.MP4

**Comment by tormoseng** [comment]
Testet OK på iOS + Android i staging
