### ISSUE TITLE
[Feature] Reisesøk: Vise flere treff for ruter med få avganger

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#1548]
Hvis man søker etter reiser hvor det er få avganger / langt mellom avgangene så er det veldig få treff som kommer opp. Et eksempel er reisesøk mellom Prinsen og Korsvegen (Melhus). Søk etter avganger nå viser kun 2 treff kl.0900 (fredag). Den siste har avgang 12:08. Setter man opp avgang kl.12:00 eller 14:00 kommer det flere treff utover dagen.

Dette er en etterspurt feature på Intercom.

Her er det tydelig en trade-off mellom antallet avganger man mottar (typisk på bynære ruter) og informasjon man trenger for å planlegge (typisk på ruter med få avganger). Hvor langt fram skal man søke? Og kan nytt søk gjøres hvis det er få treff?

Mange reiseplanleggere har en mulighet til å trykke "Vis flere reiseforslag" under søket s.a listen kan utvides etter behov. 

For eksemplet Prinsen - Korsvegen så hadde det vært nyttig å vise at etter kl.18 så er neste buss søndag kl.16 (tenkt tilfelle) - eller en beskjed om ingen avganger denne dagen om det ikke finnes avganger når man har et reisesøk på lørdag fra Prinsen til Korsvegen.

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by tormoseng** [comment]
Diskusjonspunkter:
- Vis-flere-avganger-knapp: Hvordan bør man her sette vinduet frem i tid for søket? Dersom det er mange avganger bør man unngå å ha for stort vindu mtp belastning for søkemotoren, men dersom det er få avganger vil man ha et større søkevindu. Hvis man tilbyr "Vis flere avganger neste time" og "Vis alle avganger i dag", så vil man unngå at brukere på bynære ruter skal hente hele dagen pga belastningen.
- Finnes det noen parametre som kunne fortalt at en rute har få avganger s.a. man kunne brukt denne for å utvide vinduet?
- Med OTP2 så er det paginering. Hvordan bør man løse dette når det er få avganger? Først søk på 80 min -> ingen treff, så 160 min -> ingen treff, så 320 min -> ingen treff, beskjed til bruker.
- Beskjed til bruker. Blir viktig å formidle hva som returneres - og viktigere hva som ikke returneres. Hvis det ikke er avganger neste 4 timene, og dette er søkevinduet, så bør det formidles at man ikke fant noen avganger de neste 4 timene. Kanskje også med henvisning om at man selv da kan endre avgangstidspunktet.
- Viktig å huske at man ikke lager en løsning som vil være topp for kun 10% av brukerne og som pga dette vil påvirke resterende 90% negativt. Spesielt mtp belastning på søkemotorer om man spør etter for stort søkevindu, etc.

**Comment by tormoseng** [comment]
Relatert til #1552

**Comment by hildeor** [comment]
Lukker denne da den er løst
