### ISSUE TITLE
[Feature] Støtte utenlandske mobilnummer ved innlogging/registrering

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1559]
## Origin

Nå er +47 hardkodet inn som prefiks på mobilnummer ved innlogging/registrering. Man bør også støtte utenlandske mobilnummer, slik at brukere uten norsk mobilnummer kan opprette profil og kjøpe periodebillett i appen. 

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

- Det skal gå an å sende SMSer til utenlandske nummer. 
- Selv om Vipps kun støtter norske nummer, vil ikke det skape problemer i appen, siden man ikke oppgir mobilnummer når brukeren sendes til Vipps-appen på mobil.
- Nettbutikken har støtte for registrert med utenlandske nummer, også å bruke som innlogging. 

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

![Phone number](https://user-images.githubusercontent.com/8980523/133579808-aefcddf5-5a96-47f8-834e-937475b43fea.png)
![Country code](https://user-images.githubusercontent.com/8980523/133579816-6dae0bec-ecbc-4ad3-9618-094c0968e3d5.png)

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by tormoseng** [comment]
@rosvik Denne er testet OK med endring i #1619 .

En liten kommentar/spm: Hvis man taster inn feil engangskode så blir ikke feilmld lest opp med skjermleser før man markerer denne. Burde den blitt lest opp automatisk? Ble usikker på hvordan dette er løst ellers i appen.
