### ISSUE TITLE
Vis melding om "Ingen avstigning"

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1560]
### Observasjon
Enkelte trasseer gir ikke tilgang til avstigning på holdeplasser. 
Dette har vi i dataene, men vi viser det ikke.

### Implementasjon
Viser melding om ingen avstigning når forAlighting flagget er satt til false

### Testbeskrivelse
Finn en reise der holdeplasser ikke betjenes, f.eks Trondhein S -> Orkanger Skysstasjon
På denne reisen betjenes ikke holdeplassene mellom TRD S og Hårstaadkrysset.
Observer at det vises en melding på disse holdeplassene.
Observer at de er riktig oversatt

**Comment by tormoseng** [comment]
Testet OK i staging
