### ISSUE TITLE
[Feature] Legg inn info om sykkelbillett

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#1569]
Melding fra Julia som reaksjon på Intercomspørsmål om sykkel på buss:

Under pristabellen (Mitt AtB -> Billettkjøp) kan vi sette inn følgende:
- NOR: For å ha med sykkel kan du kjøpe barnebillett.
- ENG: To bring a bicycle, you can buy a child's ticket.

**Comment by monopoint** [comment]
Det står allerede info om sykkel i billettinfo, men det kan kanskje tydeliggjøres. I tillegg bør tekst om barnebillett oppdateres for å reflektere de ny aldersgrensene.

Forslag:

| Antall soner du reiser i | 1 | 2 | 3 | 4 |
|-------------------------------|----|---|---|---|
| Voksen | 40 | 80 | 120 | 120 |
| Barn (under 20år) / Honnør / Militær | 20 | 40 | 60 | 80 |

For å ha med sykkel, kan du kjøpe barnebillett

**Comment by monopoint** [comment]
@JuliaOppegard

**Comment by JuliaOppegard** [comment]
Beklager sent svar her, var syk i går.
For at pristabellen skal være gjenkjennelig overalt er det fint om vi bruker samme oppsett som vi gjør om bord, på holdeplasser og på atb.no.
Det betyr egentlig at det eneste tiltaket vi gjør er å fjerne "ungdom" fra tabellen vi hadde fra før slik at det i den ruta bare står "student". 
Høres det ok ut?

**Comment by monopoint** [comment]
Så det betyr at du vil ha sykkel i tabellen i tillegg til et ekstra punkt om sykkel under tabellen?

**Comment by JuliaOppegard** [comment]
Ja egentlig. Dette er jo en pristabell som sier noe om hva billetten koster, så sykkel koster 20, og siden vi ikke har sykkelbilletten enda informerer vi i tillegg om hvordan du kjøper billett for sykkel.

**Comment by monopoint** [comment]
venter på dokument fra @JuliaOppegard

**Comment by monopoint** [comment]
https://github.com/AtB-AS/mittatb-app/wiki/Billettinformasjon-i-appen

**Comment by monopoint** [comment]
siden dette tar litt tid, gjør jeg disse endringene nå:
- Fjerner "Ungdom" fra pristabellen
- Legger til spesifisering om sykkel under tabellen

**Comment by monopoint** [comment]
![image](https://user-images.githubusercontent.com/1464594/146933865-648a18e4-b107-4344-9b90-838aa3d5e43f.png)
![image](https://user-images.githubusercontent.com/1464594/146933973-8815a916-7957-4fa1-8847-a11e8d7fa4e8.png)

**Comment by monopoint** [comment]
venter på godkjenning fra Line.

**Comment by tormoseng** [comment]
Testet OK på iOS for staging-1642146947, men er borte igjen for nyeste staging (1642147932).

**Comment by tormoseng** [comment]
Siste staging-bygg er OK.
