### ISSUE TITLE
Vise melding når bruker prøver å logge inn, men har aktiv billett

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1597]
### Løsningsforslag

[Skisser](https://www.figma.com/file/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?node-id=1222%3A32554)

![Anonyme billetter ved innlogging](https://user-images.githubusercontent.com/8980523/134337840-abd362bf-c73d-497d-bfc4-1143abd17b78.png)

**Comment by magnusolderoesaether** [comment]
![image](https://user-images.githubusercontent.com/50573205/134857685-0213d48b-b9cd-42f7-9f20-afbd0107b20c.png)

**Comment by tormoseng** [comment]
Denne er testet OK i staging - også med VOI/iOS og TB/Android
