### ISSUE TITLE
[Feature] Gjøre det mulig å toggle mellom tokens (reisebevis) i app

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1621]
## Opprinnelse
Når mobil token introduseres trenger man en måte å angi hvilket token som skal være aktivt. Et token kan være t:kort eller mobiltelefon.

## Features

- https://github.com/AtB-AS/abt-tokens/pull/22
- https://github.com/AtB-AS/abt-swift-test/pull/123

## Motivation

En gitt billettkonto skal bare være tilgjengelig fra den mobilen som er registrert som et aktivt token på billettkontoen. Gjennom #1089 introduserte vi to ulike visninger av billetter avhengig av om mobilen er aktivt token eller ikke.

I denne saken gjør vi det mulig for kunden å velge at en ny mobiltelefon skal overta som aktivt token. Dette er for eksempel relevant ved bytte av en mobiltelefon.

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

[Prototype](https://www.figma.com/proto/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?page-id=617%3A17654&node-id=1072%3A31996&viewport=334%2C48%2C0.33&scaling=scale-down&starting-point-node-id=1072%3A31996&show-proto-sidebar=1)
[Skisser](https://www.figma.com/file/Fc2wnZtn96wJIY6j18xoNC/Components-2.0?node-id=1072%3A31996)

<img width="1392" alt="Skjermbilde 2021-09-15 kl  10 27 49" src="https://user-images.githubusercontent.com/8980523/133398470-af3ba049-660e-4bce-8fb0-52a9cd9993c7.png">

**Comment by tormoseng** [comment]
Denne er testet vel og bra. Ser ut til å fungere fint - også når man herjer med responsene.
