### ISSUE TITLE
[BUG]: Tilbake-trykk på android lukker appen istedet for å navigere

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1625]
## Observasjon
Hvis man på Android står inne på et søkeresultat og trykker tilbake så lukkes appen.
Forventet adferd er å nullstille søket og gå tilbake til startskjerm.

på iphone er det konvensjon å benytte knapp øverst til venstre i skjermen for å gå tilbake, og her ligger AtB-logoen som gjør akkurat det.
På android er konvensjonen at trykk på Tilbake navigerer tilbake, og vi burde legge inn støtte for at trykk Tilbake utører det samme som trykk på AtB-logo ved reisesøk.

## Analyse
Tilbake-navigasjon funker for andre skjermer, og grunnen til at den ikke funker her, selv om det virker som den burde, er fordi søkeresultatene ikke teknisk er en annen skjerm enn Startskjermen. Det må derfor legges på litt ekstra logikk for å håndtere det her.

## Implementasjon
Søkeresultater vises når vi har en "fra" og en "til" posisjon. Når disse verdiene blankes ut, fjerner vi resultatskjermen og går tilbake til fyrtårnet. Det er dette som skjer også når man trykker på logoen øverst til høyre.
Vi kan avbryte back action når screenHasFocus og "fra" og "til" er satt, og istede blanke ut "fra" og "til".

**Comment by tormoseng** [comment]
Testet OK
