### ISSUE TITLE
[BUG] Last used travel is saved per device, not per user

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1660]
**Describe the bug**
Hvis du lagrer et kort, og bruker det i kjøp, så blir det kortet satt til "sist brukt" og vises på knappen som default valg i kjøpsskjermbildet. Problemet er at det lagres per device, og ikke per bruker, som betyr at den "blir med" over når du logger inn/ut.

**Application version**
Version number: 1.11

**To Reproduce**
1. Logg inn med telefon
2. Lagre et kort
3. Kjøpe billett med lagret kort
4. Logg ut til anonym kontekst
5. Gå tilbake til kjøp, se at kortet er lagret som sist bruk tross annen konto

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4932625/137300051-6190c898-207e-4437-9d95-d4dc29469c9e.png)

**Smartphone (please complete the following information):**
 - Device: Alle
 - OS: Alle

**Comment by tormoseng** [comment]
@cbrevik Jeg får ikke til å gjenskape denne. Fortsatt gyldig?

**Comment by cbrevik** [comment]
Jepp denne fikset jeg selv, ikke gyldig nei!
