### ISSUE TITLE
[BUG] Tidligere søkeparametre henger igjen når man foretar nye reisesøk

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1779]
**Describe the bug**
Fra Intercom:

> Hei, opplever at søkefunksjonen henger seg opp i det jeg har søkt tidligere. Hvis jeg søker fra Strindheim - vikelvveien, så vil den plutselig søke fra Solsiden - Vikelvveien uten at jeg vil det.

Vi har også mottatt meldinger om personer som opplever at datoer i reisesøket reverter tilbake til et tidligere søk.

**Application version**
Version number: [e.g. 1.2.3]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tormoseng** [comment]
- Intercom 1: iPhone XR, iOS 14.8, App.versjon 1.12 (https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/all/conversations/159245400044965)
- Intercom 2: iPhone 11, iOS 14.8.1, App.versjon 1.12 (https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/all/conversations/159245400026432)
- Intercom 3: Samsung Note 8, Android 9, App.versjon 1.9 (https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/all/conversations/159245400044986)

**Comment by tormoseng** [comment]
Ikke klart å gjenskape denne. Lukker saken og har i mente denne om det dukker opp igjen. 

Mulig også #1876 hjelper her.
