### ISSUE TITLE
[BUG] Blir bedt om location kontinuerlig, selv om en takker nei på Android

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1792]
**Describe the bug**
https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400045004#part_id=initial-part-159245400045004-1074107922
https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400044285#part_id=initial-part-159245400044285-987147656

**Application version**
Version number: [e.g. 1.2.3]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brorhb** [comment]
Jeg vil tro at det har noe med dette å gjøre?

https://developer.android.com/training/location/permissions

**Comment by brorhb** [comment]
Sliter med Android generelt, så får ikke testet implementasjonen min

**Comment by tormoseng** [comment]
Har testet litt rundt med å ikke tillate posisjon, og ser i hvertfall ingen feil på hverken de fysiske eller BS devicene jeg har prøvd.

**Comment by brorhb** [comment]
Lukker denne inntil videre. En mulig fiks er lagt inn, så så lenge vi ikke får tilbake meldinger om annet, så lukker jeg den 😊
