### ISSUE TITLE
Høste feedback på OTP2 - Reisesøk

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1793]
## Origin

Vi ønsker å jobbe mer datadrevet og tett på brukerne, og det er derfor behov for å kunne få innsikt som er mer direkte relatert til ulike features. Tidligere har vi brukt Intercom til dette men det har sine begrensninger (kan ikke integreres i kontekst i appen) og Intercom er heller ikke et verktøy som skal brukes på lengre sikt. 
Vi ønsker derfor å få etablert et system som kan brukes jevnlig med tanke på innhøsting av innsikt direkte i kontekst sammen med features, slik at vi under et beta-stempel kan la brukerne toggle til beta-funksjonalitet og gi feedback på dette. I første omgang er det spesielt aktuelt med OTP2 og reisesøk, samt ny avgangervisning, men det er ønskelig at man kan gjenbruke denne løsningen for fremtidige features for å sikre kontinuerlig feedback.

## Motivation

Ved å gå over til OTP2 er det usikkerhet rundt kvalitet på reiseforslag og det er dermed ønskelig at vi innhenter mer strukturert feedback på dette. Erfaringsvis er det personer som melder fra om reiseforslag ikke gir mening og da via Intercom, men det blir mer opp til hver enkelt person hvor mye de deler i detalj og opp til oss å følge opp for å få tilstrekkelig mengde informasjon.
Ved å implementere en mer strukturert metode for å hente inn data så kan vi hente informasjon om det aktuelle reiseforslaget som det gis tilbakemelding om, og vi får forhåpentligvis hentet inn feedback fra flere fordi terskelen blir lavere for å gi feedback.

Se også https://github.com/AtB-AS/mittatb-app/issues/1794.

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

**Prototyper**

- [Fra reisesøk - eksisterende søk allerede lastet](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=6827%3A51207&node-id=6827%3A51763&viewport=369%2C48%2C0.46&scaling=min-zoom&starting-point-node-id=6827%3A51763&show-proto-sidebar=1) (vet ikke om denne noen gang slår til?)
- [Fra reisesøk - Fra tomt søk](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=6827%3A51207&node-id=6827%3A51690&viewport=369%2C48%2C0.46&scaling=min-zoom&starting-point-node-id=6827%3A51690&show-proto-sidebar=1)

### Skisser

Figma: https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6827%3A51690

Toggle fra Mitt AtB: 
![Logged in](https://user-images.githubusercontent.com/8980523/144040165-5845a002-7ea4-4013-9b08-a6f44a3c6db6.png)

![Skjermbilde 2021-11-30 kl  12 35 46](https://user-images.githubusercontent.com/8980523/144040349-3b63aa49-38f5-4985-b2b3-64359eaf7be2.png)
![Skjermbilde 2021-11-30 kl  12 36 20](https://user-images.githubusercontent.com/8980523/144040424-4940b085-71c5-4197-aee2-3fb290aa9069.png)

**Feedback-komponent:**
![Skjermbilde 2021-11-30 kl  12 37 57](https://user-images.githubusercontent.com/8980523/144040614-43bf618a-aec6-47f5-b57e-0274ee0e3a98.png)

### Foreslått ønsket output:
Vet ikke helt hvordan vi får presentert dette etter innhenting av data, men har følgende tanker om output:
- Telle antall tilbakemeldinger koblet til bra/dårlig
- Telle antall tilbakemeldinger med årsaker (dårlig)
- Sende med selve reiseforslaget med tilbakemeldingen

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by cbrevik** [comment]
#2016

**Comment by tormoseng** [comment]
Kommentar basert på hva Ruter har av tilbakemelding vedrørende reisesøk:
![270180046_1050377848873614_4760204448818484905_n](https://user-images.githubusercontent.com/5812433/149766044-955da77e-b869-4bba-aee5-ff3ecf1cf20b.jpg)

**Comment by toretefre** [comment]
Gjør et forsøk på promptene nå.

**Comment by toretefre** [comment]
Vi la denne på is til det blir et behov igjen, siden reisesøk v1 uansett fjernes for alle nå.
