### ISSUE TITLE
Høste feedback OTP2 - Avganger

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1794]
## Origin

Vi ønsker å jobbe mer datadrevet og tett på brukerne, og det er derfor behov for å kunne få innsikt som er mer direkte relatert til ulike features. Tidligere har vi brukt Intercom til dette men det har sine begrensninger (kan ikke integreres i kontekst i appen) og Intercom er heller ikke et verktøy som skal brukes på lengre sikt. 
Vi ønsker derfor å få etablert et system som kan brukes jevnlig med tanke på innhøsting av innsikt direkte i kontekst sammen med features, slik at vi under et beta-stempel kan la brukerne toggle til beta-funksjonalitet og gi feedback på dette. I første omgang er det spesielt aktuelt med OTP2 og reisesøk, samt ny avgangervisning, men det er ønskelig at man kan gjenbruke denne løsningen for fremtidige features for å sikre kontinuerlig feedback.

## Motivation

Vi ønsker å få større kvantitet på feedbacken på ny avgangervisning, slik at vi kan vurdere hvordan alternativ avgangervisning dekker brukerbehovene. I intercom er det endel som har meldt fra om problemer med dagens avgangervisning som viser avganger gruppert pr. linje, men det er likevel knyttet usikkerhet til hvordan ny visning dekker behovene. Vi har behov for en mer strukturert måte å få inn feedback på nye features på, og et slikt "rammeverk" kan også brukes på mer inkrementelle endringer for å høste innsikt på hvordan små forandringer kan påvirke tilfredshet eller brukervennlighet.

Se også https://github.com/AtB-AS/mittatb-app/issues/1793.

## Proposed solution
[Prototype](https://www.figma.com/proto/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?page-id=6827%3A51207&node-id=6870%3A62844&viewport=406%2C48%2C0.19&scaling=min-zoom&starting-point-node-id=6870%3A62413&show-proto-sidebar=1)

### Skisser

Figma: https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6870%3A62413

<img width="442" alt="Skjermbilde 2021-12-01 kl  14 12 44" src="https://user-images.githubusercontent.com/8980523/144240528-73734377-0ead-40fb-b7dd-762f17b3a0b6.png">

<img width="446" alt="Skjermbilde 2021-12-01 kl  14 13 02" src="https://user-images.githubusercontent.com/8980523/144240579-dac73dc4-1476-4d44-92fc-f8e564448cd8.png">

<img width="442" alt="Skjermbilde 2021-12-01 kl  14 16 09" src="https://user-images.githubusercontent.com/8980523/144241092-64973c78-8bb6-41eb-a327-b0306e752161.png">

<img width="433" alt="Skjermbilde 2021-12-01 kl  14 17 39" src="https://user-images.githubusercontent.com/8980523/144241281-37406422-a632-443f-81b1-c0bd10f7fe74.png">

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by cbrevik** [comment]
Avhengig av #2016

**Comment by strombraaten** [comment]
Har sendt ut meldinger til et begrensa segment på intercom for å høste innsikt om ny Avganger-visning inntil videre.

**Comment by toretefre** [comment]
Dette jobbes med i #2345
