### ISSUE TITLE
[Feature] Enable period tickets if there is a valid mobile token

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1797]
Mens mobiltoken testes, skal også periodebilletter være mulig å inspisere. Endringen i 7239f604620ba9cfa563217be9b5616b187d70ff må derfor ha en ekstra sjekk for om man har et aktivt token.

https://github.com/AtB-AS/leveranser/discussions/59

**Comment by tormoseng** [comment]
Ser bra ut i staging!
