### ISSUE TITLE
[Feature] Justere tidspunkt hvor vi viser indikator for nytt døgn

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1800]
## Origin

Vi ser at i noen case blir en 24timers grense for tvetydig i grensesnittet. I tilfellet under er avgangene "ca. 07:03" og "ca.07:43" også avganger den 24. november, men bare 08:03-avgangen vises med dato.

![IMG_4159](https://user-images.githubusercontent.com/8980523/142988015-d1694fd7-62a9-4500-94b5-aa51628acd66.PNG)

## Proposed solution

- [ ] Endre til å vise dato ved midnatt
- [ ] Vise forkortelse av ukedag i stedet for dato

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by brorhb** [comment]
Merged to master ❤️

**Comment by tormoseng** [comment]
Testet OK

**Comment by tormoseng** [comment]
Egen sak etter test med skjermleser er #1878
