### ISSUE TITLE
Reisedetaljer med JP3 - fase 1

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1848]
### Beskrivelse

- [x]  Aktivere navigasjon fra reiseforslag til reisedetaljer
- [x] Sørge for at queryet for reisesøk inneholder nødvendige data for reisedetaljer
- ~~Mapping til kart~~ flyttes til fase 2
- [x] Typewrangling, refaktorisering og tilpasninger slik at nye query-spesifikke typer fungerer med gjenbrukbare komponenter
- ~~entur har endret pagination (cursor istedet for timstamp), må oppdatere~~ flyttes til fase 2
- [x] oppdater designdetaljer iht til figma
  - [ ] spacing
  - [ ] "I dag" markeres som default 
- [ ] tydelig skille mellom m (meter) og min (minutter)

### Avklaringer
- Leg.notices er spesifisert i custom type-definisjoner (i motsetning til typedefinisjoiner i sdk), men .notices finnes ikke i sdk for jp2, eller graph-treet til jp3. Har dette aldri fungert?
- typer generert fra JP3 sier at Leg har felt av typen "Mode", men "Mode" er  merket med "not implemented". skal det egentlig være "TransportMode" her?
  - Mode er feilaktig merket "not implemented", og skal oppdateres av entur. "Mode" er et supersett av "TransportMode". Mode = TransportMode + StreetMode

**Comment by mikaelbr** [comment]
Relatert: https://github.com/AtB-AS/mittatb-app/issues/1955
