### ISSUE TITLE
[Feature] SCA-excemption for payment cards

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1858]
## Origin

- https://github.com/AtB-AS/team-platform/issues/17
- https://github.com/AtB-AS/atb-ticket/pull/104

## Motivation

Enklere betalingsflyt for brukere, bankid-krav for lagret betalingskort er ikke mye bedre enn Vipps.

## Hypotheses and assumptions

- Flere brukere får bankid krav hver gang de betaler med betalingskort
- En flyt uten bankid for lave beløp vil oppleves som mye raskere enn andre alternativer

## Proposed solution

Test kort: https://shop.nets.eu/nb/web/partners/test-cards

- Sende inn `sca_excemption: true` i reserve-kall
- Håndtere HTTP 409 og ErrorReason i `use-terminal-state`. Ikke redirect med en gang en får `responseCode` = `OK` fra NETS
- Redirect tilbake til terminal-URL igjen hvis en får soft decline

## Acceptance Criteria

- [] Du får BankId-krav på test-kort som gir "challenge"
- [] Du får ikke BankId-krav på test-kort som ikke gir "challenge"

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

Ser ut som kanskje disse gir challenge:
![image](https://user-images.githubusercontent.com/4932625/144842328-359d9b4a-49e4-4a48-a6c8-5a9641d53902.png)

**Comment by cbrevik** [comment]
Vi har landet på at vi må få hentet ut terminal-URLen på en mer robust måte, dette forutsetter at vi lander følgende PR:
https://github.com/AtB-AS/atb-ticket/pull/106

**Comment by tormoseng** [comment]
Denne er testet OK i staging
