### ISSUE TITLE
[BUG] Fjern mulighet for student ved 7-dagers

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#1883]
Så vidt jeg ser ligger det riktig i RemoteConfig, vet at produktet (PreassignedFareProducts) ikke har student-brukerprofilen (UserProfile) i sine `limitations`. Det mangler nok filtrering på disse limitations når man åpner TravellersSheet.

**Comment by tormoseng** [comment]
Testet OK i app og nettbutikk
