### ISSUE TITLE
Avganger: Ferdigstille fase 1

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1884]
Fase 1 av #1394 

https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6242%3A28888

Todo:

- [x] Flytte nearest-endepunktet (henting av holdeplasser i nærheten) til JP3
- [x] Henting av avganger for individuelle quays ~med pagination~
- [x] Sanntid - Holde avganger oppdaterte selv om det er lastet inn mange for en quay
- [ ] ~Link til turdetaljer~
- [x] Diverse små GUI tweaks

**Comment by rosvik** [comment]
# Testkjøring datatrafikk for realtime oppdateringer

Charles session [departures.chls.zip](https://github.com/AtB-AS/mittatb-app/files/7735903/departures.chls.zip)


Når det gjelder realtime oppdatering av avganger, er det jo "enklest" å bare holde _alle_ avganger oppdatert. Prøvde først det, og satt `limit` for realtime oppdateringer til 1000, siden det også er limit for antall avganger pr. quay. Jeg kjørte dette i 10 min, som er tiden mellom hver "full reset". 

Det ble lastet inn 301 avganger for prinsens gate mellom 14:34 og midnatt. For fulle 24 timer ser det ut til å være rundt 400. 

## Datatraffikk mellom device og BFF

![Screenshot 2021-12-17 at 15 17 56](https://user-images.githubusercontent.com/1774972/146557830-31888c64-bce4-456c-a3ed-c99669d53416.png)

Det blir gjort 60 requests på 10 min, (10 min med 10 sek mellom hver request), på den tiden blir det overført 36kb med data. 

- Største og første kall er på rundt 5kb, og laster oppdatert data for 412 avganger (inkludert noen fra neste dag, som ikke ligger i listen orginalt).
- Nest størst er på 1,46kb, oppdateringer for 58 avganger.

Totalt brukes det 85kb på 10 minutter.

![Screenshot 2021-12-17 at 15 15 11](https://user-images.githubusercontent.com/1774972/146559679-7770a7f5-df0d-4278-8fd1-a94202ec15a0.png)

## Datatrafikk mellom BFF og journey planner

![Screenshot 2021-12-17 at 15 32 14](https://user-images.githubusercontent.com/1774972/146559851-2eb2193d-7799-4482-a8c4-ad3ddfd4fcf9.png)

Charles monitorerer ikke trafikk fra BFFen, men activity monitor viser 196kb utgående og 709kb inn i løpet av de 10 minuttene fra bff-prosessen i macOS.


# Opptak:

https://www.youtube.com/watch?v=IBJAGCyAWnc

**Comment by tormoseng** [comment]
Denne er god per nå. Testing og evt observasjoner noteres fortløpende i nye saker.
