### ISSUE TITLE
[BUG] Bytte rekkefølge på favorittsteder feiler - Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#1909]
**Describe the bug**
En bruker på Intercom sier at appen kræsjer hver gang hen ønsker å bytte rekkefølge på steder lagret i favoritter.

Lenke til Bugsnag: https://app.bugsnag.com/atb-as/mittatb/errors/6180f7a755dfc5000720a862?event_id=61bfc9df008aa5cb95d10000&i=sk&m=oc

Lenke til Intercom: https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/unassigned/conversations/159245400045226

Fikk gjenskapt denne på egen Samsung Note 10 med Android 11.0 + iPhone 12 mini med iOS 15.

**Application version**
1.13

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Lite
 - OS: Android 9.0

**Comment by brorhb** [comment]
_Notat_

Okay, har funnet ut hva som skjer. Når du flytter på noe i listen, så manipuleres den på en sånn måte at det blir lagt til en ekstra index i listen. Som fører til at listen vil rendrere et element som ikke finnes i listen over favoritter, som igjen fører til krasjen.

**Comment by tormoseng** [comment]
**Har testet på Android 11**

Denne er ok
Version 1.13 (1637745721)
Nov 24, 2021 at 10:46

Denne er IKKE ok (som er påfølgende)
Version 1.13 (1637843833)
Nov 25, 2021 at 13:55

**For iOS 15**

- feiler på 1.12 (1636017223) fra 04.11
- feiler på 1.11 (1634286981) fra 15.10

(Får ikke installert mye eldre versjoner enn dette)

**Comment by brorhb** [comment]
Nå har jeg jobbet endel med å kartlegge... Tor fant ut at feilen sannsynligvis oppsto i midten av november. Etter å ha skummet og sammenlignet kode mellom tags som starter med v1.12 -> v1.13 har jeg funnet et punkt hvor feilen ser ut til å manifestere seg.

Ved å bygge prosjektet fra tag v1.13-rc3 så kan man sortere favoritter. I tag v1.13-rc4 så slutter funksjonaliteten å fungere.

I komponenten

**Comment by monopoint** [comment]
sorteringskomponenten er overaskende kompleks. i tillegg ser det ut som det er en copy/paste fra et 3.parts github-prosjekt, og komponenten er implementert med gamle react lifecycle-metoder, og trenger sårt å oppdateres også pga av det. 
Vi har hatt en rekke problemer med den.
Siden denne kræsjer i produksjon nå, så har teamet blitt enig om å fjerne komponenten, og istedet bruke fallback-komponenten som vi bruker hvis skjermleser er aktivert, som benytter sortering med piler istedet for drag and drop

**Comment by tormoseng** [comment]
Testet OK i staging på iOS + Android.
