### ISSUE TITLE
[Ticketing] Add ticketing screen

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#192]
Related: #216

## Description

Add screen and navigation point for ticketing window as per #216.

Relevant tasks: #191

## Example

![image](https://user-images.githubusercontent.com/606374/79836387-5e6e6f80-83b0-11ea-81dd-7a20fb8dacfa.png)

## Acceptance criteria

- [ ] Able to open ticketing screen from tab bar.
- [ ] Tab bar button only available on `staging` and `development`

**Comment by gorandalum** [comment]
Done
