### ISSUE TITLE
[Ticketing] Add ticketing receipt in Ticketing screen

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#193]
Related: #216 

## Description

If we have an active valid ticket, show the receipt with active paper QR code for validation. See relevant screenshot and prototype for content.

Tickets should be minified by default but expanded on click.

Active valid tickets are found by passing in customer identification, which should be set from device id.

## Example

![Screenshot 2020-07-07 at 12 33 48](https://user-images.githubusercontent.com/56530785/86768630-2a6d2700-c04e-11ea-96c1-ca803ec16616.png)

## Technical design 
![image](https://user-images.githubusercontent.com/34686997/79840869-d0e24e00-83b6-11ea-8717-69de609ab35c.png)

## Acceptance criteria

- [ ] If no valid tickets, don't show any receipt
- [ ] If a valid ticket is found, show the receipt
- [ ] If multiple valid tickets are found, show the one that will expire first on the top.
- [ ] Should be able to toggle expand details on ticket.
- [ ] Should be able to toggle expand details on tickets independent on each other (not closing others when opening one)

**Comment by gorandalum** [comment]
Done
