### ISSUE TITLE
Brukertest: billettkjøp 2.0

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1932]
Brukertest av billettkjøp 2.0 (#1726 ). Testen kjøres på denne [Figma-prototypen](https://www.figma.com/proto/itxLyuV8s3U53qKG8K2q7n/Brukertest-billettkj%C3%B8p-2.0?page-id=0%3A1&node-id=1%3A51&viewport=406%2C48%2C0.54&scaling=scale-down&starting-point-node-id=1%3A51&show-proto-sidebar=1).

- [x] Finne dato 
- [x] Rekruttere deltagere
- [x]  Lage testscript
- [x]  Fordele oppgaver
- [x]  Lage prototype
- [x]  Generalprøve
- [x]  Gjennomføring
- [x]  Oppsummering

**Comment by strombraaten** [comment]
Oppdaterte beskrivelsesteksten med å linke til prototypen i Figma @cbrevik ✅

**Comment by strombraaten** [comment]
Brukertesten blei gjennomført på [denne Miro-tavla](https://miro.com/app/board/uXjVOWkpJ6o=/?invite_link_id=792774809549).

[Oppsummert i blogginnlegg](https://beta.atb.no/blogg/tester-nytt-billettkjop) på beta-bloggen.

Lukker denne issuen som siden vi nå har tatt stilling til tilbakemeldingene, og skapt oppgaver ut fra det.
