### ISSUE TITLE
Kart på detaljevisning av avganger for JP3

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1944]
Lage endepunkt for JP3 kartvisning på BFF
skru over endepunkter i app

- [x] PR app:  https://github.com/AtB-AS/mittatb-app/pull/2362
- [x] PR BFF: https://github.com/AtB-AS/atb-bff/pull/130
- [x] Bygg API-gateway i staging
- [x] håndtere at toQuay er optional for departure details: https://github.com/AtB-AS/atb-bff/pull/131

**Comment by tormoseng** [comment]
Denne er testet OK!
