### ISSUE TITLE
Avganger: Gjøre klar til release av fase 1

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1946]
Et par siste forandringer for å få avganger klar til en første release som brukere kan toggle på i produksjon

- [x] #1943 
	  - UU 
	  - Noe refaktorering 
	  - Beskrivelsetekst øverst i listen over stopp, f.eks. "Holdeplasser nær Prinsens Gate"
	  - Skrur av funksjon med autonavigering hvis søk er et stoppested til vi får sett på å fikse den
- [ ] #1957
- [x] #1979

### For å gjøre tilgjengelig for brukere
- [x] #1958 

### Neste steg
- Refaktorere state (Gjøres til egen issue)

https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6827%3A51238

**Comment by tormoseng** [comment]
Denne kan gå videre nå. Testet OK. Observasjoner er lagt til egne saker.

#1957 tas senere og testes separat
