### ISSUE TITLE
[Ticketing] Add link to Nets/payment for ticketing and show payment in Webview

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#195]
Related: #216 

## Description

When opening the Ticketing screen we should have the option to buy a new ticket. For the initial pilot this is a single ticket for an adult in Zone A, without any user input but hardcoded in the service layer.

But we need to handle the Nets URL returned by the service layer, showing the Nets interface in a WebView, handle the callback from Nets, and sending final confirmation.

Discussion points:
- Possible for the final confirmation to be part of domain services?
- User-id must exist. Can be handled on domain service given device id?

## Technical design
![image](https://user-images.githubusercontent.com/34686997/79840342-12bec480-83b6-11ea-8e88-50939e8761bc.png)

## Acceptance criteria

- [ ] A web view is opened with the Nets interface
- [ ] The callback from the WebView is handled by the interface
- [ ] After purchasing the ticket, an active valid ticket is visible on the ticketing screen.

**Comment by gorandalum** [comment]
Done
