### ISSUE TITLE
Alltid vise hvilken dag et reiseforslag gjelder for

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1955]
## Origin

Tilbakemelding fra Kundesenteret: 

> Nytt system medfører nye muligheter og mye å sette seg inn i. Våre kundegrupper varierer i alder og det er et stort sprik mellom hvor vidt de er i stand til å sette seg inn i alt det tekniske.
> Rundt førjulstid og romjula har vi hatt flere innringere på kundesenteret som har vært fortvilet over Appen. Da rutetilbudet var betydelig redusert, var det ekstra frustrerende og ikke kunne rekke den bussen de hadde planlagt å reise med.
> Flere av våre kunder har meldt inn at rutetidene for høytids – og helligdagene ikke har stemt med det de har fått opp på appens reiseplanlegger. Etter å ha undersøkt dette nærmere har jeg funnet ut at appen skreddersyr en reise for deg etter best mulig evne, og noen ganger er det ikke alltid dagens dato den foreslår. Man må altså trykke inn på reisen for å få tilstrekkelig med oversikt. Kundene våre savner at den nye appen opererer på samme måte som den tidligere reiseplanleggerappen. I den gamle sto det helt tydelig dato for avreise uten at man måtte trykke seg inn på selve reisen som er foreslått. Mange av våre kunder tar det altså for gitt at det er dagens dato bare av å se på det første forslaget som dukker opp.

## Proposed solution

- [ ] "I dag" vises alltid for reiseforslag i inneværende døgn
- [ ] "I morgen - 11. januar" vises alltid for reiseforslag innenfor neste døgn
- [ ] "12. januar" vises alltid for resterende påfølgende dager frem i tid som ikke er i dag eller i morgen
- [ ] Avstanden mellom overskriftene skal være større til elementene over enn under. I skissene er det brukt 12px avstand under og 24px avstand over. Dette sørger for at det blir tydeligere gruppering og at det blir lettere å få øye på overskriftene.

Skisse: 
![Visning av dag - Reisesøk](https://user-images.githubusercontent.com/8980523/148734638-40d88418-7c7c-4d63-ae21-010646d73b89.png)

## Implementasjon
Fant en bug, der disse overskriftene ikke var oversatt: overskriftene vistes alltid på norsk.
Løsningen har fra før også egen label for "i overimorgen" som jeg viderefører

- [x] Laget oversettelser
- [x] skrev om OptionalNextDayLabel til å bruke oversettelser
- [x] refaktoriserte OprionalNextDayLabel til DayLabel og refaktoriserte for å unngå rotete overlevering av hook-verdier
- [x] Gjorde slik at endringen gjelder for Reisesøk v1 og v2
- [x] Fikset avstander

**Comment by monopoint** [comment]
Her er det også en språk bug, for dette vises kun på norsk

**Comment by tormoseng** [comment]
Denne er OK.
