### ISSUE TITLE
Avganger / Reisesøk: innhøsting av data rundt bruk

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#1957]
- [x] Google Analytics
- [x] Intercom?

**Comment by rosvik** [comment]
## Testing av denne:

- Google Analytics data dukker opp i firebase under Analytics -> Events -> toggle_beta_departures / toggle_beta_tripsearch. 

- Intercom data vil dukke opp i attributtene for en bruker, som f.eks. [her](https://app.intercom.com/a/apps/xcvep5se/inbox/inbox/5163675/conversations/159542700000718). "AtB-Beta-TripSearch" og "AtB-Beta-Departures". Før det er i testflight, vil samtaler dukke opp i AtB [TEST] innboksen.

**Comment by tormoseng** [comment]
@rosvik Ser ikke ut til at jeg får til å øke event count ved å enable/disable i staging. Mulig jeg ser på feil view? [Lenke](https://console.firebase.google.com/u/0/project/atb-mobility-platform-staging/analytics/app/android:no.mittatb.debug/events/~2Foverview%3Ft%3D1644573351730&fpn%3D939812594010&swu%3D1&sgu%3D1&sus%3Dupgraded&params%3D_r..layout.pageNumber%253D0%2526_u..pageSize%253D25%2526_u.dateOption%253Dtoday&cs%3Dapp.m.events.overview&g%3D1).

**Comment by tormoseng** [comment]
Oppdatering: Nå ser det ut til at eventene har blitt registrert. Sikkert bare litt lag der - som ikke har noe å si :-)

**Comment by rosvik** [comment]
@tormoseng Oversikten på siden du sendte tror jeg tar en del tid før oppdaterer seg, men hvis man går inn på en av eventene, og så filtrerer på parameter "toggle" så viser det 8 av/på den siste halvtimen. (beklager dårlig testinstruks)

![Screenshot 2022-02-11 at 11 03 56](https://user-images.githubusercontent.com/1774972/153572451-34afc9a1-00a3-473f-b9cb-25d5c87664ad.png)

https://console.firebase.google.com/u/0/project/atb-mobility-platform-staging/analytics/app/android:no.mittatb.debug/events/~2Foverview%3Ft%3D1644573771154&fpn%3D939812594010&swu%3D1&sgu%3D1&sus%3Dupgraded&params%3D_r..layout.pageNumber%253D0%2526_u..pageSize%253D25&cs%3Dapp.m.events.overview&g%3D1

**Comment by tormoseng** [comment]
Neida, no worries. Fant den du henviste til, men heller ikke den oppdaterte seg kjapt nok for min utålmodighet. Kom nå etter noen min 👍

**Comment by tormoseng** [comment]
Da er denne testet OK
