### ISSUE TITLE
Toggling av beta-funksjoner

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1958]
Mulighet for brukere å toggle beta-funksjoner fra "Mitt AtB" fanen som vist i skisse.

![Screenshot 2022-01-05 at 13 12 50](https://user-images.githubusercontent.com/1774972/148215858-0fde1395-ee57-4860-b54d-f545611304da.png)

**Comment by tormoseng** [comment]
Denne er gull
