### ISSUE TITLE
Sette opp Mapbox for NFK

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#1961]
## Motivation

NFK vil ha Mapbox

## Proposed solution

Vil fungere med opprettet lisens og API-keys som må konfigureres.

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by mikaelbr** [comment]
Må undersøke om vi kan bruke felles tjeneste eller sette opp egen. Lisensspørsmål++
