### ISSUE TITLE
[BUG] Minutt forkortes som "m" isteder for "min" på engelsk

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1964]
`getShortHumanizer` funksjonen forkorter f.eks. 3 minutter som "3 min" på norsk, men "3 m" på engelsk. På engelsk leser VoiceOver "3 m" som "3 meters", så det bør oppdateres til å være "3 min" for begge språk.

**Comment by tormoseng** [comment]
@rosvik Ser og høres bra ut på iPhone, men på Android leses kommende avganger / next departure opp som f.ex "to min" / "two min" og ikke som "to minutter" / "two minutes".

**Comment by tormoseng** [comment]
@rosvik a11y-fix fungerer fint både på iOS og Android i Avganger v2, men ikke på Android for Avganger v1.

**Comment by tormoseng** [comment]
Lar denne gå siden det er v1 og iOS fungerer - som er det vanlige valget slik jeg har forstått for de som benytter skjermleser.
