### ISSUE TITLE
Konfigurerbare tekster i app for NFK

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#1967]
## Origin

AtB sine tekster fungerer ikke alltid for NFK

## Proposed solution

`Tickets.ts` og `Information.ts`
inneholder informasjon om billetter som må bli tatt med NFK.

Oppdatere alle infosider under "Info og priser"

Endre onboarding tekst som referer til chat i appen for tilbakemelding til NFK spesifikt

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

blocked: venter på tekster fra NFK

**Comment by tormoseng** [comment]
OK for AtB
