### ISSUE TITLE
Konfigurerbar lenke til personvernserklæring

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#1974]
Må kunne lenkes til OOS-parter sine personvernserklæringer.

**Comment by toretefre** [comment]
Dette er foreløpig satt opp med .env-filer i appen slik det er nå. Bedre med remote config, @mortlun ?

**Comment by mortlun** [comment]
Kan testes ved å sette _privacy_policy_url_ i firebase remote config til annen lenke og se at et endres. 
Det kan ta tid før cache av remote config blir invalidert - man kan sette `await  remoteConfig().fetch(0);` i koden for å slippe å vente på det.

**Comment by tormoseng** [comment]
Testet ved å sette en annen verdi for privacy_policy_url i Remote Config + fjerne denne for å vise defaults.
