### ISSUE TITLE
Endre t:kort-illustrasjon under aktive billetter for OOS

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#1976]
Under aktive billetter finnes det en t:kort-illustrasjon. Her trengs det nok en mer generell reisekort-illustrasjon når appen brukes i OOS-sammenheng.

**Comment by mikaelbr** [comment]
Avhengig av #2080 for å logge inn og se billetter på NFK miljø.

**Comment by mikaelbr** [comment]
Dette er faktisk ikke et bilde men språkendring. Så det må dekkes av #2028.

Se https://github.com/AtB-AS/mittatb-app/pull/2028#issuecomment-1026714082
