### ISSUE TITLE
[BUG] Tilbakeknapp har feil oppførsel etter toggling av beta-funksjon

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#1979]
Når man navigerer fra instillinger til avganger etter beta toggle, fungerer ikke tilbake-knappen slik den skal, og sender til Innstillinger istedet for startskjerm for avganger. 

https://user-images.githubusercontent.com/1774972/148955365-56e58a02-506b-47a0-a1e2-a75bd28611ee.mp4

**Comment by tormoseng** [comment]
Testet OK på iOS og Android
