### ISSUE TITLE
Sikre at paginated results ikke viser duplikater

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1981]
Reisesøk med timestamp-pagination er implementert slik at det i praksis gjøres et nytt søk med de samme parameter, bortsett fra at start-tidspunkt er endret.
Det medfører at entur vil kunne foreslå rene gå-strekninger ved hver page.

Denne fiksen er lettere å fikse når vi går over til cursor-basert pagination, fordi da vet vi når et søk ikke er side 1.
Det kan hende at entur selv har skjønt at gå-strekninger bare trenger  å returneres 1 gang ved cursor-søk, men det vet vi ikke. Så det kan være lurt å få gjenskapt situasjonen med duplikate gåstrekninger først, og så se om det blir bedre ved cursor-pages. Hvis ikke må resultater som ikke har Legs med serviceJourneyIds filtreres bort på BFF.

**Comment by tormoseng** [comment]
Situasjonen med duplikate gåstrekninger er dokumentert i duplikat sak #1994

**Comment by cbrevik** [comment]
Re-åpne hvis cursor i #1963 ikke løser denne
