### ISSUE TITLE
Legge til ikon for t-bane

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1982]
## Origin

I dag viser vi en rekke ulike transportmidler representert ved ikoner. Disse ikonene er en del 
Hvis man leter opp avganger eller får opp reiseforslag som inneholder t-bane vil man nå få opp buss-ikon, og ikke et spesifikt ikon som representerer t-bane.

## Proposed solution

- [ ] Legge til t-baneikon som brukes i både reisesøk og avganger. I fremtiden er det også tenkelig at det vil bli brukt i billettkontekst (visning av billetter fra andre selskaper).

Ikonet brukes i hvit med lilla bakgrunn (likt som for andre tog):
<img width="551" alt="Skjermbilde 2022-01-12 kl  12 29 56" src="https://user-images.githubusercontent.com/8980523/149132234-834ec807-25ef-4fbb-9bcb-90cd831ea0c3.png">

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by tormoseng** [comment]
OK!
