### ISSUE TITLE
bug: kan ikke søke mer, hvis ingen treff - mangler space i feilmeldinger

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1988]
## Observasjon
hvis man starter et søk på et tidspunkt der det ikke går busser i grisgrente strøk, kan man risikere at man ikke får noen treff på første søk. Da vises heller ikke knappen for å laste inne flere

@gorandalum har dialog med Entur på denne, de skal implementere slik at søkevinduet blir forstørret hvis de ikke treffer i initielt søkevindu

Estimat: 3 timer

**Comment by monopoint** [comment]
entur har økt sitt søkevindu, og det er nå rimelig vanskelig å finne en strekning som ikke gir reiseforslag.
Finner likevel en slik strekning, fra hammerfest til Øvre Ramse, Amli, sen på fredag kveld.

Entur finner ingen resultater, men knapp for å hente flere fungerer nå (selv om det ikke går an å komme seg fra A til B her)

meldingen om at vi ikke finner treff mangler litt spacing i topp, og etter litt undersøkelse så mangler det også for feilmeldinger. 

har lagt på litt space.

![image](https://user-images.githubusercontent.com/1464594/151762237-921f6bf1-a03a-4fbd-b2a6-834f370e9839.png)

**Comment by tormoseng** [comment]
@monopoint En ting her. Bruker jeg søket over og setter avgang 4.februar 22:00 så gir det ingen treff. Mange videre trykk på last flere gir heller ingen resultater. Men setter jeg avgang til 5.februar 01:00 så finner den treff på "1.forsøk" med første avgang 6.februar 10:21. Hvorfor vil ikke "vis flere" gi dette resultatet? 

En observasjon 
- gjennom proxy ser jeg de 5 kallene som går for å finne første treff. Alle disse oppgir samme søketidspunkt: "when": "2022-02-04T21:00:00.000Z". Ingen endring her i tidspunkt fra kall til kall. Og ingen bruk av paging
- trykk på "last flere" sender også med det samme tidspunktet: "when": "2022-02-04T21:00:00.000Z" og ingen bruk av paging
- Responsen fra BFF gir 

`{
	"trip": {
		"__typename": "Trip",
		"nextPageCursor": null,
		"previousPageCursor": null,
		"metadata": null,
		"tripPatterns": []
	}
}`

**Comment by monopoint** [comment]
Wat

**Comment by monopoint** [comment]
Merkelig. Jeg har sendt forspørsel til entur.
Her er 2 identiske søk, der eneste forskjellen er at dateTime er et døgn imellom:
https://api.entur.io/graphql-explorer/journey-planner-v3?query=%7B%0A%20%20trip%28%0A%20%20%20%20dateTime%3A%20%222022-02-04T20%3A00%3A50.527Z%22%2C%0A%20%20%20%20from%3A%20%7B%0A%20%20%20%20%20%20name%3A%20%22Fors%C3%B8lbukta%22%0A%20%20%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20%20%20latitude%3A%2070.719538%0A%20%20%20%20%20%20%20%20longitude%3A%2023.796073%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20to%3A%20%7B%0A%20%20%20%20%20%20name%3A%20%22%C3%98vre%20Ramse%22%0A%20%20%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20%20%20latitude%3A%2058.79112759215357%0A%20%20%20%20%20%20%20%20longitude%3A%208.207479572578649%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20arriveBy%3A%20false%0A%20%20%29%20%7B%0A%20%20%20%20tripPatterns%20%7B%0A%20%20%20%20%20%20expectedStartTime%0A%20%20%20%20%20%20duration%0A%20%20%20%20%20%20walkDistance%0A%20%20%20%20%20%20legs%20%7B%0A%20%20%20%20%20%20%20%20mode%0A%20%20%20%20%20%20%20%20distance%0A%20%20%20%20%20%20%20%20line%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20systemNotices%20%7B%0A%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20tag%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20metadata%20%7B%0A%20%20%20%20%20%20nextDateTime%0A%20%20%20%20%20%20prevDateTime%0A%20%20%20%20%20%20searchWindowUsed%0A%20%20%20%20%7D%0A%20%20%20%20nextPageCursor%0A%20%20%20%20previousPageCursor%0A%20%20%20%20routingErrors%20%7B%0A%20%20%20%20%20%20code%0A%20%20%20%20%20%20description%0A%20%20%20%20%20%20inputField%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A

vs

https://api.entur.io/graphql-explorer/journey-planner-v3?query=%7B%0A%20%20trip%28%0A%20%20%20%20dateTime%3A%20%222022-02-05T20%3A00%3A50.527Z%22%2C%0A%20%20%20%20from%3A%20%7B%0A%20%20%20%20%20%20name%3A%20%22Fors%C3%B8lbukta%22%0A%20%20%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20%20%20latitude%3A%2070.719538%0A%20%20%20%20%20%20%20%20longitude%3A%2023.796073%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20to%3A%20%7B%0A%20%20%20%20%20%20name%3A%20%22%C3%98vre%20Ramse%22%0A%20%20%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20%20%20latitude%3A%2058.79112759215357%0A%20%20%20%20%20%20%20%20longitude%3A%208.207479572578649%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20arriveBy%3A%20false%0A%20%20%29%20%7B%0A%20%20%20%20tripPatterns%20%7B%0A%20%20%20%20%20%20expectedStartTime%0A%20%20%20%20%20%20duration%0A%20%20%20%20%20%20walkDistance%0A%20%20%20%20%20%20legs%20%7B%0A%20%20%20%20%20%20%20%20mode%0A%20%20%20%20%20%20%20%20distance%0A%20%20%20%20%20%20%20%20line%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20systemNotices%20%7B%0A%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20tag%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20metadata%20%7B%0A%20%20%20%20%20%20nextDateTime%0A%20%20%20%20%20%20prevDateTime%0A%20%20%20%20%20%20searchWindowUsed%0A%20%20%20%20%7D%0A%20%20%20%20nextPageCursor%0A%20%20%20%20previousPageCursor%0A%20%20%20%20routingErrors%20%7B%0A%20%20%20%20%20%20code%0A%20%20%20%20%20%20description%0A%20%20%20%20%20%20inputField%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A

Det første gir bare en feilmelding, den andre gir nesten samme feilmelding, men med pageCursor.

**Comment by tormoseng** [comment]
Observasjon fra test håndteres i #2103
