### ISSUE TITLE
Vis linjenummer sammen med transportmiddel-ikon i reiseforslag

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#1990]
## Motivation
Etter nedkorting av informasjon på reisesøk er det behov for å øke lesbarheten mellom de ulike delene av reisen. Linjenummer bør derfor vises i samme boks som ikon for transportmiddel for at det visuelle hierarkiet skal bli riktig.

## Proposed solution
<img width="713" alt="Skjermbilde 2022-01-13 kl  10 50 05" src="https://user-images.githubusercontent.com/8980523/149306712-6ae15433-f1b9-4d4d-882d-67d708bdb097.png">

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by hildeor** [comment]
@monopoint Kan du verifisere at vi har matchet riktig skriftfarge på de ulike transmortmiddel-fargene? Jeg catchet i demoen at det hadde sneket seg inn sort skrift på selve linjenummeret på regionbusser, mens denne må være hvit for å tilfredsstille WCAG.
<img width="475" alt="Skjermbilde 2022-01-17 kl  13 28 21" src="https://user-images.githubusercontent.com/8980523/149769939-28e29c86-eac1-4a18-a943-1cca97597262.png">

Kombinasjoner fins her: https://www.figma.com/file/3rlcixpbhfBglNSctUkMys/Theme-1.0?node-id=1172%3A5844

**Comment by tormoseng** [comment]
@monopoint Se kommentar til @hildeor over. I appen nå så er fortsatt rutebuss-nr svart i light mode. Lurer også på hvorfor bybuss-nr er hvit, mens symbol er svart i dark mode + at tog-nr er svart mens symbol er hvitt i light mode (den svarte skrifta er lite synlig). Se skjermbilder.

![271539833_355791182651724_8416176507907663854_n](https://user-images.githubusercontent.com/5812433/150093320-de0f686a-9b27-4177-a0bf-805077df816e.jpg)

![271539813_441474650796669_2732265086225770450_n](https://user-images.githubusercontent.com/5812433/150093354-11e30b01-8158-4420-ab71-127da8c61ae7.jpg)

**Comment by hildeor** [comment]
@monopoint Her er de riktige mappingene i både light og dark mode. Altså ingen forskjell men det må være riktig mapping mellom hvilke farger som skal ha sort tekst og hvilke som skal ha hvit:

<img width="1063" alt="Skjermbilde 2022-01-19 kl  10 26 28" src="https://user-images.githubusercontent.com/8980523/150102056-c4843d7e-67fb-4c4f-b143-34e27802fdb0.png">

**Comment by gorandalum** [comment]
Fargene skal bli fikset av denne: https://github.com/AtB-AS/mittatb-app/pull/2036
Merget nå

**Comment by strombraaten** [comment]
Nå er jeg i v1.14, og ser at linjenumrene ikke står sammen med ikonet i den farga boksen. Er det en "fix in the making" i nærmeste framtid her, eller noe som bør følges opp på? 
![IMG_2935](https://user-images.githubusercontent.com/72508979/150766510-7bd61dde-7e1f-4964-98ea-6a0c72648956.PNG)

Ser at du lukka denne i forrige uke, @gorandalum , så kanskje du veit noe om saken?

**Comment by tormoseng** [comment]
@strombraaten Ser ut som om du er på reisesøk v1 (dagens reisesøk). Gå til Mitt AtB og toggle på nytt reisesøk.

Testet OK her:

![271598771_616015339694097_4591148660860033369_n](https://user-images.githubusercontent.com/5812433/150783190-b82de522-3abc-439a-8710-8e2417f96ed3.jpg)

**Comment by strombraaten** [comment]
Se det! Så flott 👏 Takk for at du sjekka @tormoseng
