### ISSUE TITLE
vise bussrutenummer inne i bobla på reiseforslag

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#1991]
<img width="708" alt="Skjermbilde 2022-01-13 kl  10 44 06" src="https://user-images.githubusercontent.com/1464594/149308782-a7ff90f6-7947-4941-bf66-2b86410a53bb.png">

**Comment by hildeor** [comment]
Duplikat av #1990

**Comment by tormoseng** [comment]
Testes i #1990
