### ISSUE TITLE
Identisk reise skal ikke vises ved å be om flere reiseforslag

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#1994]
Søkte reisesøk v2 etter reise ned fra mitt hjem (sted) til Melhus skysstasjon (bussholdeplass). Da får alternativet om å gå hele strekningen. Skjønner på en måte at å gå hele veien er en mulighet når man tenker dør-til-dør, men er det riktig å vise det? Vil jo alltid være mulig å gå.

Men når jeg laster flere forslag og da igjen får muligheten til å gå på et senere tidspunkt gir det liten mening..

Hvorvidt en ren gå-rute skal komme opp vil nok bero på hvor lang denne turen er. Her vet jeg ikke om det er noen grense som er satt?

** Forventet oppførsel **
- Dersom alternativet å gå skal komme opp bør det ikke komme opp på nytt når man laster flere forslag

** Akseptansekriterie **
- Vis flere reiseforslag skal ikke vise samme alternativ flere ganger (selv om avgangstidspunkt for den rene gåturen er ulike)
- (Legg til ekstra punkt om rene gåruter dersom dette ikke skal vises - evt ta ut i egen sak)

** Video **
Søk etter turer hjemmefra til Melhus skysstasjon

https://user-images.githubusercontent.com/5812433/149339252-b01e292c-56ca-479d-adc7-26fcb9f4f5db.mp4

**Comment by monopoint** [comment]
dette er en duplikat av #1981
