### ISSUE TITLE
Avreise nå tidspunkt henger igjen

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#1995]
Gjorde et reisesøk i reisesøk v2 for en time siden med default "Avreise nå". La så mobilen til siden og tok deretter opp mobilen for å gjøre et nytt søk (altås en time senere). Endret destinasjon og ser at søket oppdateres. Tidspunktene på søkeresultatene vises riktig med tidspunkt som tilsier søketiden, mens label/knapp for avreisetid står fortsatt som "Avreise nå (13:30)" kl.14:38. Se skjermbilde under.

** Akseptansekriterie **
- Avreise nå bør oppdateres til å reflektere søketidspunktet

** Skjermbilde **
![270865394_449936363457689_6118280097904189081_n](https://user-images.githubusercontent.com/5812433/149341115-137f8e5e-37fd-4710-8a51-fd0397d5a9a9.jpg)

**Comment by tormoseng** [comment]
Ser forøvrig at tidspunktet henger igjen når jeg går til tidsvelger og velger Avgang/Ankomst. Video under er tatt opp kl.14:54. (at søket feilet her er urelatert til akkurat denne saken)

https://user-images.githubusercontent.com/5812433/149343130-cfc74e4e-094b-4e97-badc-372410b0c06c.mp4

**Comment by monopoint** [comment]
er det forskjell fra reisesøk v1?

**Comment by tormoseng** [comment]
Opprinnelig observasjon i saken fungerer i reisesøk v1, mens sak i kommentaren er også gjeldende for reisesøk v1. Kan lage en egen sak for den.

**Comment by hildeor** [comment]
@gorandalum Det som er beskrevet i denne issuen ble vel fikset i dag?

**Comment by hildeor** [comment]
Fikset av https://github.com/AtB-AS/mittatb-app/pull/2073
