### ISSUE TITLE
Upålitelig spinner for lasting av reiseforslag

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#1997]
Har et søk med resultater. Går inn på tidsvelger og trykker på "Søk etter reiser". Det er da tydelig at det søkes etter forslag på nytt (samme som pull-down for å refreshe). Men oppførselen er litt merkelig. 
- Første forsøk gir ingen spinner før resultatene kommer
- Andre forsøk gir ingen resultater (er JPv3 stabilt?)
- Tredje forsøk gir en spinner som ikke spinner før forslagene kommer

Dersom scenarioet er søkt er det en ting, men spinneren virker ikke helt "stabil".

Testet på iOS 15.1

**Akseptansekriterier**
- Spinner skal alltid komme ved henting av søkeresultater

**Video**

https://user-images.githubusercontent.com/5812433/149342166-843767af-d76b-4745-bc3c-11637b1a029d.mp4

**Comment by monopoint** [comment]
ser ut som dette er ios-spesifikt, spinneren vises konsistent på android emulator

**Comment by tormoseng** [comment]
På siste 1.18-stagingbygg finner jeg rester av er en statisk iOS-spinner ved tidsvalg "Nå" > "Søk etter reiser". (ikke fått sjekket Android). Er jo ingen showstopper, men ta en titt under.

https://user-images.githubusercontent.com/5812433/159645286-cc6811a1-66c5-47b7-befb-8b60cc237674.mp4

**Comment by tormoseng** [comment]
Gjelder ikke på Android. Skal vi la denne bare gå @gorandalum ?

**Comment by gorandalum** [comment]
@rosvik tar en rask titt. Hvis det ikke er kjapt løst så rebrander vi til Forvaltning og tar ut av leveransen.

**Comment by rosvik** [comment]
Ser ut om om dette er en feil som skjer fordi vi bruker pull-to-refresh i reisesøk på litt feil måte. Vi viser ikke den innebygde refresh indikatoren til fordel for “laster reiseresulater”-teksten, som skaper litt trøbbel. Rent teknisk forventer refresh-indikatoren at `isRefreshing` skal være true etter at man har startet en refresh, og når vi ikke gjør det, blir det feil (hvis jeg forsår det riktig utifra https://github.com/facebook/react-native/issues/5839#issuecomment-182209883).

Vet ikke hvorfor vi valgte å gjøre det slik, men tenker at i utgangspunktet er det en fordel å ligge nærmest mulig native-implemetasjon. Har ikke funnet noen enkel hack for å løse det som det er, så alternativet er å gjøre refresh på “riktig” måte og forandre litt på designet, eller bare leve med buggen som den er. Prøver å vise de to forskjellige tilfellene i video, først slik det er nå, og så hvordan en løsning kan se ut.

https://user-images.githubusercontent.com/1774972/159928459-d963f8fb-9439-4c50-aa7e-ee40bb834502.mov

**Comment by gorandalum** [comment]
Forslag: Vis native spinner helt fram til noen reiser er lastet. Når noen reiser er lastet, men man fortsatt søker etter flere, så tar vår "custom spinner" over og legger seg nedenfor reisene.

**Comment by tormoseng** [comment]
En liten manglende lasteindikator på iOS ved _Velg tid_ > _Søk nå_. På Android er alt gull.

Tenker vi lar denne gå nå. Ikke verdt innsatsen.
