### ISSUE TITLE
Avganger v2 - Favoritter

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2013]
### Skisser

Krever oppdatering av BFF:

- Nytt endepunkt: Utlisting av informasjon om ett eller flere stopp til visning i favoritt-tab (**potensielt samme endepunkt som i #2227**)
- Mulighet for filtrering av avganger i quay-departures og stop-departures endepunktene.

Kan løses i tre deler: #2427, #2428 og #2429

**Favoritt-tab:**
![Favoritter](https://user-images.githubusercontent.com/8980523/149743437-ff552d41-ee24-4719-959c-5a1c9e151a6c.png)

**Favoritter:**
![Spinner](https://user-images.githubusercontent.com/8980523/149743489-1fa00581-720b-4ab7-8452-34be65d20a4e.png)

**Comment by strombraaten** [comment]
Kan bekrefte at det her er antakeligvis den mest etterspurte funksjonen når vi har testa den nye visningen av Avganger v2 nå ➕

**Comment by rosvik** [comment]
Splittet denne opp i mindre saker, så lukker denne.
