### ISSUE TITLE
Feature - Generisk tilbakemeldingskomponent

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2016]
- Lagring av spørsmål i Firestore
- Innhenting av svar til BigQuery (nytt endepunkt i BFF, sende inn til BigQuery via Pub/sub)
- UI for å hente inn svar på bra/dårlig, og liste ut spørsmål

Estimat: Over uke 

![image](https://user-images.githubusercontent.com/4932625/149747303-373205ea-6056-442a-855c-797b3b2f5b81.png)

**Comment by toretefre** [comment]
Denne avhenger av #2345 (og til dels #2313) for å være helt ferdig, men komponenten i seg selv finnes allerede nå.

**Comment by tormoseng** [comment]
Ser greit ut. Testes bedre som del av #2345
