### ISSUE TITLE
[Feature] Justering av reisesøkparameter fra utvikler-menyen

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#2019]
Etter møte om sortering av reiseforslag ble det foreslått å legge inn mulighet for å justere søkeparameterene som sendes til journey planner for reisesøk i utvikler-menyen, slik at det blir enklere å teste hvilke verdier som er gode defaults, og hvilke man potensielt kan gi brukeren mulighet til å justere på selv. 

Dette krever endring også i BFF, for å støtte parametere som sendes videre til journey planner.

## Forslag til parameterene som skal kunne endres på:

- `transferPenalty` - An extra penalty added on transfers (i.e. all boardings except the first one). The transferPenalty is used when a user requests even less transfers. In the latter case, we don't actually optimise for fewest transfers, as this can lead to absurd results. Consider a trip in New York from Grand Army Plaza (the one in Brooklyn) to Kalustyan's at noon. The true lowest transfers trip pattern is to wait until midnight, when the 4 train runs local the whole way. The actual fastest trip pattern is the 2/3 to the 4/5 at Nevins to the 6 at Union Square, which takes half an hour. Even someone optimise for fewest transfers doesn't want to wait until midnight. Maybe they would be willing to walk to 7th Ave and take the Q to Union Square, then transfer to the 6. If this takes less than transferPenalty seconds, then that's what we'll return.
- `waitReluctance` - Wait cost is multiplied by this value. Setting this to a value lower than 1 indicates that waiting is better than staying on a vehicle. This should never be set higher than walkReluctance, since that would lead to walking down a line to avoid waiting.
- `walkReluctance` - Walk cost is multiplied by this value. This is the main parameter to use for limiting walking.
- `walkSpeed` - The maximum walk speed along streets, in meters per second.

## Parametere som også kan vurderes, men kanskje ikke er like relevante
<details>
  <summary>Klikk for å vise</summary>

- `transferSlack` (**Kun i OTP2**) - An expected transfer time (in seconds) that specifies the amount of time that must pass between exiting one public transport vehicle and boarding another. This time is in addition to time it might take to walk between stops.
- `maximumTransfers` - Maximum number of transfers. Note! The best way to reduce the number of transfers is to set the `transferPenalty` parameter.
- `boardSlackDefault` - The boardSlack is the minimum extra time to board a public transport vehicle. This is the same as the 'minimumTransferTime', except that this also apply to to the first transit leg in the trip. This is the default value used, if not overridden by the 'boardSlackList'.
- `alightSlack` - The alightSlack is the minimum extra time after exiting a public transport vehicle. This is the default value used, if not overridden by the 'alightSlackList'. (Kan altså settes pr. type transportmiddel i `alightSlackList`)
- `timeTableView` (Default: `true`) - Search for the best trip options within a time window. If `true` two TripPatterns are considered optimal if one is better on arrival time (earliest wins) and the other is better on departure time (latest wins). In combination with `arriveBy` this parameter cover the following 3 use cases:
	- Traveler want to find the best alternative within a time window. Set `timetableView=true` and `arriveBy=false`. This is the default, and if the intention of the traveler is unknown it gives the best result, because it includes the two next use-cases. This option also work well with paging. Setting the `arriveBy=true`, covers the same use-case, but the input time is interpreted as latest-arrival-time, and not earliest-departure-time.
	- Traveler want to find the best alternative with departure after a specific time. For example: I am at the station now and want to get home as quickly as possible. Set `timetableView=false` and `arriveBy=false`. Do not support paging.
	- Traveler want to find the best alternative with arrival before a specific time. For example going to a meeting. Set `timetableView=false` and `arriveBy=true`. Do not support paging.

</details>

**Comment by cbrevik** [comment]
Estimat: To dager

**Comment by rosvik** [comment]
Feil i staging nå fikses i #2165
