### ISSUE TITLE
[Realtime] Establish pattern for indicating change on realtime data

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#202]
We now have some instances where the data changes continuously (through polling) and this can lead to instances where the UI just updates without any feedback. We need an established pattern for users to be familiar with.

Different solutions from the top of my head:

- Activity indicator (not optional, but easy. Ensure not to "influence" layout flow)
- Transitions/animations (can be much, but is better to track progress)
- Show update indicator, the Twitter style. Show link "updates are found, click to refresh". (Not best on realtime time changes, but maybe when new departures or trips are found when polling).
- Just update having the UI always reflect the latest changes (this is what we do now, and in some cases it works, in others it can be odd).

This is something we need to think about from design and UX. CC @pettersuul and @haugsand

**Comment by gorandalum** [comment]
Closing as this has been improved in later versions of app.
