### ISSUE TITLE
Utvidet logging på mobile-token

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2061]
- [x] https://github.com/AtB-AS/abt-swift-test/pull/124
- [x] Hooke inn Bugnsag i appen her når ☝🏻 er merged
- [x] Logging injection på JS-lib
- [x] Breadcrumbs i app for state changes
- [ ] Mer eksplisitt logging på errors hvis bruker står fast

**Comment by mikaelbr** [comment]
Nå ligger denne i godkjent, men det er mange unchecked tasks og den er ikke closed. Skal den closes?

**Comment by gorandalum** [comment]
Jeg lukker denne. Det er ikke på et nivå som blir testet på i denne omgang, derfor hopper den over kolonnen for testing. Koden er merget og blir med i 1.17. Hvis vi ser at loggingen fortsatt er mangelfull så oppretter vi en ny sak for tokens fase 3.
