### ISSUE TITLE
Får ikke til å laste inn reiseforslag via singleTripSearch

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#2070]
### Observasjon
Det ser ut som at hvis vi bruker aimedStartTime fra et TripPattern som søkeparameter for å finne det igjen, så mener JP at vi akkurat ikke rekker den reisen, og filtrerer den bort. Hvis jeg padder aimedStartTime med noen minutter, så finner vi igjen reiseforslaget i singleTripSearch.

### Implentasjon
padder startTime med 60 sekunder i compressedQuery

**Comment by tormoseng** [comment]
@monopoint 
- Vil denne saken løse meldingen om at "vi kunne ikke oppdatere reiseforslaget ditt"? 
- Er endringen på BFF ute?
- Ser gjennom proxy at jeg får HTTP 404 på /bff/v2/singleTrip, men at detaljene lastes i app.

**Comment by tormoseng** [comment]
Kommentar over er fikset med ny deploy av BFF/gateway.
