### ISSUE TITLE
Avganger v2 - Forbedre UU

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#2076]
[UU-observasjoner til fase 2](https://github.com/AtB-AS/leveranser/issues/81#issuecomment-1018461420):

- [x] Plattformvelgerne kan gi litt mer info som ex "Aktiver for å vise avganger fra plattform Kongens gate K1".
- [x] Tidsvelger sier bare "0" når klokka er "00:00"
	- Velg annen dag så gir aktuell dag klokkeslett som "Valgt dato 22.januar 0"
- [x] Hvis man endrer tid i dag så leses valgt dato opp som ex "21.januar 13:19" og ikke "i dag 13:19"
- [x] Gi gjerne en beskjed på skjermleser om man velger en tid tilbake i tid (tidsvelger). Android sier f.ex "slått av" om man velger dato tilbake i tid, men ikke iOS. Og endring av tid tilbake i tid på samme dag som i dag gir ingen endringer i resultat, men kunne evt vært opplyst om (dersom mulig).
- [x] Forrige og Neste dag gir kun beskjed om "knapp"
- [x] Burde opplesning av en linje også lese opp den valgte dagen og ikke kun klokkeslett når en dag i fremtiden er valgt?
- [x] Fokus på en avgang gir ingen info om at man kan åpne for å vise detaljer
- [x] ~Åpning av en avgang i detaljvisningen leser opp ex "forventet tid Prinsens gate P1" (kun iOS. Android leser "Overskrift Prinsens gate P1")~ ([kommentar](https://github.com/AtB-AS/mittatb-app/issues/2076#issuecomment-1032419918))
- [x] Etter søk etter holdeplass så leses kun synlig tekst opp på en holdeplass. Kunne lagt på noe a la "Velg for å ..."
- [x] ~Gjør "New features" trykkbar når voiceover er aktivert~ Works as intended?

### Android

- [ ] Avgangsmeny-punktet velges/fokuseres etter å ha bekreftet en dato/tid i datovelger (iOS). Ingen fokus for Android.
- [ ] Etter å ha trykket på en plattform for å vise avganger herfra så leses ingenting opp (kun Android)

Generelt leser Android opp "Dobbelttrykk for å aktivere" i tillegg på knappene. Ikke iOS.

**Comment by rosvik** [comment]
> Tidsvelger sier bare "0" når klokka er "00:00"

Tenkte det hadde vært greit å se hvordan forskjellige klokkeslett blir lest opp i native iOS komponenter, slik at man har en "fasit" å gå ut etter. 

Sjekket det som leses opp av tidsvelgeren i DepartureTimeSheet, vs. klokkeslett skrevet inn i  ThemeText (F.eks. `<ThemeText>circa 00:00</ThemeText>`)

![collage](https://user-images.githubusercontent.com/1774972/151368179-5c2d29f4-f139-4762-91ef-c909ea60bea3.png)

("✅" betyr at det er nøyaktig det samme som blir lest som native)

| Testcase | Native, engelsk | Native, norsk | ThemeText, engelsk | ThemeText, norsk |
| --- | --- | ---- | ---- | --- |
| 00:00 | zero | null  | ✅ | ✅ |
| 00:01 | zero o' 2 | null, null en | zero, zero 1 ❌| ✅ |
| 00:12 | zero 12 | null, 12 | ✅ |  ✅|
| 01:00 | one | en | ✅ |  ✅ |
| 01:12 | one 12 | en 12 | ✅ | ✅ |
| 02:02 | 2 o' 2 | 2 null 2 | 2 zero 2 ❌ | ✅ |
| 16:00 | 16 | 16  | ✅ | ✅ |
| 16:02 | 16 o' 2 | 16 null 2 | 16 zero 2 ❌ | ✅ |
| 16:59 | 16 59  | 16 59  | ✅ | ✅ |

Altså er det kun "o'" vs. "zero" som er forskjellen mellom en native og tidspunkt klokkeslett i ThemeText.

For å komme tilbake til poenget, tror jeg ikke det er hensiktsmessig å prøve å styre hvordan klokkeslett blir opplest, men heller prefikse det slik at det leses "klokken 0", "klokken 16 59".

**Comment by rosvik** [comment]
> Gi gjerne en beskjed på skjermleser om man velger en tid tilbake i tid (tidsvelger). Android sier f.ex "slått av" om man velger dato tilbake i tid, men ikke iOS. Og endring av tid tilbake i tid på samme dag som i dag gir ingen endringer i resultat, men kunne evt vært opplyst om (dersom mulig).

Legger inn beskjed på submit-knappen i dato velgeren at "Valgt tidspunkt er i fortiden. Nåtid vil bli brukt i stedet."

**Comment by rosvik** [comment]
> Åpning av en avgang i detaljvisningen leser opp ex "forventet tid Prinsens gate P1" (kun iOS. Android leser "Overskrift Prinsens gate P1")

Ikke et problem med avganger, men reisedetaljer v1. Venter til jeg får implementert reisedetaljer v2 før jeg evt. fikser.

**Comment by tormoseng** [comment]
Alle punkter som er rettet er testet OK.

Står igjen to observasjoner for Android, men disse er mindre viktige så de legges i egen sak som kan prioriteres på egenhånd: #2150
