### ISSUE TITLE
[BUG] For mye padding mellom header og reiseforslag

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2077]
### Bakgrunn 
<img width=450 src="https://user-images.githubusercontent.com/675421/151356911-186ac633-82ce-45c4-a7f0-8a0bb17eca5b.jpg"/>

Feil er en trolig en bug i disappearing-header.

Hilde sin oppskrift for å gjenskape. Starter appen fresh og har OTP2 søkemotor:

1. Reisesøk-fane
1. Fra: Skriv inn og velg Midtre Gauldal legekontor
1. Til: Rindal (sted)
1. Vent på at alle resultatene er ferdig lastet inn.
1. Marker fra-feltet og skriv inn Kvål (sted)
1. Til: Rindal (sted)

### Løsningsforslag
`contentHeight` i `DisappearingHeader` blir evaluert når animasjonen er ferdig, men om header endrer størrelse så blir ikke denne oppdatert. Ved søk fra "Midtre Gauldal legekontor" som går over to linjer i input-feltet så blir det en feil verdi for `contentHeight` når man endrer til "Kvål" som bare gå over en linje.

Merk at dette er kun teori, og ikke testet.

## Akseptansetester

- [ ] Fungerer for Android med notch
- [ ] Fungerer for Android med små skjerm
- [ ] Fungerer for Android uten notch
- [ ] Fungerer for iPhone mini
- [ ] Fungerer for iPhone uten notch
- [ ] Fungerer for iPhone Pro Max med notch og stor skjerm.
- [ ] Animasjon mellom fullscreen og "header modus" animerer som forventet (både frem og tilbake).
- [ ] Fungerer for Avganger-visning som forventet.
- [ ] Scroll "tar tak i header" på rett tidspunkt i scroll.

**Comment by gorandalum** [comment]
Ny informasjon tyder på at dette kan oppstå uavhengig om sted brukt i reisessøk går over to linjer eller ikke,

**Comment by mikaelbr** [comment]
Denne er egentlig en duplikat av #746, men denne er bedre beskrevet.

**Comment by mikaelbr** [comment]
Se [PR for forklaring](https://github.com/AtB-AS/mittatb-app/pull/2364) på hva som har skjedd. I praksis har det vært noe uforutsigbar kompensering for insets som har skjedd på iOS. Derfor har det alltid fungert for Android. Fikset gjør at det ikke skjer lengre, samtidig som den fjerner kode som da ikke lengre er relevant. Jeg har oppdatert issue beskrivelse over med en liste over ting som burde sjekkes. Jeg har sjekket på ulike størrelser på iPhone og Android, men fint også å teste på fysiske enheter en gang.

**Comment by tormoseng** [comment]
Denne er testet OK på ulike reelle devicer.
