### ISSUE TITLE
Implementere force-resend for SMS-innlogging

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2082]
### Observasjon

Brukere opplever at engangskode aldri kommer fram.

### Analyse
Firebase Auth SDK for mobile lar oss sende inn `forceResend` for OTP. Denne bør muligens taes i bruk når brukeren velger å "send en ny engangskode" i login

```typescript
     * @param phoneNumber The devices phone number.
     * @param forceResend Forces a new message to be sent if it was already recently sent.
     */
    signInWithPhoneNumber(phoneNumber: string, forceResend?: boolean): Promise<ConfirmationResult>;
```
### Impl
utvider signInWithPhoneNumber til å ta inn optional parameter forceResend, settes til false som default.
Ved onResendCode settes forceResend til true. 

### Test
Kan testes lokalt fra dev, som default går mot staging. 
velg logg inn med SMS, skriv inn et reelt mobilnummer du har tilgang til.
trykk "Send på nytt" og verifiser at ny kode sendes.
Vær oppmerksom på evt rate limit.

i QA (og prod) kan safetyNet blande inn en finger, så det må testes ekstra.

**Comment by jahnrohme** [comment]
Sjekke direkte med support GCP?

**Comment by tormoseng** [comment]
Virker greit. Må ta en ekstra runde i TestFlight på teamet

**Comment by cbrevik** [comment]
Apropos; etter leting i kildekode så ser det ut til at denne kun har effekt på Android; https://github.com/invertase/react-native-firebase/blob/ddf3f5f43d2c8547879934c3169d3e01c0db44c0/packages/auth/lib/index.js#L229-L233
