### ISSUE TITLE
Organisering av SVG-assets

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2085]
En uskreven regel vi har er at `mono-icons` skal være innenfor et gitt størrelseskrav, kunne overstyres på farger, og være gjenbrukbare på tvers av aktører. Når har vi hatt et case av at i fht. reisebevis ønsker vi å overstyre fargen på noen SVG-er (slik som reisebevis), men de passer ikke direkte inn som `mono-icons`. Hvordan burde vi organisere disse? Diskusjonspunkt til grooming.

En av prinsippene vi har blitt enig om tidligere (men ikke har blitt godt kommunisert) er at Figma skal være source-of-truth, og så skal vi kunne eksportere direkt derfra til samme struktur i kodebase.

Reisebevis-SVGer:
![image](https://user-images.githubusercontent.com/4932625/151543152-f96f52ac-59c1-4666-bf10-a9d569c454a3.png)

Mono-icons-struktur:
![image](https://user-images.githubusercontent.com/4932625/151542997-a70ad278-3ee8-44ae-a376-04b508704999.png)

**Comment by hildeor** [comment]
FYI: Har prøvd å samle alle ikke-monoikoner under Illstrations i Componentsfila i Figma nå:
<img width="1652" alt="Skjermbilde 2022-02-11 kl  13 28 50" src="https://user-images.githubusercontent.com/8980523/153591519-48cc839c-509b-4ed2-b48b-43a137732dcc.png">

[Figma](https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components-1.0?node-id=335%3A1019)

**Comment by mikaelbr** [comment]
@monopoint Kan du oppdatere her manglene du fant i adapsjon av v4?

**Comment by monopoint** [comment]
la inn ny SVG uten drop shadow som fikser en feil der filter ble rapportert som ikke støttet

**Comment by tormoseng** [comment]
Testes gjennom gjennomgang av app v.18 og gjennom ny webshop.

Se forøvrig #2556 for funn relatert til 1.18
