### ISSUE TITLE
Avganger v2 - Oppdater key i listen av EstimatedCallLines til `servicejourney.id + aimedDepartureTime`

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/mittatb-app#2090]
Ref. slack tråd med entur https://mittatb.slack.com/archives/CHLDG8C30/p1643618052446099

I noen tilfeller (jeg ser på deg, ringen i Oslo) vil noen service journeys besøke samme stopp to ganger på en tur. Derfor kan man ikke annta at `servicejourney.id` er unik når man lister ut avganger. Løsning er å bruke `servicejourney.id + aimedDepartureTime` som key istedet.

- [x] Trenger at `aimedDepartureTime` blir lagt til i BFF, både for StopPlace og Quay. https://github.com/AtB-AS/atb-bff/pull/118

https://user-images.githubusercontent.com/1774972/151796159-e4fb4706-4a62-4539-b37d-4dfa21b53382.mp4

**Comment by tormoseng** [comment]
Gull!
