### ISSUE TITLE
Bug: Enkelte strekninger har ikke reiser i en periode og pageCursor feiler

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#2103]
### Observasjon
Enkelte strekninger har ikke avganger i en periode, feks i helg. når JourneyPlanner (JP) søker etter reiser i denne perioden, feiler den, og vi får tilbake tomt resultat med hverken metadata eller pageCursor (lenke til neste side i søket). Vi viser da tomt resultat og en "Last inn flere"-knapp som ikke funker.

### Analyse
JP har tilgjengelig cache/heuristikk for reiser kun på søkedagen og de neste to dagene. Når JP søker etter reiser, og ikke finner noe som helst i heuristikken, havner JP i en uavklart tilstand og klarer ikke å gi oss noe data hverken om hva slags søkevindu som er bukt, eller en pageCursor vi kan bruke til å fortsette søket til påfølgende dager.
Dette skjer typisk når det på en strekning ikke finnes noen reiser i en helg. Hvis Bruker søker etter reiser sent på fredag kveld, så finner ikke JP noen reiser hverken på resten av fredag, lørdag eller søndag, og feiler, selv om det faktisk finnes reiser på mandag.

### Løsning
Dette er et problem som bunner ut i hvordan OpenTripPlanner funker, og entur er konfigurert. Det er forholdsvis skjelden det skjer. Det er ikke sannsynlig at entur kommer til å utbedre dette på kort sikt.
Det vi kan gjøre i disse tilfellene er å identifisere når situasjonen oppstår (ved å se at vi har tomt resultat uten pageCursor), og da enten 
- gi en god tilbakemelding, og fjerne "Last inn flere"-funksjonaliteten.
- Trikse til søket ved å maskinelt justere søketidspunkt og prøve et nytt søk. vi må da ta konsekvensene av at vi trikser. 

I samråd med Simen og @hildeor ble vi enige om  å gå for forslag 1, "gi tilbakemelding og fjern knappen"

### Testbeskrivelse
Et søk på reise fra `Forsølbukta, Hammerfest` -> `Øvre Ramse, Åmli` på `fredag kl 22` Vil fremprovosere denne feilen. 
Endre deretter søketidspunktet til `Lørdag kl 22` for å komme tilbake til normalen
Kun aktuell på reisesøk v2, siden v1 ikke har funksjonalitet for å laste flere.

**Comment by cbrevik** [comment]
T-skjorte: Small

**Comment by tormoseng** [comment]
Testet OK
