### ISSUE TITLE
Avgangsdetaljer for Nattbuss viser blank side

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#2104]
### Observarsjon
Gjør et søk der nattbuss er et reisealternativ
Ved å klikk på reiseforslaget kommet man til reisedetaljer. Her vises alle delene av reisen, inkludert nattbuss-delen, der alle holdeplassene er kollapset til et antall.
Klikk på det kollapsede antallet navigerer til Avgangsdetaljer for den spesifikke avgangen. Dette feiler og vi viser bare en blank side.
Dette gjelder både gammelt og nytt reisesøk.

https://user-images.githubusercontent.com/1464594/152391047-b3d1c94c-3b8c-489e-9dc2-fd3aefb7cead.MP4

### Analyse
Både det nye og det gamle reisesøket bruger JP2, og entur sin SDK (dvs et knippe med endepunkter som entur har implementert)
~Det ser ut til at dette endepunktet (DeparturesForServiceJourney) ikke håndterer når mode=bus og SubMode=nightbus og returnerer et tomt resultat. Dette endepunktet lar oss ikke sende inn parametre som gjør at nattbuss vil bli støttet.~
Grunnen til at vi ikke finner noen avganger for denne serviceJourneyen er at vi bruker feil dato. Vi sender inn datoen for når reisen skjer, men det er ikke teknisk riktig. her skal serviceDate inn, som i realiteten er dagen før avgangen på nattbuss.

### Løsning
På sikt burde vi implementere getDeparturesForServiceJourney med JP3, men det blir en større jobb.
For å fikse denne buggen nå, er det bedre å få hentet ut serviceDate for serviceJourneyen og sende inn den istedet.
Det eneste fornuftige stedet jeg kan se at vi kan hente ut serviceDate er fra 
`trip/tripPatterns/legs/intermediateEstimatedCalls/date`

### Testbeskrivelse
Løsningen inneholder endringer på BFF og App.
Endringene på BFF skal være bakoverkompatible, så det er grunn til å teste at eksisterende versjoner av appen også funker mot ny BFF.
Det er gjort endringer på datamodellene som brukes i gammelt og nytt reisesøk, og gammele og nye Avganger. Flyten gjennom disse skjermene må teste. 
Det som skal funke er altså å gjøre et søk, og så klikke seg helt fram til avgangsdetaljer, og her skal man ikke få blank side.
Denne saken startet med en feil som ble observert for nattbuss, men feilen eksisterer for alle reiser. Akkurat nå er nattbusser innstilt pga korona, så det kan være litt vanskelig å framprovosere den feilen i prod, men nattbusser er der i dev. Feilen skal også kunne fremprovoseres på avganger som går etter midnatt, men som fortsatt regnes som rutetilbudet til dagen før, typisk de siste avgangene før bussene slutter å gå for natten. i disse tilfellene skal avgangstiden for bussen ligge en dato forran serviceDate. i datamodellen ligger serviceDate under estimatedCalls/date

**Comment by tormoseng** [comment]
Det ser bra ut!

Testet fint med reisesøk v2 /avganger v2 på App v1.14 også. App v1.13 får HTTP 400 med message": "\"arriveBy\" is required", men dette er jo endret på og ikke påvirket av denne endringen. Reisesøk v1 / Avganger v1 fungerer fint på v1.13 og v1.14 også
