### ISSUE TITLE
[Feature] Enkeltbillett (v2)

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2106]
## Origin
Som en del av leveransen https://github.com/AtB-AS/leveranser/issues/88

Se leveranse for mer utfyllende informasjon.

## Todos

Avhengig av utforming av design-system #2109

- Skal kunne toggle av og på info. Den skal være på som default.
- Toggle husker valget til neste gang
- Ingen passasjerkategori skal være forhåndsvalgt, men du får spørsmål etterpå om du vil sette standard passasjerkategori (se egen issue #2107 )
- Sonevelger skal være det samme som før, men knappen for å gå inn på sonevelgeren er annerledes.

## Skisser

[Figma-skisser](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=7601%3A66411)

<img width="1196" alt="Skjermbilde 2022-02-03 kl  12 44 32" src="https://user-images.githubusercontent.com/8980523/152336647-cc111833-4901-4c43-853d-48d5b5231bd4.png">

**Comment by gorandalum** [comment]
Dette inngår i andre saker.
