### ISSUE TITLE
[Feature] Periodebillett (v2)

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2108]
## Origin
Som en del av leveransen https://github.com/AtB-AS/leveranser/issues/88

Se leveranse for mer utfyllende informasjon.

## Todos

Avhengig av utforming av design-system #2109

Mye likt som #2106 (bortsett fra oppstartstidspunkt)

- Horisontal scroll på periodelengde. Sortert etter stigende varighet. 
- Toggle (slik som på enkeltbillett) for å skjule/vise ekstra informasjon om passasjerkategorier. Default er på.
- Sone-angivelse lik oppførsel som på enkeltbillett.
- Kunne velge oppstartstidspunkt: Nå er default. Trykk på "Senere" åpner om samme komponent som brukes i dag. Etter man har valgt senere oppstartstidspunkt vises dette i labelteksten.

## Skisser
[Figma-skisser](https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=6600%3A44952).

<img width="795" alt="Skjermbilde 2022-02-03 kl  12 34 33" src="https://user-images.githubusercontent.com/8980523/152335366-8b7d2d40-6e14-465e-85f2-102daddc120a.png">

<img width="1433" alt="Skjermbilde 2022-02-03 kl  12 35 15" src="https://user-images.githubusercontent.com/8980523/152335448-c67a7459-3df0-438e-b19f-8b91ff355665.png">

**Comment by gorandalum** [comment]
Dette inngår i andre saker.
