### ISSUE TITLE
Ny kjøpsflyt

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2109]
## Origin
Som en del av leveransen https://github.com/AtB-AS/leveranser/issues/88

Se leveranse for mer utfyllende informasjon.

## Beskrivelse av komponenter og skisser

I denne saken inngår implementering av nye komponenter for å støtte kjøpsflyten. Vi implementerer kun komponentene som trengs for billettproduktene vi har i denne omgang.

Ny billettkjøpsflyt er bygd opp av en samling med komponenter på tvers av billettprodukter.

### Karusell
Brukes som hovedregel for å velge antall. Bare én kan velges om gangen.  Scrolles horisontalt hvis skjermbredden ikke kan vise hele.

Brukes på:
- Periodebilletter
- Ungdomsbillett
- Klippekort
- 24 timersbillett
- Sommerpass

![Skjermbilde 2022-02-07 kl  14 37 24](https://user-images.githubusercontent.com/8980523/152798355-8cfd7918-babf-413c-a505-81c1019f289a.png)

### Tekst-input
Brukes for å navigere til eksisterende sonevelger og vise frem valgt sone. Består av label og verdi.

Brukes på:
- Periodebilletter
- Enkeltbillett
- Klippekort
- 24 timersbillett

![Skjermbilde 2022-02-07 kl  14 38 27](https://user-images.githubusercontent.com/8980523/152798807-8c62981a-5233-4676-87a5-0affee39a053.png)

### Segmented controls
Brukes for å velge oppstartstidspunkt for en gitt billett. Står default på Nå. Ved valg av "Senere" får man opp eksisterende dato/tidsvelger. Deretter vises også evt. dato og tidspunkt som er satt når man har endret til senere.

Brukes på:
- Periodebilletter
- Enkeltbillett (i fremtiden?)
- Ungdomsbillett
- 24 timersbillett
- Sommerpass

![Skjermbilde 2022-02-07 kl  14 44 52](https://user-images.githubusercontent.com/8980523/152799634-5eb4af1e-b58a-45c6-9105-2fd3648f81ae.png)

### Sammendrag
Oppsummerer pris og hvilket transportmiddel billetter er gyldig på.
Knapp for å gå videre til betaling.

Brukes på:
- Alle billettyper

![Skjermbilde 2022-02-07 kl  14 46 09](https://user-images.githubusercontent.com/8980523/152799838-5faa4dbc-e314-47c3-8f3f-c6f629d60968.png)

### Infoboks
Brukes om det er spesifikk informasjon man ønsker å sende ut på en viss billettype. Eksempler kan være å sjekke for andre gyldige reiserettigheter, hva et sommerpass er, at nattbillett er det sannsynlige reisealternativet i et gitt tidsrom.

Brukes på:
- Sommerpass
- Nattbillett
- Enkeltbillett

![Skjermbilde 2022-02-07 kl  14 46 20](https://user-images.githubusercontent.com/8980523/152799872-1a7192e8-b927-4889-ae2b-e3a6d74b4cb9.png)

### Helge-velger
På nattbillett spesifikt er det kun gyldige reiser i helg. I stedet for å gi full date picker viser vi kun dager i helg hvor det er gyldig og hensiktsmessig å kjøpe nattbillett. Ved å trykke på Vis flere datoer dukker neste helg opp. Bare én kan velges om gangen. 

Brukes på:
- Nattbillett

![Skjermbilde 2022-02-07 kl  14 55 09](https://user-images.githubusercontent.com/8980523/152801311-69c91930-c87d-4b6f-8a77-e1331a2e9d45.png)

### Passasjerkategori - radiobutton
Noen billettyper kan kun selges med én passasjer. Eksempler på dette er periodebilletter, eller Ungdomsbillett.
Disse vises som radiobuttons. Antall passasjerkategorier vil kunne variere fra billett til billett. Informasjonstekster om de ulike passasjerkategoriene kan toggles. Default er PÅ.

Brukes på:
- Periodebilletter
- Klippekort
- Nattbillett (konsept ikke helt avklart)
- Ungdomsbillett
- 24-timersbillett

![Skjermbilde 2022-02-07 kl  15 11 39](https://user-images.githubusercontent.com/8980523/152804336-bb7d52c8-d245-45f6-8ef3-9f02d0a5bc73.png)

### Passasjerkategori - multiselect
Andre billettyper som f. eks enkeltbillett støtter flere passasjerer på samme billett. Se egen issue (#2107) for beskrivelse av logikk rundt lagring av standard passasjerkategori.
Når en kategori er > 0, får den bakgrunnsfarge bak antallet. I tillegg blir minus-ikonet sort. Viktig at minus-ikonet fortsatt er mulig å navigere til via VoiceOver. Også infotekster kan toggles.

Brukes på:
- Enkeltbillett
- Sommerpass

![Skjermbilde 2022-02-07 kl  15 17 33](https://user-images.githubusercontent.com/8980523/152805119-4efc74bc-76b7-43b8-8c2b-b29f3c926545.png)

## Todos
- Burde passe inn i "eksisterende" Section-basert komponent-bibliotek
- Er dette issuen som endelig gjør at vi setter opp en Storybook? Hvem vet?

**Comment by gorandalum** [comment]
Lukker denne da denne er oppdelt i mindre saker per komponent.
