### ISSUE TITLE
[Bug] Når et reiseforslag blir langt blir det visuelt kuttet uten at det er mulighet for å scrolle horisontalt

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#2114]
### Beskrivelse
Når man får opp reiseforslag så vil visningen i flere tilfeller vise legs og overganger som går utover tilgjengelig plass. Dette feltet skal være scrollbart, men i praksis så er det vanskelig å scrolle uten å trykke på reisen slik at detaljene lastes. På Andorid kan man få det til om man er veldig rask med å scrolle etter å ha "trykket", mens på iPhone så er dette nærmest umulig.

Denne saken er omtalt på [Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643288458048400).
Gjelder både reisesøk v1 og v2.

### Løsning
<img width="692" alt="Skjermbilde 2022-02-15 kl  15 59 45" src="https://user-images.githubusercontent.com/8980523/154088277-0817de92-cdb5-47d8-82dc-91b4975b6ed8.png">

- [ ] Ingen horisontal scroll. 
- [ ] Hele feltet er fortsatt klikkbart for å gå til detaljer
- [ ] Ved mange legs trunkerer vi og viser f. eks “+3” hvis det er 3 legs som er kuttet i visningen.
- [ ] Farge på "+3" er transport-other

### Implementasjon
Det er ikke rett fram å vite hvor mange legs som skal kollapses til en `+n`. forsøk på å lage en enkel cut-off på 3 eller 4 legs viste seg å ikke funke noe bra på veldig små skjermer eller for brukere med større skrifttype. Skrev derfor om til en dynamisk startegi, der vi prøver å rendre ut alle legs, for så å se om vi får plass. hvis vi ikke får plass kollapses en og en til vi er innefor bredden av komponenten. Det førte til litt hopping og lugging. Vi skjuler derfor komponenten til den er ferdig kollapset, og fader det inn. 
Fant samtidig at for brukere med stor skrift/liten skjerm, så brekker detaljer-knappen over 2 linjer. restrukturerte derfor result footer til å forkorte holdeplassnavn med "..." hvis det ikke er plass.
Litt sparring med @hildeor førte til at vi kutter ut mål-ikonet, siden det ikke egentlig gir noen verdi, og bare tar opp plass.

https://user-images.githubusercontent.com/1464594/154708665-a8a782e3-d220-420b-8d3b-9bb675d210bf.mp4

### Testbeskrivelse
jeg tror det viktigste her er å teste at "+n"-boblen teller riktig i alle tilfeller, evt være bevisst på om antallet gir mening for brukeren (burde venting telle?). 
Test på stor skrifttype, store og små skjermer.

**Comment by hildeor** [comment]
Oppdatert med løsningsforslag.

**Comment by monopoint** [comment]
oppdatert med Implementasjon- og test-beskrivelse

**Comment by tormoseng** [comment]
Testet OK
