### ISSUE TITLE
[Bug] Mange duplikate reiseforslag ved å velge Ankomst før

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#2115]
### Observasjon
Ved å velge ankomst før på reisesøk v2 så kommer det mange duplikate reiser.

Original post på [Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1643362553448509), som tas videre med Entur [her](https://mittatb.slack.com/archives/CHLDG8C30/p1643363172658369?thread_ts=1642599972.020600&cid=CHLDG8C30). Se også @gorandalum sitt eksempel på Slack [her](https://mittatb.slack.com/archives/C02EEG7D8EL/p1643630948849719).

Spørsmål fra @gorandalum 
> Vi får nå en feil i vår staging-versjon med duplikate treff med arriveBy: true-søk. Tidligere har vi brukt arriveBy: true og prevPageCursor og på klientside akkumulert en liste over treff, slik som gjøres ved et “vanlig” søk med arriveBy: false og nextPageCursor . Men det er slik at den siste versjonen innfører en ikke-bakoverkompatibel-endring ved at søk med arriveBy: false og prevPageCursor nå inneholder alle akkumulerte treff i responsen, og man ikke lenger skal akkumulere treff selv klient-side?

En mulighet her er å fjerne opprinnelige forslag når man laster flere reiser ved valgt "Ankomst før"

### Analyse
Duplikatene er en feil, og er [registrert i OpenTripPlanner](https://github.com/opentripplanner/OpenTripPlanner/issues/3890)
Siden entur forventer forholdsvis lang tid før de kan levere en fiks, er det bedre at vi implementerer client side filtrering i appen
-emh

### Implementasjon
Det er hensiktsmessig at vi benytter react key som en unik client side identifikator for TripPatterns. Både react og Appen forventer at reiser er unike, så react key fyller begge rollene.
Vi har tidligere brukt compressedQuery som en del av react-key for å generere unike nøkler for reiseforslagene. Det må vi nå gå bort fra, siden compressedQuery innholder pageCursor, og gjør at vi ikke kan skille duplikater som kommer fra forskjellige pages.
Det genereres en  ny react key basert på
- aimedStartTime fra første leg med ServiceJourney
- geoposisjon til alle ankomststeder (long-lat)

Det bety at rene gåstrekninger ikke har start-tid, og har bare to posisjoner. det anser jeg som greit.
Det betyr også at vi ikke skiller mellom TripPatterns der den reisende må enten vente ved quay A eller quay B, men ellers er like. Det anser jeg også som ok, og nesten til og med en feature, siden vi ikke har noen muligher å identifisere den subtile forskjellen i skjermbildet for reisedetaljer, der vi prøver å søke opp den samme reisen en gang til for å fange opp endringer i reiseruten. Mao: det finnes ingen måte vi kan formulere et søk der vi spesifiserer at reisende helst vil vente på quay B. Dermed er det like greit at vi anser dem som duplikater, og vi velger ut det første som entur foreslår.
-emh
### Testbeskrivelse
jeg har lagt inn logging når duplikater oppdages og filtreres ut. både orginal og duplikat logges slik at det går an å sammenlikne dem og evaluere duplikatness. enkelte ganger vil det være duplikater med små avvik, men det er greit. Vi har observert at entur  leverer TripPatterns med små avvik (men som likevel bør regnes som duplikater), men at de forsvinner igjen senere på dagen, som kan tyde på at entur fortsatt tuner sine algoritmer.
Duplikater oppstår hyppig ved reisesøk med ankomst-tid. I sjeldne tilfeller hender det at det oppstår i søk med avgangstid.

eksempel på log: 
![image](https://user-images.githubusercontent.com/1464594/154130648-7ac20cf2-d7d3-4897-9462-463921364d56.png)

-emh

**Comment by monopoint** [comment]
det ser ut som vi må filtrere resultater for duplikater i appen

**Comment by monopoint** [comment]
Blocked mens vi venter på [bugfiks i opentripplanner](https://github.com/opentripplanner/OpenTripPlanner/issues/3890).

**Comment by tormoseng** [comment]
@monopoint Forbedringsforslag som formidlet på [Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1645019413011059)

**Comment by tormoseng** [comment]
> @monopoint Forbedringsforslag som formidlet på [Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1645019413011059)
Besvart på Slack. Bør håndteres av Entur. Problemstilling tas opp der

**Comment by tormoseng** [comment]
Testet OK

**Comment by tormoseng** [comment]
Forbedring av denne saken er lagt i #2194
