### ISSUE TITLE
Informere om samarbeidsbillett for enkeltbillett i sone A

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2155]
Fra 1. mars vil samarbeidsbilletten være gjeldende, og da skal enkeltbillett i sone A også være gyldig på tog. Det er et ønske om at dette skal informeres om i kjøpsprosess, samt på billettdetaljer. 

Origin: Trond på System

CC @jahnrohme 

### Løsningsforslag:
<img width="1558" alt="Skjermbilde 2022-02-18 kl  09 51 59" src="https://user-images.githubusercontent.com/8980523/154649860-558bea13-3dad-4698-b802-3318fda52ded.png">

**Comment by cbrevik** [comment]
Det er ikke veldig komplisert å legge til en ekstra setning, men tenker meldingsboksen legger opp for et system hvor vi kan informere om ting uten at vi trenger å knytte det for hardt opp mot en gitt aktør. Tenker hvis f. eks. NFK eller FRAM har noe spesiell informasjon som gjelder under gitt omstendigheter. I så tilfelle er det kanskje greit å gjøre det med meldingsboks/generisk sånn sett.

**Comment by cbrevik** [comment]
Bør informere om periodebillett på samme vis eller ei? @jahnrohme

**Comment by strombraaten** [comment]
Støtter meldingsboksen under selve billetten 👍 Ved å legge inn den setningen på billettvisninga (detaljer) så gjør vi også resten av informasjonen der mindre lesbar, siden det øker mengden med tekst man må skumme gjennom. Derimot ved å separere det med en egen meldingsboks så skaper vi en god kontrast i informasjonen som vises, og alt blir lettere å scanne fort gjennom.

**Comment by cbrevik** [comment]
Estimat: 2 dags

**Comment by jahnrohme** [comment]
> 

Ja, periodebilletten må også få samme info.

**Comment by rosvik** [comment]
Kan oppdatere PR, men hva blir ny tekst da? Noe sånt?

'Visste du at enkelt- og periodebilletter i sone A også kan brukes på tog i sone A?'
'Single and period tickets in zone A can also be used for trips by train in zone A.'

**Comment by rosvik** [comment]
Kan oppdatere, men trenger litt input på oppførsel / språk. 

1. Skal man vise samme melding på periode- og enkeltbilletter? Da med tekst noe sånt som
	- 'Visste du at enkelt- og periodebilletter i sone A også kan brukes på tog i sone A?'
	- 'Single and period tickets in zone A can also be used for trips by train in zone A.'
2. Eller skal det være to forskjellige meldinger, en for periode og en for enkeltbillett?

Mulig det gir mest mening å ha forskjellige meldinger, siden de fleste ikke har tilgang til periodebilletter i appen enda.

@jahnrohme @hildeor

**Comment by hildeor** [comment]
Tenker kanskje det er mest fleksibelt med tanke på fremtidig bruk og potensielle endringer å ha to separate meldinger. La oss si at man ønsker å legge til en slik melding på en annen produkttype, eller man endrer betingelsene rundt enkeltbillett eller periodebillett.

Visste du at enkeltbilletter i sone A også kan brukes på tog i sone A?
Visste du at periodebilletter i sone A også kan brukes på tog i sone A?

**Comment by JuliaOppegard** [comment]
Enkeltbilletter i sone A kan også brukes på tog i sone A.
Periodebilletter i sone A kan også brukes på tog i sone A

**Comment by jahnrohme** [comment]
@rosvik :point_up:

**Comment by rosvik** [comment]
@JuliaOppegard 👍

Engelsk:
- Single tickets in zone A can also be used on train in zone A.
- Period tickets in zone A can also be used on train in zone A.

Ok?

**Comment by JuliaOppegard** [comment]
Topp :)

**Comment by tormoseng** [comment]
Testet OK
