### ISSUE TITLE
[Ticketing] Extended pilot Ticketing purchase Feature

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#216]
## Motivation
This issue represents the extended implementation of ticket purchasing planned for the pilot. This issue supercedes #187 

## Tasks

App-related:
- [ ] #192 
- [ ] #193 
- [ ] #195
- [x] #217 

Ticket API related:
- [x] https://github.com/AtB-AS/atb-ticket/issues/6
- [x] https://github.com/AtB-AS/atb-ticket/issues/9

**Comment by gorandalum** [comment]
Done
