### ISSUE TITLE
[chore] Fikse bygget for Android staging med Bugsnag sourcemaps upload

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#2183]
`npm WARN deprecated bugsnag-sourcemaps@1.3.0: This package has been replaced by @bugsnag/source-maps. Please upgrade.`

Vi får feil tidvis på staging-bygget (og sikkert store-bygget) for Android med måten sourcemaps blir lastet opp. Vi må bytte dependency her: https://github.com/AtB-AS/mittatb-app/runs/5215170352?check_suite_focus=true

**Comment by rosvik** [comment]
@tormoseng Vet ikke om det gir mening å legge slikt som det her i test-kolonnen på arbeidsboardet. Det eneste å følge med på her er at "Upload bundle and source maps"-steget for android fungerer i GitHub actions. F.eks. https://github.com/AtB-AS/mittatb-app/runs/5333844479?check_suite_focus=true

**Comment by tormoseng** [comment]
@rosvik Helt enig i din betraktning! Denne testes implisitt, så om du ser at det ser ut til å gå bra så er denne fikset!
