### ISSUE TITLE
[Feature] Buy tickets as an integrated part of travel search

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#219]
## Origin
Links to recieved feedback, user research or other findings.

## Motivation
A short description of what user needs or business goals this feature will solve.

Mange brukere vil benytte reiseplanleggeren for å finne en komplett reiserute fra A til B. Å tilby muligheten for å kjøpe billetter som en del av den samme flyten, gir følgende fordeler:

* Brukeren sparer tid fordi han slipper å bytte til billett-fanen i appen.
* Brukeren slipper samtidig å bytte kontekst fra reiseplanlegging til billettkjøp.
* Vi kan gjøre brukeren trygg på at han kjøper riktig type billett. 

Skal billettkjøpet foregå som en egen flyt integrert i visning av den detaljerte reiseruten, eller skal det være en snarvei til et forhåndsutfylt skjema i billetteringsfanen?

## Hypotheses and assumptions
A list of hypotheses and assumptions we have made about the user or the proposed solution.

## Proposed solution
A coarse description of a proposed solution, that may include wireframes and graphic design.

**Comment by vidtil** [comment]
Dekkes av https://github.com/AtB-AS/mittatb-app/issues/1117
