### ISSUE TITLE
Reisesøk v2 - ikke vise umulige reisesforslag ved ankomst før

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#2194]
## Beskrivelse ##
Når man velger ankomst før litt frem i tid vil det komme reiseforslag med avganger som allerede har passert. Disse er da per definisjon umulig å gjennomføre. [Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1645019413011059) diskusjon gikk videre til å høre med [Entur](https://mittatb.slack.com/archives/CHLDG8C30/p1645043022079889). De bekrefter at det beste er å filtrere ut disse på klientsiden siden man kan være trygg på at videre lasting av forslag kun vil ligge bakover i tid.

@gorandalum spør Entur
> Er det slik at man trygt kan se på avgangstid på de returnerte reiseforslagene for å avgjøre om det er verdt å paginere videre bakover vha. previousPageCursor? Altså hvis man kl. 1500 søker etter avganger med ankomst kl. 1700, og ett av de returnerte reiseforslagene har avgang 14:55, så er det ingen vits for brukeren å paginere bakover siden det ikke kommer til å være noen reiseforslag med avgang etter 1500 på forrige side?

Svar fra Entur
> paginering bakover vil da hente frem flere forslag som er tilbake i tid, så er liten vits i det slik jeg forstår deres ønske om å ikke vise reiser som allerede har forlatt avangsstedet. Alternativet er da å ha en knapp som trigger pagineringen, men med litt måling vil vel kun en lite promille trykke på den 

## Video ##

https://user-images.githubusercontent.com/5812433/154654213-ed4228e6-71ca-48d9-b512-f590b521a326.mp4

https://user-images.githubusercontent.com/5812433/154654254-d2503153-6101-44b8-a1ca-8f9a9f6ce20e.mp4

## Foreslått løsning 

- Gjennomstreking av tidspunkt på passerte reiseforslag
- Endre bakgrunnsfarge

![Outdated travel](https://user-images.githubusercontent.com/8980523/158363799-ef8b3c4f-5b72-4701-972e-0a629fa48575.png)

**Comment by tormoseng** [comment]
Kommentar fra @cbrevik: Vil det være hensiktsmessig å fortsatt vise avganger som har passert?

**Comment by mikaelbr** [comment]
Her må det og tas hensyn til om det er utelukkende gange
![Screenshot 2022-03-18 at 16 11 54](https://user-images.githubusercontent.com/606374/159029506-297c8acd-462d-494c-be63-3d74d5b4112c.png)

**Comment by gorandalum** [comment]
Dette må fikses. Sparr litt med Hilde om nødvendig @rosvik. Kanskje denne gjennomstrykingen kun behøver å komme hvis man har søkt med ankomsttidspunkt? 🤔

**Comment by rosvik** [comment]
Det kan oppleves som om gjennomstreking fungerer litt forskjellig mellom søk med tidspunkt "Nå", "Ankomst" og "Avgang". (Men i bunn å grunn strekes det alltid gjennom de turene som starter i fortiden)

- Søk på **Nå**: Her skal i utgangspunktet ingenting bli gjennomstreket, men hvis man lar forslagene stå oppe i noen minutter kan flere forslag bli utdatert, og også gjennomstreket. Det er også en bug med at man kan man få opp gangeforslag som begynner bare noen sekunder i fortiden, slik at de markeres som utdatert. 
- Søk på **Avgang**: Her er det mulig å gjøre søk på tidspunkt tilbake i tid, slik at man får forslag som allerede har passert. Disse blir gjennomstreket.
- Søk på **Ankomst**: Her får man forslag på turer som ankommer før et tidspunkt. Hvis det er kort tid til ankomsttidspunktet, kan noen av disse forslagene begynne i fortiden, så disse steker vi gjennom. 

Hovedproblemet her er at gåturer man får foreslått når man søker på "Nå", ikke bør vises som utdaterte, bare fordi starttidspunktet har passert. Det er mulig å ha gåturer som unntak, ved å enten streke gjennom dem eller kontinuerlig holde de oppdatert med nytt tidspunkt. Alternativt kan man bare skru av gjennomstreking for alle søk med tidspunkt "Nå".

**Avklarte med @strombraaten at løsning nå er at vi skrur av gjennomstreking for søk på "Nå".**

**Comment by tormoseng** [comment]
@rosvik Supert dett! Men jeg kunne ønsket meg at det kunne blitt lest opp noe om at turen er "ferdig" el.lign på skjermleser. Slik jeg hører det nå er det ingen forskjell i opplesningen når ting er gjennomstreket.

**Comment by tormoseng** [comment]
Tror forøvrig at vi _burde_ hatt noe skjermleserstøtte her siden gjennomstreking betyr noe visuelt som ikke gjenspeiles med skjermleser.

**Comment by tormoseng** [comment]
Skjermleser testet OK
