### ISSUE TITLE
Nullstilling av reisesøk

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#2201]
## Origin

Etter oppsøkende brukertest på gata (aka geriljatest) så lærte vi om ønsket om å nullstille et reisesøk, enten fordi du søkte feil, eller om du skal gjøre et nytt søk.

**Også nevnt på intercom:**

> _Når jeg har gjort et reisesøk og ønsket å gjøre et nytt hadde det vært enkelt å kunne trykke på reisesøkikonet nede til venstre for så å komme tilbake til åpningssiden med reisesøk - denne er mye lettere å taste inn fra enn å måtte flytte fingrene opp til toppen av skjermen. Den gir meg også direkte tilgang til mine favoritter_

## Motivation

Etter å ha utført et reisesøk har man behov for å kunne nullstille dette. I dag skjer dette via tap på AtB-logoen men dette er ikke et etablert pattern. Konvensjonen er at man nullstiller ved å trykke på hovedelementet i navigasjonen på nytt. 

Sånn sett vil det fungere på samme måte som Avganger gjør i dag (ny visning). Hvis du er inne på én spesifikk holdeplass kan du alltids trykke på Avganger fra menylinja for å komme deg tilbake og se hvilke andre holdeplasser som er i nærheten.

## Proposed solution

- Når man har utført et reisesøk og man står på reisesøk-fanen kan man trykke på "Reisesøk" i hovednavigasjonen for å nullstille søket (_se illustrasjonen under_)
- Nullstill søk fjernes fra AtB-logo

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/72508979/159229917-9235d2af-5473-480d-bb4d-815b1450d561.png">

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by strombraaten** [comment]
Jepp! Skal se på det imorra, @hildeor 👍

**Comment by strombraaten** [comment]
Spørsmål, @hildeor:

Om du er i et reisesøk, som det her:
![IMG_3084](https://user-images.githubusercontent.com/72508979/155493392-f346c58f-601e-44dc-af70-9ab3fa217dbc.PNG)

Og du trykker på Reisesøk på navigasjonslinja i bunn. 
**Skal du da gå videre til bildet 1 eller 2 nedenfor her?**

1:
![IMG_3085](https://user-images.githubusercontent.com/72508979/155493498-c273e980-c60d-4d5b-9bf0-e55a4aa9cd3d.PNG)


2:
![IMG_3086](https://user-images.githubusercontent.com/72508979/155493540-c4ad6ee5-961a-4898-ba13-33406a2f8f28.PNG)

Personlig hadde jeg nok forventa å komme til bilde 2, siden man i det tilfelle vil forbli på reisesøket. Problemet er bare at vi da har begrensa det til et sted du skal **til**, uten muligheten til å velge **fra**.

**Comment by hildeor** [comment]
Jeg forventer bilde 1 fordi jeg vil resette/nullstille hele søket. Hvis du går til nr 2, er som du sier at vi må gjøre en antagelse om at du først og fremst vil endre "fra". Tror potensielt det å gå til nr 1 er mer etablert pattern? (kan sikkert researches med veldig enkel forskning 🤓 )

**Comment by strombraaten** [comment]
> Jeg forventer bilde 1 fordi jeg vil resette/nullstille hele søket. Hvis du går til nr 2, er som du sier at vi må gjøre en antagelse om at du først og fremst vil endre "fra". Tror potensielt det å gå til nr 1 er mer etablert pattern? (kan sikkert researches med veldig enkel forskning 🤓 )

Mener du ikke vi gjør en antagelse om at du vil endre "til"? Det føles veldig flisespikkete, men akkurat i denne konteksten utgjorde det en viss forskjell, føler jeg.

Skulle vi starta med å bare høre litt internt i teamet, og se hva de sier?

**Comment by hildeor** [comment]
Nei fordi hvis vi resetter til bilde så har vi ikke forhåndsvalgt noe felt. 
Jeg mener det er dette som vil være mest i tråd med etablerte patterns. Hvis du tester endel apper (Slack, Instagram, Finn, Spotify osv) så er dette standard oppførsel når man tapper nåværende aktivt menyelement for 2. gang.

**Comment by mikaelbr** [comment]
Enig med @hildeor ang tabbar her. Det er i alle fall på iOS et etablert pattern. Men jeg er usikker på om det er forventet mønster på Android?

**Comment by strombraaten** [comment]
Godt poeng 👍 Da oppdaterer jeg beskrivelsen her så det blir tydeligere hva som skal gjøres.

**Comment by mikaelbr** [comment]
Se også kommentar her @strombraaten https://github.com/AtB-AS/mittatb-app/issues/2290#issuecomment-1073564980

**Comment by tormoseng** [comment]
Testet OK i staging
