### ISSUE TITLE
Endre navn på "Mitt AtB" til "Min profil"

### ISSUE THREAD

**Issue by strombraaten** [AtB-AS/mittatb-app#2206]
## Origin

_Referer til det jeg skreiv på Slack tidligere:_

Når vi har jobba med språket på onboardinga til token toggle nå, sammen med Julia og Hilde fra Marked, så har vi også kommet inn på navnet til Mitt AtB-fanen. Det vi har snakka om er å endre det til noe mer gjenkjennbart for brukeren, som “Min profil”.
Grunnen til det er blant annet basert på tilbakemeldingene vi fikk på brukertestene av den nye billettkjøpvisninga, for da var det flere som misforstod hva de ville finne på Mitt AtB (spesielt blant eldre).

## Proposed solution

- [ ] Endre alt som refererer til "Mitt AtB" til "Min profil", **dette gjelder da både på nettbutikk og i appen**

## Mer bakgrunn

Magnus har også vært god til å minne vårs på at navnet/konseptet hadde noen langsiktige, strategiske røtter ved seg. Og at det skulle på sikt kunne knyttes opp mot alle slags mobilitetstjenester i Trøndelag, hvor brukeren kan ta med alt av personlige opplysninger og preferanser på tvers av tjenester. Det har vært tanken. Vi er jo ikke der nå, og etter noen diskusjoner landa vi heller på at vi kan komme tilbake til hva det konseptet burde hete når det er mer relevant.

Samtidig er det nok et begrep som har vært et arbeidsnavn opp gjennom årene, og ikke like gjennomarbeida som et navn som brukes ut mot kundene. Derfor tenker vi at Min profil er bedre å bruke inntil videre, og så kan vi heller ta en ny runde på hva det skal hete når vi kommer dit at det er et konsept med mer innhold vi kan snakke om til kundene.

**Comment by hildeor** [comment]
Obs: GJelder både nettbutikk og app

**Comment by strombraaten** [comment]
> Obs: GJelder både nettbutikk og app

Jepp! Bra du nevner det. Oppdaterte beskrivelsen litt nå.

**Comment by strombraaten** [comment]
> Blir det "My profile" på engelsk?

Jepp 👍
