### ISSUE TITLE
[Feature] Show valid travel rights in nearby tab

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#221]
## Origin
Links to received feedback, user research or other findings.

## Motivation
A short description of what user needs or business goals this feature will solve.

En bruker vil ved flere anledninger ha behov for se informasjon om sine gyldige reiserettigheter. For raske reiseoppslag, for eksempel for å planlegge en returreise mens den nåværende billetten fremdeles er gyldig. Kan løses ved å markere reiser som er innenfor billettene gyldighetsperiode i Nearby-fanen. 

## Hypotheses and assumptions
A list of hypotheses and assumptions we have made about the user or the proposed solution.

## Proposed solution
A coarse description of a proposed solution, that may include wireframes and graphic design.

**Comment by hildeor** [comment]
Løst ved billett-fanen.
