### ISSUE TITLE
QA v1.17: MobToken fase 2, reisesøk og tilbakemld.komponenten

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/mittatb-app#2211]
## Innledning

En oversikt over saker som må testes i QA for v1.17, og observasjoner gjort under testing av v1.17.

Merk av for hvert underpunkt når en sak er fikset / tilgjengelig i test / testet. Selve saken sjekkes ut når alle underpunkter er ferdige.

## Tidligere versjoner
- #2089 
- #2112 

## Observasjoner som må tas for v1.17

- [x] Oversettinger av ulike feil-tilstander og annet små-stæsj ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1647425273895479))
    - [x] Fikses fortløpende av @monopoint 
    - [x] Testet OK
- [x]  Kjøp av billett: Man får opp melding om at man må bruke t:kort for reisen, selv om et mobiltoken er satt som reisebevis
     @monopoint 
    - [x] Fikset ([PR](https://github.com/AtB-AS/mittatb-app/pull/2291))
    - [x] Testet OK
- [x]  Oppdatere tekst rundt "Ikke tillatt å generere QR-kode" ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646127650059829))
 @monopoint
    - [x] Fikses av #2279 
    - [x] Fikset
    - [x] Testet OK
- [x] Skjul teksten "Du kan ikke få inspisert billetten på denne enheten" ([Slack](https://mittatb.slack.com/archives/C02EEG7D8EL/p1646295829471289)) - Løses i #2255 
    @monopoint 
    - [x] Fikset ([PR](https://github.com/AtB-AS/mittatb-app/pull/2287))
    - [x] Testet OK
- [x] Meldingsboks om samarbeidsbilletten forsvinner utenfor scrollområde ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646128463575489))
	- [x] @rosvik https://github.com/AtB-AS/mittatb-app/pull/2232
    - [x] Fikset
    - [x] Testet OK
- [x] Ulike farger på "Ikke vis i kontroll" ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646129545400579))
	- [x] @rosvik #2246 
		- Fikk til å gjenskape problemet ved å logge inn på en bruker med ikke-inspiserbare billetter, men det ble riktig igjen etter restart av appen. Dette blir fikset i denne PR-en 
    - [x] Fikset
    - [x] Testet OK
- [x] Styling av t:kortnummer x'ene ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646134161002599))
	- [x] @rosvik https://github.com/AtB-AS/mittatb-app/pull/2237
    - [x] Fikset
    - [x] Testet OK
- [x] Hvordan skal vi - eller skal vi - håndtere bytte mellom t:kort og mobil-token som bærer når nettbutikken (og kundeservice) ikke har noen mekanismer for å håndtere sjonglering av tokens og rettigheter ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646138665220979?thread_ts=1646134192.473539&cid=C0116FMPX4Y))
    - @jahnrohme initierer et møte med Entur om hvordan vi bør håndtere dette i Sørvis. App og nettbutikk har vi kontroll på selv, og vil bli fikset når token-toggle kommer ut.
    - Eventuelle feilsituasjoner kan fikses gjennom å fjerne/sette inspeksjons-action på riktig token(s) i Backoffice.
- [x] Reisebevis bør skjules fra Utløpte billetter-visningen ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646142880981629))
	- [x] @rosvik #2258
    - [x] Fikset
    - [x] Testet OK
- [x] Infoboks om samarbeidsbilletten bør skjules fra Utløpte billetter-visningen ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646142994179249))
    - [x] @rosvik #2232
    - [x] Fikset
    - [x] Testet OK
- [x] Ikon og melding om at billetten ikke kan inspiseres bør skjules fra Utløpte billetter-visningen ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646142994179249))
    - [x] @rosvik #2254 
    - [x] Fikset
    - [x] Testet OK
- Token-toggle: Device name blir vist som "undefined" i listen over mobiler ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646128885886489))
    - [x] @rosvik Legger til fallback til "Enhet uten navn", til vi klarer å gjenskape og forbedre det #2302   
    - [x] Fikset
    - [x] Testet OK
- [x] Reisesøk v2 viser unødvendig gå-etapper når man søker fra og til holdeplasser
    - Er beskrevet i sak #2296 
    - [x] Testet OK

## Andre observasjoner fra QA som ikke trenger å tas i v1.17

- Tidligere valgt mobil fremstår som valgt i listen over devices, selv om du faktisk har t:kort som valgt. [Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646743009110859)
    - Fikset
    - Testet
- #2419
    - Fikset
    - Testet OK
- [x] Hvis man har flere devicer registrert så forsvinner lagre-knappen hvis man scroller ned til denne knappen ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646662437063149))
    - Fikses av #2280 
    - [x] Fikset
    - [x] Testet OK
- Flere tokens tilknyttet samme device listes opp under mulige toggle-alternativer ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646136517019389))
    - Denne er knyttet til token-toggle, men må undersøkes om den kan "forstyrre" vanlig flyt.
    - "Fikses" av å legge på dato for når token ble lagt til i #2295 
    - Testet OK
- [x] Hvit skrift på fyllt grønn sone-ikon i dark mode. Skal være svart skrift ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646659125819179?thread_ts=1646129545.400579&cid=C0116FMPX4Y))
	- [x] @rosvik Fikses i #2306
	- [x] Testet OK

## Saker som må testes i Staging

- [x] Mobile token
    - [x] Inspeksjonsrettighet settes på valgt device
    - [x] QR-kode er dynamisk og kontrollerbar
    - [x] Kan toggle mellom ulike devicer + t:kort 
    - [x] Feilsituasjoner håndteres
    - [x] Språk er riktig oversatt
    - [x] Re-attestering fungerer
- [x] Reisesøk
    - Reisesøk v2 som eneste reisesøk
    - Sjekk saker i https://github.com/AtB-AS/leveranser/issues/4
    - Sjekk "resett-beskrivelse" under akseptansekriteriene i #2201 
- [x] Avganger
    - [x] Enkel regresjonstest av Avganger v1
    - [x] Enkel regresjonstest av Avganger v2
- ~~Tilbakemeldingskomponenten~~ > Versjon 1.18
    - ~~Grundig test basert på scenarier i #2345~~

## Saker som må testes i Prod (a.k.a Testflight/Internal)

- [x] Mobile token
    - Inspeksjonsrettighet settes på valgt device
    - QR-kode er dynamisk og kontrollerbar
    - Kan toggle mellom ulike devicer + t:kort
    - Anonym bruker uten mobToken får papirQR
    - Innlogget bruker uten t:kort får mobil som token (første innlogging)
    - Innlogget bruker med t:kort får t:kort som token (første innlogging)
    - Re-attestering fungerer
- [x] Reisesøk
    - Enkel regresjonstest med fokus på sakene i https://github.com/AtB-AS/leveranser/issues/4 og "resett-funksjonalitet" beskrevet i #2201 
- [x] Avganger
    - Enkel regresjonstest v1 og v2
- [x] Tilbakemeldingskomponenten
    - Denne skal ikke vises i første omgang s.a. man får ikke testet denne her.
- [x] Billettkjøp
    - Regresjonstest av enkeltbillett og periodebillett med/uten lagret betalingskort + Vipps

**Comment by jahnrohme** [comment]
Kan vi få med https://github.com/AtB-AS/mittatb-app/issues/2206 i denne?

**Comment by tormoseng** [comment]
@jahnrohme Noe å vurdere, i hvertfall, til token-toggle skal ut https://mittatb.slack.com/archives/C0116FMPX4Y/p1646136790508289

**Comment by mikaelbr** [comment]
Skal denne tagges som v1.17?

**Comment by tormoseng** [comment]
> Skal denne tagges som v1.17?

Bra spørsmål. Veeeldig knytta til 1.17, men ingen kode som leveres i 1.17. Hva synes du?

**Comment by tormoseng** [comment]
Testet ferdig i Prod på iOS + Android!
