### ISSUE TITLE
[Feature] Notify the user if a payment method needs to be updated

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#222]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

Vi ønsker å gi brukeren en trygghet om at han alltid har et gyldig betalingsmiddel registrert i appen. En bruker skal slippe å legge inn nye kredittkortdetaljer når han har dårlig tid, for eksempel rett før han går innpå bussen og skal kjøpe en enkeltbillett.

Har vi i praksis tilgang til informasjon om betalingsmiddelet er gyldig, eller er dette noe som håndteres hos andre aktører?

Hvor aggressivt skal varselet være? Skal det for eksempel vises første gang en bruker åpner appen, eller skal det først vises etter at brukeren har gjennomført et billettkjøp?

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

**Comment by gorandalum** [comment]
Lukker da det fortsatt ikke er implementert lagring av bankkort i app. Dette kan tas inn i saken hvor vi implementerer mulighet for slik lagring.
