### ISSUE TITLE
Favoritter som er holdeplasser navigerer direkte til holdeplassen 

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#2227]
## Origin

Dette var opprinnelig tenkt måte å fungere på, men har ikke blitt prioritert enda.

## Motivation

En favoritt er en snarvei for å raskt kunne komme seg til et forhåndsdefinert sted eller holdeplass. I Avganger 2.0 er favorittene tilgjengelig fra landingssiden, og det raskeste for å komme seg inn på en favoritt er da at trykk på favoritten tar deg direkte til avgangssiden til den favoritten.

## Proposed solution

- [ ] Trykk på en favoritt som er definert som en holdeplass navigerer direkte til avganger for den holdeplassen
- [ ] Ved søk på en holdeplass, og trykk på en holdeplass i resultatlisten navigerer man direkte til avganger for den holdeplassen

Dette var tidligere implementert med en useEffect som sjekket om søk var en holdeplass (se 26a1ffa839a430278162ae2b9704b2b8e3eeee98), men viste seg å være litt buggy i praksis, ved at det trigget navigering når man ikke forventet det. I tillegg til krevde det ferdig innlasting av holdeplassdata før man navigerte (hovedsaklig for å få tak i info om plattformer), slik at det ble litt delay mellom trykk og navigering. 

Istedet bør navigeringen skje øyeblikkelig, og så håndterer `PlaceScreen` innlasting av holdeplass-data. Dette krever kanskje oppdatering av BFF, og kan potensielt løses med samme endepunkt som brukes i favoritt-fanen (#2013 / #2427)

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by tormoseng** [comment]
Testet OK.

Fant en UU-ting som ikke er relatert til denne saken direkte. Egen sak i #2493
