### ISSUE TITLE
Oppdateringer på språk rundt reisebevis

### ISSUE THREAD

**Issue by strombraaten** [AtB-AS/mittatb-app#2249]
Språkendringene jeg har sett på er basert på Billettvisning og Onboarding (fra skissene i figma)

### Arbeidsfiler
Den engelske oversettelsen ligger til høyre for den norske.

- [Billettvisning](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/?node-id=7207%3A57460) 
- [Onboarding](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/?node-id=7059%3A55786)

### Viktige ting å merke seg

- [ ] "Request receipt" endres til "Send receipt"
       - Gjerne sjekk at det er konsekvent andre steder og
- [ ] Gått over fra å snakke om "mobile phone" til "phone", etter en diskusjon med Magnus, Hilde, og Julia
       - Endres kun på engelsk. Snakker fremdeles om "mobil" på norsk.

![image](https://user-images.githubusercontent.com/72508979/156386245-1dd8717b-50c6-441b-8562-69c8c3822129.png)

![image](https://user-images.githubusercontent.com/72508979/156388632-250b464e-735f-4dcc-8d4b-32cc9c786c20.png)

![image](https://user-images.githubusercontent.com/72508979/156389286-6e3818a5-ab25-4121-83ba-3f7e4075fd3e.png)

![image](https://user-images.githubusercontent.com/72508979/156389343-6ea83c18-af61-455b-abc5-308f0c1d89b7.png)

![image](https://user-images.githubusercontent.com/72508979/156389392-422c07e5-6d32-44c3-8902-a4fd9a1d85e7.png)

**Comment by monopoint** [comment]
legger også oppdatering av FAQ som del av denne:
https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App-1.1?node-id=8200%3A71825

**Comment by monopoint** [comment]
[ x] - Ticket Info Box (tickets / token toggle)

**Comment by monopoint** [comment]
Mangler engelsk oversettelser på disse:
![image](https://user-images.githubusercontent.com/1464594/157244799-521439ef-4152-4fa1-8eb4-d47b9d82598a.png)

**Comment by JuliaOppegard** [comment]
Case 1:
Unable to retrieve information about phone/t:card 
Tickets must be used on either a t:card or phone, but right now we are unable to find where the ticket is in use. Check that you have internet access. 
Retry

Case 2:
We can not find any t:cards or phones associated with your profile 
Check that you have internet access. If you are not online, the app will try again once you are connected. If the problem persists, please contact AtB service center. 

Case 3:
Choose where you want to use your tickets
 Tickets must be used on either a t:card or a phone, and it looks like you haven't chosen one. Go to My profile> switch between phone/t:card to select.

**Comment by tormoseng** [comment]
Da er språkendringene verifisert så langt jeg kan se. OK!
