### ISSUE TITLE
[Feature] View expired tickets

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#225]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

**Comment by hildeor** [comment]
Already handled.
