### ISSUE TITLE
Nattbillett

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#2259]
Konseptuelt trenger vi avklaringer på:

- Kjøpstidsrom
    - Fra EnTur sin side er det mulig å kjøpe billettene 90 dager i forkant, men i praksis er ikke det nødvendig for brukeren
- Lengde på gyldighet
    - 90 min ✅
- Navn på "soner" (Natt 1, Natt 2, Natt 3)
- Knytning mellom oppsatte avganger og kjøpstidsrom

**Comment by strombraaten** [comment]
### Oppdatering
1. **Kjøpstidsrom**
    - Kjøpstidsrommet er satt til 90 dager før avreise (standard for de fleste billettproduktene vi har registrert hos EnTur)
    - Det vil også si at plattform står fritt til å definere kjøpstidsrommet ut fra våre ønsker innenfor de 90 dagene
2. **Lengde på gyldighet**
    - Venter på svar fra EnTur her, men vi undersøker muligheten om å låse gyldighetsperioden til et fast tidsrom (00:30-04:00) som da vil omfatte alle nattbuss/trikker, i stedet for 90 minutter f. Eks som er gyldigheten som er definert hos EnTur i dag.
    - Om vi får tommel opp på den endringen riktignok så åpner det for noen muligheter som du kan se på bildet under.
3. **Navn på "soner" (Natt 1, Natt 2, Natt 3)**
    - Venter på statistikk fra Markedsinnsikt for å kunne ta en avgjørelse om hvor mange brukere som går på bussen utafor Trondheim (nattbussene går **kun fra Trondheim**, og ikke **til**, med mindre det er en konsert som er satt opp i Stjørdal f. Eks)
    - Natt 1 er prissatt ut fra at du skal reise innad 1 kommune, men siden de aller fleste reisene skjer innafor Trondheim (faktisk 91% ut fra billettstatistikken), og ikke Orkdal eller Melhus osv., så er den begrensa til å kun gjelde for Trondheim kommune. Så ikke en hvilken som helst kommune. 
    - Natt 2 gjelder derimot reise mellom 2 kommuner
    - Natt 3 gjelder reiser mellom 3 kommuner
    - Her er det også en liten "klinsj" i form av at navnet på billetten skal vises til to veldig ulike brukergrupper, nemlig potensielt sett bedugga reisende som skal ha kjøpe seg en billett, og sjåfører som selger billettene på bussen gjennom MTen. Natt 1/2/3 er godt innarbeida blant sjåførene, men gir mindre mening for de reisende.
5. **Knytning mellom oppsatte avganger og kjøpstidsrom**
    - Den her dekkes vel under punkt 1 og 2

For å få noen innspill, eller eventuelt unngå uforutsette fallgruver så har jeg tatt kontakt med Rune fra NFK for å høre hvordan de har gjort det med nattbilletten sin.

![Skjermbilde 2022-03-31 kl  14 02 06](https://user-images.githubusercontent.com/72508979/161050401-7eb8eea9-8d2b-44ab-a421-ead19d546c15.png)

**Comment by strombraaten** [comment]
Hadde en prat med NFK nå, og da var det to ting som var nyttig å vite:
1. De har kun nattbuss i Bodø, så de krysser ikke flere kommunegrenser som vi gjør
2. De har ikke dedikerte busslinjer som er satt opp for nattbuss, sånn som vi har i Trondheim. Om jeg har forstått riktig. Det er altså de samme linjenumrene som kjører på natta og på dagen, bare at det er en "litt annen turnummerering"

Det vil si at dersom vi bruker selve nattbusslinjene her i Trondheim til å dedikere parametre, for å eventuelt begrense noe i appen, så vil ikke det være overførbart til Nordland på samme måte. Det her rører innom noe vi prata om i møtet i går @havwig, så inkluderer deg der bare så du er informert.

De bruker jo også WTW som leverandør, så nattbuss-produktet ser likt ut:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/72508979/161961511-5af5cd20-7e0a-40ad-9224-e69083fdf39e.png">

**Comment by strombraaten** [comment]
Diskuterte konseptet med kundesenteret, og de kom med veldig nyttig tilbakemelding. Blant annet om at målgruppa for nattbillett vil ha særdeles god nytte av et pushvarsel som sier noe om når billetten snart blir gyldig, dersom man har valgt "oppstart seinere" ved billettkjøp.

**Comment by strombraaten** [comment]
La rapporten om det [innsiktsarbeidet her på Sharepoint](https://atbno.sharepoint.com/:b:/s/kompasset/EdvEMV_UDdBCsOTdm1GgBGEBSmaKy8MbufnMXSrlDpjHcQ?e=DVLpD0), for de som er interessert. Har begynt å koke det ned til konkrete designendringer, så denne oppgaven kan lukkes for denne omgangen, også vurderer vi heller om det er behov for en egen sak på designendringene, eller om de er så små at det ikke er noe vits i å lage saken.
