### ISSUE TITLE
Fjerne reisesøk v1

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#2260]
Føler oss nå trygge på at vi kan gå over til OTP2 og JP3 for Reisesøket.

- [x] Rydde bort OTP1-reisesøk
- [x] Gjøre OTP2-reisesøk tilgjengelig for alle
- [x] ~~Fjerne e2e-tester mot OTP 1 og toggling.~~ Dette blir gjot i 1.18 på https://github.com/AtB-AS/mittatb-app/pull/2390

**Comment by tormoseng** [comment]
Denne er OK! At alle kodelinjer tilknyttet v1 er borte er del av review.
