### ISSUE TITLE
Oppdatere informasjon rundt togbillett i app 

### ISSUE THREAD

**Issue by jahnrohme** [AtB-AS/mittatb-app#2266]
## Origin

![image](https://user-images.githubusercontent.com/87697374/156712466-9f17a926-5c0a-43c6-83d4-3de5beffd85b.png)

Meldingen sier at man må kjøpe en annen billett, og som ikke er tilgjengelig i appen. Nå som samarbeidsbilletten er ute, må meldingen endres.

Siden det er komplisert å evaluere soner og hvilke operatører som inngår i samarbeidsbilletten gjør vi her en inkrementell tilnærming, og utsetter den perfekte løsningen til litt senere.

Per i dag viser vi Gul melding hvis reisen inneholder en annen operatør enn AtB.
Endringen som skal gjøres i denne saken er å legge til tekst hvis Tog er involvert i reisen.

ToDo:
- [x] Logikk for når den gule meldingen skal vises forblir som før
- [x] Sjekk om resien innbefatter Tog, i så fall skal denne teksten legges til:
  - Med enkelt- og periodebillett for sone A fra AtB kan du reise med tog i sonen.
  - With a single or periodic ticket for zone A from AtB, you can travel by train in the zone.

## Implmentasjon

![image](https://user-images.githubusercontent.com/1464594/160110092-9322739d-7e62-4df1-aa2d-71cf4908258f.png)

Skrev om den biten som tester kort ventetid, for å fjerne en god porsjon spaghetti.

## Test
Siden det er gjort en del omskrivinger på biten som sjekker kort ventetid, er det lagt til enhetstester som tester dette.
Testene kjøres ved `yarn test`.
Ellers kan både reisesøk og avganger testes ganske greit, der utvidet gul melding skal vises hvis reisen inneholder tog.

**Comment by jahnrohme** [comment]
@JuliaOppegard Har du forslag til tekst her? :)

**Comment by JuliaOppegard** [comment]
Det har jeg nok :D Er det mulig å differensiere tekst ut fra om søket er i sone A eller ikke, eller blir en tekst som vises over alt?

**Comment by jahnrohme** [comment]
@rosvik @gorandalum kunne dere svart på spørsmålet til Jules? ☝️

**Comment by gorandalum** [comment]
Jeg tror det blir komplisert å begynne å bruke logikk basert på soner her. Både at jeg ikke vet hvor lett teknisk det er å få tak i soneinformasjon, samt at jeg ser for meg at det blir ganske raskt komplisert logikk hvor man må ta høyde for hvor man starter, stopper, bytter, osv. under hele reisen.

Det vi kan basere logikken til teksten på er i hovedsak hvilket selskap (AtB, Fram, SJ, ..), transportmåte (buss, trikk, tog, ..) og eventuelt også linjenummer.

**Comment by JuliaOppegard** [comment]
I så tilfelle tror jeg det er smart å i alle fall ha med tog-logikken slik at meldingen kan bli noe sånt som den er i dag, men med en tilleggssetning på tog. Min umiddelbare tanke:
Med enkelt- og periodebillett for sone A fra AtB kan du reise med tog i sonen.
Jeg tar GJERNE innspill fra f.eks, @jahnrohme :D

**Comment by toretefre** [comment]
Inkluderer "tog" regiontoget til Bodø på strekningene Trondheim S - Stjørdal / Trondheim Lufthavn?

**Comment by jahnrohme** [comment]
Bra catcha @toretefre. 
Husker vi snakka om dette i oppstartsmøtet for noen uker siden, om Nordlandsbanen skulle være med. Vi stilte spørsmålstegn til hvorfor dette ikke skulle gjelde, men det ble ikke landet på noe annet enn av SJ skulle sjekke ut dette. Entur har ikke lagt det inn i så fall. Om jeg husker riktig så var det noe med plassbestilling som var problematisk. 
Ballen ligger sånn sett hos SJ, og jeg tenker ikke vi trenger å gjøre noe her.

**Comment by JuliaOppegard** [comment]
Men hvordan blir da dette i vår app? Da kan det godt hende vi må tenke en gang til på infoen vår så lenge det er noen togavganger vi ikke selger billett til. Det vil påvirke både teksten som står på billetten og info om billettering som vises i reisesøk.

**Comment by monopoint** [comment]
Det har kommet en del diskujson om hvordan denne oppgaven skal løses og mye av det gjelder ikke for denne sakken, som bare er en inkrementell justering.
Diskusjon om endelig løsning bør flyttes over til en ny sak.

**Comment by tormoseng** [comment]
Testet OK i staging
