### ISSUE TITLE
[Feature] Notify a user if a period ticket needs to be extended

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#227]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

**Comment by pettersuul** [comment]
Håndteres under #1109
