### ISSUE TITLE
[Improvement] Tydeliggjøre i appen hvor man finner avviksinformasjon

### ISSUE THREAD

**Issue by jahnrohme** [AtB-AS/mittatb-app#2290]
## Mål
Tydeliggjøre hvor man finner informasjon om driftsavvik.

## Origin
Grethe og AtBs styre.
Et gjentakende emne er at kundene ikke mottar gode nok avviksmeldinger dersom noe uforutsett oppstår i busstrafikken.

## Behov
- Kunder har behov for å vite om det er avvik på deres reiserute
- Avvik kan oppstå “når som helst” og kundene er derfor avhengig av å bli pushet denne informasjonen i riktig kontekst

**Merk**: Lenke til atb.no/driftsavvik vil ikke fullstendig kunne dekke disse behovene, da dette legger ansvaret tilbake på kundene om at de selv må oppsøke informasjonen før de skal ut og reise, men det gjør informasjonen litt lettere tilgjengelig for å oppsøke selv. 

## Hensikt
Det pågår et prosjekt utenfor AMP for å forsøke å forbedre avviksmeldingene.
Et lavthengende tiltak kan være å finne alternative måter kundene får tilgang til https://www.atb.no/driftsavvik/

## Løsning

Ser tre mulige løsninger her. **Anbefaler en kombinasjon av 1 og 2**. Hvis det skulle være mange avvik som påvirker store deler av trafikken burde man vurdere bruk av meldingsboks for å informere kundene på "push"-vis. 
I normale driftssituasjoner med enkelte avvik kan det vurderes som tilstrekkelig med alt 2. 

**1: Manuell bruk av meldingsboks**
Manuell rutine for å publisere hvis det er store avvik som påvirker veldig mange. Må også manuelt fjernes.
<img width="418" alt="Skjermbilde 2022-03-14 kl  08 05 08" src="https://user-images.githubusercontent.com/8980523/158121491-41c58648-025f-49c4-bdf7-794adcf2413e.png">

**2: Knapp fra både Reisesøk og avganger som viser hvor du kan finne driftsavvik**
Går på bekostning av nullstilling av reisesøk som nå aktiveres av AtB-logoen, men dette er heller ikke foretrukket atferd (#2201) og disse to sakene må endres i samsvar med hverandre. 
Knapp med ikon øverst i venstre hjørne. 
<img width="1222" alt="Skjermbilde 2022-03-14 kl  08 05 18" src="https://user-images.githubusercontent.com/8980523/158121507-927b5e8d-b7dc-4a57-909d-e47659265724.png">

**3. Lenke fra Min profil**
Tror denne blir litt for vanskelig å finne.
<img width="332" alt="Skjermbilde 2022-03-11 kl  09 40 32" src="https://user-images.githubusercontent.com/8980523/157832796-6b9f81d8-f54b-4880-9b38-c1e2900cbfdc.png">

## Tekster

**Norsk**
Overskrift: Driftsavvik
Body: Oversikt over endringer, forsinkelser og avvik finner du på atb.no:
Knappetekst: atb.no/driftsavvik (åpnes i nettleser)

**Engelsk**
Overskrift: Service disruptions
Body: Get an overview of changes, delays and service disruptions at atb.no (Norwegian only):
Knappetekst: atb.no/driftsavvik (opens in browser)

**Comment by jahnrohme** [comment]
Vi går for alternativ 2

**Comment by mikaelbr** [comment]
Denne oppgaven må som nevnt over her sees i sammenheng med https://github.com/AtB-AS/mittatb-app/issues/2201. Her bryter vi potensielt et etablert mønster med et nytt implisitt mønster som folk ikke kjenner til, så det kan bli noe overgangssmerter her. Men etter å ha diskutert med @hildeor for denne og #2201 så blir løsningen:

- Avviksmeny på reisesøk og avgangsvisning. Ingen logo/knapp på andre visninger.
- Reset-visning flyttes til tabbar og ved klikk flere ganger.

Samtidig vil jeg løfte frem at langsiktig løsning her må være å sammenstille avviksdatagrunnlag og heve kvaliteten på det slik at det ikke er ulike kilder til avviksmeldinger.

**Comment by strombraaten** [comment]
Veldig godt poeng, @mikaelbr. Har inntrykket av at de færreste veit at man kan trykke på logoen for å nullstille, og har fått noen tilbakemeldinger om det tidligere, men det er jo mer en "hunch" enn kvantitativ data foråsirresånn, så jeg skal såklart ikke kimse av et etablert bruksmønster. 

En mulighet hadde jo vært å tipsa brukeren om at man kan nullstille reisesøket ved å trykke på Reisesøk-knappen. På den måten kunne det vært relevant å gjenbruke promptsa fra #1793 (bildet under), hvor det kunne stått f. Eks "Visste du at du kan nullstille reisesøket ditt ved å trykke her", når brukeren faktisk er inni et reisesøk. Eller hva tenker du @hildeor ? Har det vært noen lignende måter å "lære opp" brukeren på tidligere kanskje? 

![image](https://user-images.githubusercontent.com/72508979/159243068-23f687e8-b883-42cb-8d41-41cfb5c35919.png)

**Comment by tormoseng** [comment]
Testet OK i staging
