### ISSUE TITLE
[Feature] Make it possible to choose an earlier route search 

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#232]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

Brukeren har behov for å søke etter den samme reiseruten gjentatte ganger. 

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

Når en bruker skal velge fra-sted, kommer det opp et forslag som inkluderer både fra-sted og til-sted. 

Forslaget inkluderer kan inneholde både stoppesteder, adresser og favoritter.

**Comment by gorandalum** [comment]
Done
