### ISSUE TITLE
[Feature] Appearance and behaviour of place selection

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#233]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

A fast and easy-to-use place selection tool is an important part of the travel assistant, and needs to be user testet and refined.

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

- Users that shares their position, probably wants to use this as their primary place entry.
- Users do not need to see favourites or earlier search results when the search for a new place

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

- Text input:
-- By default not focused
-- Maintains focus if cleared
-- Loses focus if clicked outside or user scrolls in results

- Shortcuts and favorites:
-- Shown if text input is not focused AND empty

- Previous searches:
-- Shown if text input is empty
-- Remove heading if text input is focused

- Search results:
-- Shown if text input is not empty
-- Also contains previous searches

Order of the search results:
- Favourites
- Earlier search results
- Regular results

![image](https://user-images.githubusercontent.com/56530785/92106038-0e82c900-ede4-11ea-9c7a-336da2fef860.png)

**Comment by hildeor** [comment]
@pettersuul Vet du status på denne nå? Er det noe gjenstående arbeid her?

**Comment by pettersuul** [comment]
Tror denne kan lukkes
