### ISSUE TITLE
Visningslogikk tilbakemeldings-komponent

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#2345]
## Origin

Ved implementering av tilbakemeldings-komponenten var det ingen klare retningslinjer for visningslogikk. Det ble gjort et forsøk i #2256, mens denne issuen sikter mot en ny pull request som implementerer mer gjennomtenkte regler som er definert her (med utgangspunkt i Miro-boardet for tilbakemeldingskomponenten).

## Motivation

Denne utvidelsen vil gjøre mulighetene våre for å hente inn data bedre ved at vi treffer brukerne våre på riktig tidspunkt. Vi vil også unngå å irritere brukere unødvendig.

## Hypotheses and assumptions

Det ble gjennomført et møte med Gøran, Simen, Tore og Tor, tirsdag 15. mars, der forutsetninger og krav ble diskutert og delvis nedfelt i et Miro-board.

### Konfigurerbare parametre:

`surveyVersion` Integer
`viewContext` String
`alwaysShow` Boolean
`dismissable` Boolean // Aktuell hvis alwaysShow = false
`gracePeriodDisplayCount` Integer // Aktuell hvis alwaysShow = false
`repromptDisplayCount` Integer // Aktuell hvis alwaysShow = false

### Defaults: 
Gitt at config `surveyVersion` er 1
Gitt at config `gracePeriodDisplayCount` er 0
Gitt at config `repromptDisplayCount` er undefined
Gitt at config `dismissable` er false
Gitt at config `alwaysShow` er false

Gitt at brukeren ikke har svart tidligere
Når brukeren åpner visningen første gang
Så skal komponenten vises

### Testing
<details>
<summary>Scenarioer</summary>

Defaults:
Gitt at config surveyVersion er 1
Gitt at config gracePeriodDisplayCount er 0
Gitt at config repromptDisplayCount er undefined
Gitt at config dismissable er false
Gitt at config alwaysShow er false

Gitt at brukeren ikke har svart tidligere
Når brukeren åpner visningen første gang
Så skal komponenten vises

Gitt at config gracePeriod er 5
Gitt at brukeren ikke har svart tidligere
Når brukeren åpner visningen første gang
Så skal komponenten ikke vises

Gitt at config gracePeriod er 5
Gitt at brukeren ikke har svart tidligere
Når brukeren åpner visningen for 6. gang
Så skal komponenten vises

Gitt at config dismissable er false
Gitt at brukeren ikke har svart tidligere
Når brukeren åpner visningen for første gang
Så skal komponenten vises
Så skal komponenten ikke kunne krysses ut

Gitt at config dismissable er true
Gitt at brukeren ikke har svart tidligere
Når brukeren åpner visningen for første gang
Så skal komponenten vises
Så skal komponenten kunne krysses ut

Gitt at config surveyVersion er 2
Gitt at brukeren har svart på surveyVersion 1 tidligere
Når brukeren åpner visningen
Så skal komponenten vises

Gitt at config surveyVersion er 2
Gitt at brukeren har svart på surveyVersion 2 tidligere
Når brukeren åpner visningen
Så skal komponenten ikke vises

Gitt at config surveyVersion er 1
Gitt at brukeren ikke har svart på noen surveyVersion tidligere
Når brukeren åpner visningen
Så skal komponenten vises

Gitt at config surveyVersion er 1
Gitt at config dismissable er true
Gitt at brukeren har krysset ut surveyVersion 1 tidligere
Når brukeren åpner visningen
Så skal komponenten ikke vises

Gitt at config repromptDisplayCount er 12
Gitt at brukeren har svart for 12 visninger siden
Når brukeren åpner visningen
Så skal komponenten vises

Gitt at config dismissable er true
Gitt at config repromptDisplayCount er 12
Gitt at brukeren har krysset ut for 12 visninger siden
Når brukeren åpner visningen
Så skal komponenten ikke vises

Gitt at config repromptDisplayCount er 12
Gitt at brukeren har svart for 10 visninger siden
Når brukeren åpner visningen
Så skal komponenten ikke vises

Gitt at config alwaysShow er true
Når brukeren åpner visningen første gang
Så skal komponenten vises

Gitt at config alwaysShow er true
Når brukeren åpner visningen 10. gang
Så skal komponenten vises

Gitt at config alwaysShow er true
Gitt at brukeren svarte sist visning
Når brukeren åpner visningen neste gang
Så skal komponenten vises

Gitt at config gracePeriodDisplayCount er 3
Når brukeren åpner visningen første gang
Så skal komponenten ikke vises

Gitt at config gracePeriodDisplayCount er 3
Når brukeren åpner visningen 3. gang
Så skal komponenten ikke vises

Gitt at config gracePeriodDisplayCount er 3
Når brukeren åpner visningen 4. gang
Så skal komponenten vises

Gitt at config viewContext er 'assistant'
Når brukeren åpner visningen 'departures'
Så skal komponenten ikke vises

</details>

## Proposed solution

Løses med bruk av FeedbackContext, i samspill med en datastruktur lagret i Firestore

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by toretefre** [comment]
Hvis brukerhistoriene i saken her fungerer, så fungerer nok #2473 også, så flytter den rett til godkjent.

**Comment by tormoseng** [comment]
To observasjoner. Har konfig
```
"viewContext": "assistant",
"surveyVersion": 1,
"alwaysShow": true,
"dismissable": true,
"gracePeriodDisplayCount": 3,
"repromptDisplayCount": 12,
```

Da observerer jeg:
- `gracePeriodDisplayCount` overstyrer `alwaysShow` (ingen tmk første 3 visninger), men siden `alwaysShow = true` burde tmk vært vist allerede fra første visning
- `dismissable` overstyrer `alwaysShow` s.a. tmk ikke vises igjen etter å ha blitt krysset bort. Siden `alwaysShow = true` burde tmk vært vist også gangen etter at tmk er krysset bort.

**Comment by toretefre** [comment]
Godt observert! Det skal jeg ordne asap

**Comment by tormoseng** [comment]
Re-testet OK i staging

**Comment by tormoseng** [comment]
@toretefre Litt dårlig testing fra min side i forrige runde. Fant noe rusk rundt skjermleser på Android. Markering av "Bra" eller "Dårlig" leser kun opp "alternativet er ikke valgt. aktiver for å velge dette alternativet". Det samme med årsakene som leses opp om man velger "Dårlig". iOS leser opp "Bra. Jublende hender" og "Dårlig. Tommel ned.".

**Comment by tormoseng** [comment]
@toretefre Testet OK på Android nå. Sier riktignok "Bra false" + "false Dårlig" når man velger, men tenker denne får gå videre nå :-)
