### ISSUE TITLE
Avstand fra "min posisjon" og "adressesøk" viser ulike avstander

### ISSUE THREAD

**Issue by jahnrohme** [AtB-AS/mittatb-app#2352]
**Describe the bug**
Avgangssøk fra "min posisjon" og fra "adresse" viser forskjellige avstander.

Tillegg: lagt inn et nytt scenario i en kommentar som viser at bruk av "min posisjon" i AtB-appen ikke stemmer overens med Ruter og Entur sine apper.

Bilde 1: Avgangssøk «min posisjon». Avstandene stemmer ikke, men ser på kartet at posisjonen er på huset mitt, så det synes jeg er rart.

![image](https://user-images.githubusercontent.com/87697374/158778040-d3ea74c5-d69f-481e-8c66-a9fcd5ea1814.png)

Bilde 2: Avgangssøk min adresse tastet inn. Avstandene stemmer plutselig?

![image](https://user-images.githubusercontent.com/87697374/158778153-6b616cae-27bd-45e0-af81-5b8846d8f7ff.png)

 

**Application version**
Version number: 1.16

**To Reproduce**

**Expected behavior**
Ønskelig at avstanden skal vise tilnærmet lik

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tormoseng** [comment]
Her er kall som går basert på koordinatene til adressen Laura Hangerås veg 12
GET https://api.prod.mittatb.no/bff/v1/geocoder/reverse?lat=63.38900368979588&lon=10.34911915537739

Her er også kallet som går for å finne nærmeste holdeplasser i Avgangerfanen v2

GET https://api.prod.mittatb.no/bff/v2/departures/stops-nearest?count=30&distance=1000&latitude=63.38900368979588&longitude=10.34911915537739

Fra bruker (Mats)
> Begge kall gir riktig resultat på GPS-posisjon, så eneste forklaring jeg da finner er at appen oppfatter feil posisjon på meg? Sjekka dog V1 mot V2 og får ulike avstander på samme posisjon?

V1
```
"properties": {
            "id": "NSR:StopPlace:43455",
            "gid": "whosonfirst:venue:NSR:StopPlace:43455",
            "layer": "venue",
            "source": "whosonfirst",
            "source_id": "NSR:StopPlace:43455",
            "name": "Olav Nygards veg",
            "street": "NOT_AN_ADDRESS-NSR:StopPlace:43455",
            "confidence": 0.6,
            "distance": 0.347,
            "accuracy": "point",
            "country_a": "NOR",
            "county": "Trøndelag",
            "county_gid": "whosonfirst:county:KVE:TopographicPlace:50",
            "locality": "Trondheim",
            "locality_gid": "whosonfirst:locality:KVE:TopographicPlace:5001",
            "label": "Olav Nygards veg, Trondheim",
            "category": [
                "onstreetBus"
            ],
```

V2
```
"__typename": "placeAtDistanceEdge",
                "node": {
                    "__typename": "PlaceAtDistance",
                    "distance": 544.156174639535,
                    "place": {
                        "__typename": "StopPlace",
                        "name": "Olav Nygards veg",
                        "quays": [
                            {
                                "__typename": "Quay",
                                "id": "NSR:Quay:74563",
                                "description": null,
                                "name": "Olav Nygards veg",
                                "publicCode": "",
                                "stopPlace": {
                                    "__typename": "StopPlace",
                                    "id": "NSR:StopPlace:43455"
                                }
                            },
```

**Comment by monopoint** [comment]
Jeg er ikke helt sikker på om jeg forstår hva denne saken handler om. Jeg ser at det er litt forskjell på v1 og v2 fra denne GPS-posisjonen. 
Begge disse holdeplassene ligger på veldig lik avstand fra brukerens posisjon.
I luftlinje ligger `Kystad` nærmere, men i gåavstand vil `Ole Nygårds veg` være nærmere.
Jeg vil tippe at v2 ser på gåavstand mens v1 er litt enklere. 
Uansett er det så små marginer her at det er som corner case å regne.

**Comment by tormoseng** [comment]
**Scenario 2.1 Reisesøk basert på "Min posisjon" gir ulikt resultat i AtB-appen vs Ruter / Entur**

![reisesøk_comparison](https://user-images.githubusercontent.com/5812433/161541705-fa1d07bf-7a9c-4fad-b814-2ffa85108daa.png)

Vanlig prosess ved reisesøk:
1. Finn min posisjon (PG39)
    - GET https://api.prod.mittatb.no/bff/v1/geocoder/reverse?lat=63.43125212741734&lon=10.392992084638609
2. Finn reise fra min posisjon til Laura H 12 (fra PG39)
   - POST https://api.prod.mittatb.no/bff/v2/trips med body
```{
  "to": {
    "name": "Laura Hangerås' veg 12",
    "coordinates": {
      "latitude": 63.38889938825702,
      "longitude": 10.349046235411894
    }
  },
  "from": {
    "name": "Prinsens gate",
    "coordinates": {
      "latitude": 63.43259954442901,
      "longitude": 10.391485220286912
    }
  },
  "when": "2022-04-04T11:11:03.562Z",
  "arriveBy": false
}

**Problem**
AtB-app viser reiseforslag som ikke stemmer overens med virkeligheten / Ruter / Entur fra brukers posisjon til Laura H 12

Koordinater for "min posisjon" er : 63.39751001260316, 10.367191019671244

Test av JP3 med aktuelle koordinater -> Laura H 12 viser samme reiseforslag som Vy / Entur: [JP3 søk](https://api.entur.io/graphql-explorer/journey-planner-v3?query=%7B%0A%20%20trip%20%28%0A%20%20to%3A%20%7B%0A%20%20%20%20name%3A%20%22Laura%20Hanger%C3%A5s%27%20veg%2012%22%2C%0A%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20latitude%3A%2063.38889938825702%2C%0A%20%20%20%20%20%20longitude%3A%2010.349046235411894%0A%20%20%20%20%7D%0A%09%7D%2C%0A%20%20from%3A%20%7B%0A%20%20%20%20coordinates%3A%20%7B%0A%20%20%20%20%20%20latitude%3A%2063.39751001260316%2C%0A%20%20%20%20%20%20longitude%3A%2010.367191019671244%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20dateTime%3A%20%222022-04-10T18%3A00%3A00.562Z%22%2C%0A%20%20arriveBy%3A%20false%0A%20%20%29%7B%0A%20%20%20%20tripPatterns%20%7B%0A%20%20%20%20%20%20expectedStartTime%0A%20%20%20%20%20%20duration%0A%20%20%20%20%20%20walkDistance%0A%20%20%20%20%20%20legs%20%7B%0A%20%20%20%20%20%20%20%20mode%0A%20%20%20%20%20%20%20%20distance%0A%20%20%20%20%20%20%20%20duration%0A%20%20%20%20%20%20%20%20line%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20toPlace%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%7D%0A%7D)

**Spørsmål**
- Vil dette si at Appen setter inn feil koordinater i reisesøket? 
- Hvor tas koordinatene i "from"-feltet fra, og brukes svar fra `/bff/v1/geocoder/reverse` på noen måte inn her?

**Comment by toretefre** [comment]
Har et veldig likt eksempel på at bruk av "Min posisjon" gir en dårlig mapping til nærmeste gateadresse / ganglenke, hvis noen skulle ha behov for det til feilsøking. Tipper det eksempelet kan være ganske relevant her.

**Comment by tormoseng** [comment]
Til info. Her er kall som AtB-app og Entur-app benytter:

**Geocoder reverse**
- GET https://api.prod.mittatb.no/bff/v1/geocoder/reverse?lat=63.39751001260316&lon=10.367191019671244
- GET https://api.entur.io/geocoder/v1/reverse?point.lat=63.39751001260316&point.lon=10.367191019671244&lang=no&size=5

Disse ser ut til å gi relativt like resultater, men ikke helt på ulike koordinater. Annet eksempel gir ulike svar:
- GET https://api.prod.mittatb.no/bff/v1/geocoder/reverse?lat=63.38889938825702&lon=10.349046235411894
- GET https://api.entur.io/geocoder/v1/nearby?lang=no&point.lat=63.38889938825702&point.lon=10.349046235411894&layers=venue&boundary.circle.radius=2.5&multiModal=all&size=50

Her er f.ex Laura H vei item no.3 på AtB, mens Laura H ikke er med hos Entur.

**Nærmeste stopp**
- GET https://api.prod.mittatb.no/bff/v2/departures/stops-nearest?count=30&distance=1000&latitude=63.39751001260316&longitude=10.367191019671244
- GET https://api.entur.io/geocoder/v1/nearby?lang=no&point.lat=63.39751001260316&point.lon=10.367191019671244&layers=venue&boundary.circle.radius=2.5&multiModal=all&size=50

Her er det ulikheter. Hallset er f.ex 494 m unna på AtB, men kun 392 m unna på Entur, og tilsvarende for Munkvoll er 490 m og 367 m.

**Comment by gorandalum** [comment]
Lukkes da den utforskende fasen er ferdig. Løses i #2499.
