### ISSUE TITLE
Forventet holdeplass dukker ikke opp i avganger

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#2356]
## Observasjon

Bruker bor rett ved holdeplassen på Casper Lunds veg, men denne dukker ikke opp i appen som alternativ for holdeplasser i nærheten.
Hvis jeg prøver å gjenskape situasjonen fra en annen posisjon i nærheten, så dukker den opp. Det er akkurat som Bruker bor i et skyggehull for Casper lund.
ToDo:
- [ ] Verifiser at vi ikke gjør noe merkielig på vår side, og hvis ikke er nok dette et case for Entur.

> Hei
Når jeg trykker på Avganger så kommer alle andre busstopp i nærheten opp, bortsett fra Casper Lundes Vei. Det er dette som er nærmest og jeg har prøvd å endre hvor jeg er, men det kommer likevel ikke opp.

> Hei, prøvde å se etter nå. Hvis jeg velger min posisjon som Kolstadtunet i kartet, som ligger ganske nære Casper Lundes veg, så dukker holdeplassen Casper Lundes veg opp som nærmeste holdeplass i Avganger.
Hvilken adresse er det du prøver, der holdeplassen ikke vises?

![image](https://user-images.githubusercontent.com/1464594/158975572-b7c73aa1-7512-4b39-8731-8174796f150d.png)

## Løsning
Feilen lå i OSM.
For at en holdeplass skal være finnbar, må den ha forbindelse med vegnettet. I dette tilfellet var platformen plassert slik at alle ganglenker gikk forbi platformen, istedet for igjennom den. Dermed blir ikke holdeplassen plukket opp av eksporten av GSM-data som entur bruker (via [https://download.geofabrik.de/](https://download.geofabrik.de/))
Løsningen ble å flytte ganglenke på norsiden av vegen, og legge til en ganglenke på sørsiden.
![image](https://user-images.githubusercontent.com/1464594/160796997-10112089-bd07-4245-9fca-02becafab8f4.png)
Slik så det ut før endring
![image](https://user-images.githubusercontent.com/1464594/160797117-4d3589d1-10e3-4398-8554-dbfa4dfc34de.png)
Slik ser det ut etter endring.

## Test
Eksport fra OSM gjøres hver natt. Når endringene er i effekt skal [denne spørringen](https://api.entur.io/graphql-explorer/journey-planner-v3?operationName=nearestStopPlaces&query=query%20nearestStopPlaces%28%24count%3A%20Int%20%3D%2010%2C%20%24distance%3A%20Float%21%2C%20%24longitude%3A%20Float%21%2C%20%24latitude%3A%20Float%21%2C%20%24after%3A%20String%29%20%7B%0A%20%20nearest%28%0A%20%20%20%20latitude%3A%20%24latitude%0A%20%20%20%20longitude%3A%20%24longitude%0A%20%20%20%20maximumDistance%3A%20%24distance%0A%20%20%20%20first%3A%20%24count%0A%20%20%20%20after%3A%20%24after%0A%20%20%20%20filterByInUse%3A%20true%0A%20%20%20%20filterByPlaceTypes%3A%20stopPlace%0A%20%20%20%20multiModalMode%3A%20parent%0A%20%20%29%20%7B%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%7D%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20distance%0A%20%20%20%20%20%20%20%20place%20%7B%0A%20%20%20%20%20%20%20%20%20%20...%20on%20StopPlace%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20quays%28filterByInUse%3A%20true%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20stopPlace%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20transportMode%0A%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22count%22%3A%2030%2C%0A%09%22distance%22%3A%202000%2C%0A%09%22longitude%22%3A%2010.35823%2C%0A%20%20%22latitude%22%3A%2063.367545%2C%0A%20%20%22after%22%3A%20null%0A%7D) inneholde Casper Lundes veg.

**Comment by jahnrohme** [comment]
Kan det være relatert til: https://github.com/AtB-AS/mittatb-app/issues/2352

**Comment by jahnrohme** [comment]
Kan også henge sammen med: https://github.com/AtB-AS/mittatb-app/issues/1915

**Comment by monopoint** [comment]
GPS for Saupsatdringen 29A er 63.36751º N, 10.35819º Ø

**Comment by monopoint** [comment]
Vi bruker [denne spørringen mot JP3](https://api.entur.io/graphql-explorer/journey-planner-v3?operationName=nearestStopPlaces&query=query%20nearestStopPlaces%28%24count%3A%20Int%20%3D%2010%2C%20%24distance%3A%20Float%21%2C%20%24longitude%3A%20Float%21%2C%20%24latitude%3A%20Float%21%2C%20%24after%3A%20String%29%20%7B%0A%20%20nearest%28%0A%20%20%20%20latitude%3A%20%24latitude%0A%20%20%20%20longitude%3A%20%24longitude%0A%20%20%20%20maximumDistance%3A%20%24distance%0A%20%20%20%20first%3A%20%24count%0A%20%20%20%20after%3A%20%24after%0A%20%20%20%20filterByInUse%3A%20true%0A%20%20%20%20filterByPlaceTypes%3A%20stopPlace%0A%20%20%20%20multiModalMode%3A%20parent%0A%20%20%29%20%7B%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%7D%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20distance%0A%20%20%20%20%20%20%20%20place%20%7B%0A%20%20%20%20%20%20%20%20%20%20...%20on%20StopPlace%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20quays%28filterByInUse%3A%20true%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20publicCode%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20stopPlace%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20transportMode%0A%20%20%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22count%22%3A%2030%2C%0A%09%22distance%22%3A%202000%2C%0A%09%22longitude%22%3A%2010.35823%2C%0A%20%20%22latitude%22%3A%2063.367545%2C%0A%20%20%22after%22%3A%20null%0A%7D) og forventer å finne [Casper Lundes holdeplass](https://api.entur.io/graphql-explorer/stop-places?query=%7B%0A%20%20stopPlace%28size%3A%205%2C%20stopPlaceType%3A%20onstreetBus%2C%20id%3A%20%22NSR%3AStopPlace%3A44014%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%20%7B%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%20%20geometry%20%7B%0A%20%20%20%20%20%20coordinates%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A), men den mangler fra resultatet.

Jeg har sendt spørsmålet videre til entur. https://mittatb.slack.com/archives/CHLDG8C30/p1648545063971369

**Comment by monopoint** [comment]
Blocked mens vi venter på entur

**Comment by monopoint** [comment]
løst

**Comment by tormoseng** [comment]
Testet OK

**Comment by gorandalum** [comment]
Fikset av endringer i OSM, og ikke å våre kanaler.
