### ISSUE TITLE
Oppdater mapbox, holdeplasser er flyttet

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#2357]
Vi må jevnlig oppdatere Mapbox.
Bruker har rapportert at Være holdeplass er feil i appen

![image](https://user-images.githubusercontent.com/1464594/158977311-19f344cf-c2f6-4899-badd-620030f82b23.png)

her sammenliknet med kartet fra atb.no

**Comment by torfjor** [comment]
Dette er en plattform-oppgave for å få asag opp og stå, eventuelt en gjentagende jobb som gjør det samme.

Se AtB-AS/team-platform#19

**Comment by jahnrohme** [comment]
Lukker denne, da denne håndteres av Plattform
