### ISSUE TITLE
Tilbakemeldingskomponent: Lage tabeller/grafer

### ISSUE THREAD

**Issue by jahnrohme** [AtB-AS/mittatb-app#2371]
# Mål
Kunne tydeliggjøre høstingen fra tilbakemeldingskomponenten til å finne svar på spørsmål som vi lurer på.

# Avhengighet fra Plattform:
Eksport av hele collection kjører nå hver natt til BigQuery: https://github.com/AtB-AS/team-platform/issues/104

# ToDo
- [ ] Vi må avklarerhvordan samspillet med å få opp grafer/spørringer skal være. 
- [ ] Kundevendts behov:
- [ ] Markedsinnsikts behov:

**Comment by strombraaten** [comment]
### Fra design-perspektivet så vil vi gjerne kunne se:

**Prosentmessig fordeling fordelt på de ulike svar-alternativene**
Det blir i så fall todelt, siden det både gjelder bra/dårlig, i tillegg til de ulike alternativene som velges dersom man svarer "dårlig". Se bilder under.

1. Hvor mange svarte Bra 👍 og hvor mange svarte Dårlig 👎 ?
2. Hvor mange valgte f. Eks "Vanskelig å navigere" osv.? På den måten vil vi kunne trekke ut konklusjoner som f. Eks _"Av de som svarte Dårlig så var det 60% som syns det var vanskelig å navigere på den nye Avganger visninga"_

**Utviklingen fra første gang man svarer til andre gangen** 
Etter å ha diskutert med @toretefre forstod jeg at vi kan se hvor mange prosent av de som svarte Dårlig 👎  første gangen, endra deretter meninga si andre gangen og svarte Bra👍 .
Vi kan altså sammenligne på en gruppe med brukere som svarte ja/nei, men vi kan ikke sammenligne svarene til én enkelt bruker. @hildeor her har du forresten svaret på om vi kan tracke svarene til en bruker.

---

Det her blir vel litt på sida, men vi skulle også gjerne se hvor mange som har skrudd Avganger/reisesøk av og på, så lenge den er i beta. Husker du hvilken issue som er relatert til den logginga, @rosvik ? Tenkte bare jeg skulle linke inn i den her.

![image](https://user-images.githubusercontent.com/72508979/160594887-19e73d8d-e081-40d0-baee-1caaae131e8e.png)

![image](https://user-images.githubusercontent.com/72508979/160594916-d9084289-1f89-43f8-9b2e-96291095836a.png)

**Comment by strombraaten** [comment]
@jahnrohme I og med at vi ikke skal lage tabellene/grafene sjøl, anser vi da den her som ferdig når @torfjor og Håvard har fått tatt en prat om hvordan man får tak i dataen fra tilbakemeldingskomponenten? For da er den jo ute av våre hender, og over i fanget til Markedsinnsikt sånn sett. Er vel ikke relevant å la den ligge på tavla vår i vente på at den skal være up and running i PowerBI, eller hva tenker du?

**Comment by rosvik** [comment]
> Husker du hvilken issue som er relatert til den logginga, @rosvik ?

@strombraaten Denne:

- https://github.com/AtB-AS/mittatb-app/issues/1957

**Comment by strombraaten** [comment]
Tar meg friheten til å lukke den her siden saken nå går videre på plattformsida:
- https://github.com/AtB-AS/team-platform/issues/118
- https://github.com/AtB-AS/team-platform/issues/117
