### ISSUE TITLE
[Feature] Add useful metadata

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#238]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

Metadata about the installed app could be useful for debugging. 

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

- Metadata should not take attention from other parts of the app.

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

- Show a human-readable install-id in the bottom if the profile tab.
- Show build number for distributions through test flight.

**Comment by hildeor** [comment]
Looks like this has already been implemented? @gorandalum 
I see there is a version number, and ID in staging now.
