### ISSUE TITLE
Android tilbake-knapp resetter reisesøk

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#2391]
Denne funksjonaliteten ser ut til å ha forsvunnet i  merge.

Android har hardware tilbake-funksjonalitet som vi må ta høyde for i UX.
Denne endringen sørger for at hvis brukeren har gjort et reisesøk, og deretter trykker `tilbake` så resettes søket. Uten denne endringen ville `tilbake` ha lukket appen.
Appen lukkes hvis Bruker trykker `tilbake` når søket allerede er nullstilt.

**Comment by tormoseng** [comment]
Testet OK på Android 7.0 i staging
