### ISSUE TITLE
Delvis engelsk i RenderQuestions-alternativer

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#2419]
Fra https://github.com/AtB-AS/mittatb-app/issues/2211#issue-1149017160

VoiceOver i tilbakemeldingskomponent leser delvis på engelsk når man flytter fokus mellom de ulike svaralterativene under "dårlig". ("Annet. Sjekkboks checked"

**Comment by gorandalum** [comment]
Blir løst i #2345

**Comment by toretefre** [comment]
Etter å ha endelig fått testet på egen telefon, ser det faktisk ut som manglende oversettelser for gitte interactions er et problem med React Native: https://github.com/facebook/react-native/issues/31227

Vi har dermed et lite utvalg med løsninger:

1. Legge på ekstra hint som forteller om ting er valgt eller ikke.
2. Endre rolle fra `radio` til `button` som faktisk blir oversatt, og heller signalisere state med hint.
3. Legge ved våre egne oversettelser, slik som hacket til [her](https://valtterilaine.medium.com/react-native-accessibilityrole-i18n-support-for-ios-and-android-16d896e69178)
4. Sende inn pull request på React-native, men jeg ser ikke hvordan dette fikses hos de på en enkel måte.

Foreløpig har jeg gått for alternativ 1 på denne måten: https://github.com/AtB-AS/mittatb-app/pull/2377/commits/58d64b949ea268e797360de1d0702c7699cdf9fb, og jeg ser på alternativ 2 som eneste reelle alternativ. 

Noen tanker, eller kan det være noe jeg eventuelt har misforstått, @tormoseng @gorandalum @mikaelbr?

**Comment by gorandalum** [comment]
Jeg har ikke sett så nøye på dette, men min umiddelbare tanke er at vi avventer fiks i react-native i stedet for å manuelt håndtere det. Jeg har så lite lyst til å begynne å håndtere radio-boks-status manuelt i stedet for å lene oss på skjermleser-støtten som vi skal få automatisk av å bruke korrekt html.

Jeg tror brukere av skjermlesere er generelt fornøyd med vår implementasjon, likevel om det leses "checked" i stedet for "avhuket":
