### ISSUE TITLE
Bruke referanse-data fra Firestore

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2430]
## Opprinnelse
Tidligere har referansedata og annen konfigurasjon ligget i Remote Config. Dette er uheldig siden det er en delay fra man oppdaterer Remote Config til det blir synlig app. I nettbutikken har vi allerede gått over til Firestore i denne saken: 
https://github.com/AtB-AS/webshop/issues/437

I saken nevnt ovenfor ble også noen andre konfigurasjoner overført til firestore. Man kan også gå over til å bruke de i appen.

## Analyse
preAssignedFareproducts_V2 ligger her: https://console.firebase.google.com/project/atb-mobility-platform-staging/firestore/data/~2Fconfiguration~2FreferenceData

På sikt vil vi flytte alt av konfigurasjon fra remoteConfig over til Firesstore.
Vi lager derfor en context i Appen, ConfigurationContext, der referansedata er en del av konfigurasjonen som ligger der.

## Test
Si fra Til Gunn så hun kan teste i QA

**Comment by tormoseng** [comment]
Denne er testet OK i staging, bortsett fra at distributionChannel ikke tas hensyn til i Appen. Dette fikses av #2492
