### ISSUE TITLE
Komponent for valg av periodelengde

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2457]
### Bakgrunn
Nytt design for valg av periodelengde i forbindelse med billettkjøp 2.0

Brukes på:
Periodebilletter
Ungdomsbillett
Klippekort
24 timersbillett
Sommerpass

![](https://user-images.githubusercontent.com/8980523/152798355-8cfd7918-babf-413c-a505-81c1019f289a.png)
https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App-1.1?node-id=7657%3A65776

### Løsning
En "karusell" over mulige periodelengdevalg. Bare én kan velges om gangen. Scrolles horisontalt hvis skjermbredden ikke kan vise hele. Bør løses som en generisk flervalgs karusell, og ikke tett knyttet opp mot billettprodukter.

I dagens billettkjøpsflyt velger man billettprodukt, og og ikke periodebillettlengde. For å løse denne endringen på en god måte må man også få inn billettlengde på produktene i referansedata i Firestore. Merk da at valg av periodelengde rent teknisk blir valg av et spesifikt billettprodukt.

**Comment by tormoseng** [comment]
@rosvik To ting:
- Alternativet "1 dager" skulle vel vært "1 dag" (tilsvarende på engelsk)
- Android/TalkBack: Fokus på alternativene leser opp "(Valgt) Aktiver for å velge varighet alternativknapp dobbelttrykk for å aktivere". Ingen opplesning av selve verdien. iOS leser opp verdiene.

**Comment by gorandalum** [comment]
@tormoseng Ref det andre punktet, synes du man trenger `accessibilityHint` "Aktivèr for å velge 30 dager" eller lignende her? Eller er det nok med "30 dager. Alternativknapp. Dobbelttrykk for å aktivere"? Siden man har vært innom overskrift "Velg varighet" like før så skal konteksten være grei tenker jeg.

**Comment by rosvik** [comment]
- Tenkte det ikke var nødvendig å håndtere nå, siden dette kun gjelder staging, pluss at det skal hete "24 timer" og være en egen skjerm separat fra periodebilletter. 
- Jeg tenker det holder at den leser "30 dager, aktiver for å sette varighet". Implementer her: https://github.com/AtB-AS/mittatb-app/pull/2621 Men ikke så vanskelig å forandre på.

**Comment by tormoseng** [comment]
Enig med @rosvik. Nok med "30 dager". Det er det som leses opp på iOS, så godt nok for Android også :-)

**Comment by tormoseng** [comment]
Re-testet OK på Android
