### ISSUE TITLE
Komponent for å velge soner

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2458]
### Bakgrunn
Brukes for å navigere til eksisterende sonevelger og vise frem valgt sone. Består av label og verdi.

Brukes på:
- Periodebilletter
- Enkeltbillett
- Klippekort
- 24 timersbillett

![](https://user-images.githubusercontent.com/8980523/152798807-8c62981a-5233-4676-87a5-0affee39a053.png)

### Løsningsforslag
Kan kanskje løses med bare små endringer på eksisterende Sections -> ButtonItem.

**Comment by gorandalum** [comment]
@tormoseng Noen små endringer på denne etter merge av https://github.com/AtB-AS/mittatb-app/pull/2611. Behøver trolig ikke ny test-runde, men du kan ta en titt på beskrivelsen i den saken og avgjøre om det er nødvendig.

**Comment by tormoseng** [comment]
@jorelosorio A small thing with screen reader. The subtitle "Velg sone(r)" / "Select zone(s)" is read as "Velg sone r". Not too important, but could be interpreted that zone "R" is selected - especially with TalkBack.

**Comment by gorandalum** [comment]
That is actually introduced by me when adding the "(r)". I'll fix it.

**Comment by gorandalum** [comment]
Fixed in the linked PR. Such a small change that it is enough if you review it @tormoseng.

**Comment by tormoseng** [comment]
> Such a small change that it is enough if you review it @tormoseng.

Den PR-en skjønte jeg faktisk 👍

**Comment by tormoseng** [comment]
Re-testet OK
