### ISSUE TITLE
Komponent for å velge oppstartstidspunkt

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2459]
### Bakgrunn

Brukes for å velge oppstartstidspunkt for en gitt billett. Står default på Nå. Ved valg av "Senere" får man opp eksisterende dato/tidsvelger. Deretter vises også evt. dato og tidspunkt som er satt når man har endret til senere.

Brukes på:
- Periodebilletter
- Enkeltbillett (i fremtiden?)
- Ungdomsbillett
- 24 timersbillett
- Sommerpass

![](https://user-images.githubusercontent.com/8980523/152799634-5eb4af1e-b58a-45c6-9105-2fd3648f81ae.png)

### Løsningsforslag
Trolig gjenbruk av reisetidspunktvelger fra Avganger-skjerm

**Comment by rosvik** [comment]
@tormoseng La inn en PR som skal fikse alle dato-feilene (#2659), men tror ikke jeg klarer å styre TalkBack fokus etter å ha endret dato. Har inntrykk av at det generelt er vanskelig å styre fokus, pluss at jeg ikke får testet på android.

**Comment by tormoseng** [comment]
Re-testet OK med @rosvik sin kommentar over!
