### ISSUE TITLE
Komponent for valg av reisende - multiselect

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2461]
### Bakgrunn 
Andre billettyper som f. eks enkeltbillett støtter flere passasjerer på samme billett. Se egen issue (https://github.com/AtB-AS/mittatb-app/issues/2107) for beskrivelse av logikk rundt lagring av standard passasjerkategori.
Når en kategori er > 0, får den bakgrunnsfarge bak antallet. I tillegg blir minus-ikonet sort. Viktig at minus-ikonet fortsatt er mulig å navigere til via VoiceOver. Også infotekster kan toggles.

Brukes på:
- Enkeltbillett
- Sommerpass

![](https://user-images.githubusercontent.com/8980523/152805119-4efc74bc-76b7-43b8-8c2b-b29f3c926545.png)

### Løsningsforslag
`Sections.CounterInput` brukes kun i eksisterende multiselect-reisende-flyt, og kan oppdateres til nytt design uten å være redd for konsekvenser andre steder.

**Comment by rosvik** [comment]
Oversettelser av reisendekategorier:

### Norsk

Voksen
20 til og med 66 år.

Barn
6 til og med 19 år.

Student
Fulltidsstudenter og elever under 35 år.

Honnør
Over 67 eller med gyldig honnørbevis.


### Engelsk

Adult
20 to 66 years.

Senior
Over 67 or with concessionary card.

Child
6 to 19 years. Bike.

Student
Fulltime students under 35.

Military
Soldiers in mandatory service.

**Comment by gorandalum** [comment]
Ingen info om sykkel på norsk tekst for barn?

**Comment by rosvik** [comment]
> Ingen info om sykkel på norsk tekst for barn?

@gorandalum Kom frem her at det finnes flere mulige beskrivelser for forskjellige reisende/billettprodukter-kombinasjoner. F.eks. at det ikke det informeres om sykkel på barn periodebillett. Samme med info om billetten er gyldig på nattbuss.

**Comment by tormoseng** [comment]
@rosvik En liten ting. Med TalkBack så markeres f.ex "1" mellom "-" og "+" i valgene. Så om man sveiper for å skifte fokus blir det lest opp "reduser etc." for "-", deretter "1", så "øk etc." for "+". På iOS/VoiceOver så får ikke tallet mellom "-" og "+" noe fokus.

**Comment by tormoseng** [comment]
@monopoint Har du mulighet til å se raskt på denne ☝️
