### ISSUE TITLE
Bedre theme-farge-støtte i designsystemet

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2463]
### Bakgrunn
I designsystemet slik det er implementert nå har man typen `ContrastColor` som har et felt `color` for skriftfarge og felt `backgroundColor` for bakgrunnsfarget. I det oppdaterte designet [i Figma](https://www.figma.com/file/3rlcixpbhfBglNSctUkMys/Theme-1.0?node-id=1012%3A7) så har man støtte også for andre farger i forbindelse med tilstander som "Hover", "Active", "Disabled" og "Outline". Dette bør også støttes av designsystemet.

<img width="325" alt="Screenshot 2022-04-03 at 14 58 41" src="https://user-images.githubusercontent.com/675421/161429302-1c32a9cc-2757-4077-95ae-f56cd85c5bae.png">

Noen skjermbilder som viser hvor dette er i bruk i Billettering v2:

<img width="317" alt="Screenshot 2022-04-03 at 14 58 08" src="https://user-images.githubusercontent.com/675421/161429289-3129308e-26ff-4bcf-be79-eb2021898d0e.png">
<img width="423" alt="Screenshot 2022-04-03 at 14 57 58" src="https://user-images.githubusercontent.com/675421/161429290-05418a6c-ced6-4220-b976-fc4273b17270.png">
<img width="333" alt="Screenshot 2022-04-03 at 14 57 46" src="https://user-images.githubusercontent.com/675421/161429293-fe9d6dcc-cbde-46aa-8b65-7a03378f2886.png">

**Comment by rosvik** [comment]
Løsningen på denne ble litt større enn det som vises i beskrivelsen:

Den store forandringen er at det legges til en "interactive" farge-type, som har farger for "hover", "active", "disabled", "outline" og "default". Resten av fargene er også sortert på en ny måte som reflekterer det som ligger i figma.

- Ny fargetype [`InteractiveColor`](https://github.com/AtB-AS/design-system/pull/30/files#diff-4612a0ec178968d31aefd7ddf37f410f9c4faf9601e0efb8c1e13dad4b1f8b61R20)
- Alle andre farger ligger nå under "static" -> "background", "transport" eller "status" ([her](https://github.com/AtB-AS/design-system/pull/30/files#diff-4612a0ec178968d31aefd7ddf37f410f9c4faf9601e0efb8c1e13dad4b1f8b61R39-R67))
- I `ContrastColor`-typen er `backgroundColor` omdøpt til `background` og `color` til `text`
- `textColorType` er fjernet fra `ContrastColor`-typen
- Går bort ifra "primary" og "secondary" farger. Nå ligger de som brukes som `background_accent_X`.
- Tekstfarger er oppdatert til farger som ikke er gjennomsiktige
- Design system websiden er oppdatert

## Figma

![Screenshot 2022-04-21 at 10 35 23](https://user-images.githubusercontent.com/1774972/164414886-3474d6d5-2c9e-4a47-800a-5b4778024184.png)
![Screenshot 2022-04-21 at 10 35 03](https://user-images.githubusercontent.com/1774972/164414907-ab29417a-308e-4770-a51a-097d33d86360.png)

## design-system

![Screenshot 2022-04-21 at 13-21-24 AtB Design System](https://user-images.githubusercontent.com/1774972/164447657-0b4f0988-f5d9-473e-a31a-d7955674ca23.png)

**Comment by tormoseng** [comment]
Dette ser bra ut!
