### ISSUE TITLE
Tilbakemeldings knapp som går til nettside istedenfor Intercom

### ISSUE THREAD

**Issue by mortlun** [AtB-AS/mittatb-app#2465]
NFK ønsker å ha en knapp som går til nettside istedenfor Intercom for tilbakemeldinger på appen.

**Comment by gorandalum** [comment]
@mortlun Bør testes av oss i staging også. Kunne du beskrevet til Tor hvordan han kan teste denne. Hva han må sette i RemoteConfig og hvordan logikken skal være i corner cases hvor man f.eks. har satt både intercom enabled og url.

**Comment by mortlun** [comment]
> @mortlun Bør testes av oss i staging også. Kunne du beskrevet til Tor hvordan han kan teste denne? Hva han må sette i RemoteConfig og hvordan logikken skal være i corner cases hvor man f.eks. har satt både intercom enabled og url.

Ja. 

- Du kan legge inn customer_feedback_url i remote config med https://www.reisnordland.no/tilbakemeldingsskjema-reiseapp. 
- Så kan du gå inn i appen å trykke på chatte-ikonet. Da vil knappen nederst "forbedre appen" gå til den nettsiden.
- Hvis enable_intercom også er true, så skal bare knappen som går til nettside vises. 
- vis du fjerner customer_feedback_url fra remote config og enable_intercom er true så går knappen til intercom igjen.

**Comment by tormoseng** [comment]
Re-testet OK etter siste fix!
