### ISSUE TITLE
Billettering må respektere DistributionChannel 

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#2492]
## Origin
Etter at vi skrudde om til å hente fareproducts fra Firestore, avdekket vi at produkter som har satt kun distribution "web" også dukker opp i app.
Kun fareproducts med ddistributionChannel "app" skal dukke opp i appen.

**Comment by tormoseng** [comment]
Testet OK med å fjerne/legge til både app og web som distribusjonskanaler i staging for ulike produkter.
