### ISSUE TITLE
"Min posisjon" blir evaluert til ulogisk adresse

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2499]
### Bakgrunn
Vi har fått tilbakemeldinger fra brukere (og AtB-ansatte) om at ved bruk av "Min posisjon" så får man ulogiske reiseruter. Dette har blitt utredet og feilsøkt en god del i denne saken:
https://github.com/AtB-AS/mittatb-app/issues/2352

Vi får det ikke til å stemme at det alltid har vært slik, og har hatt en del dialog med Entur om dette:
https://mittatb.slack.com/archives/CHLDG8C30/p1649245264260019

Uansett så ser det ikke til å være mer å hente mot Entur, så vi bør løse dette på vår side.

### Løsning
- Ved bruk av "Min posisjon" så brukes devicesens faktisk GPS-koordinater inn i søkene mot Entur. Dette blir da endret både for å søke etter reiser (trips) i Reisesøk, og får å slå opp holdeplasser i Avganger. Her blir det da en endring ved at man ikke lenger benytter Entur sitt geocoder reverse endepunkt.
- Om man velger "Velg i kart" og beveger markøren så skal man som tidligere bruke geocoder reverse for å mappe kartnålens posisjon til en adresse. Geocoder reverse skal fungere som før, det er ikke i kontekst av denne saken å endre den til å f.eks. inkludere gateadresser.
- Siden det er enda viktigere enn før at brukerens posisjon er korrekt så oppdaterer vi GPS-koordinater når brukeren har beveget seg 20m, i stedet for 50m slik det var før.

### Akseptansekriterier
- [ ] Ved utfylt sted med "Min posisjon" så brukes enhetens posisjon i reisesøk.
- [ ] Ved utfylt sted med "Min posisjon" så brukes enhetens posisjon i avganger v1.
- [ ] Ved utfylt sted med "Min posisjon" så brukes enhetens posisjon i avganger v2.
- [ ] Ved utfylt sted med "Min posisjon", om man går til lokasjonssøk så skal tekstfeltet være tomt.
- [ ] Ved utfylt sted med "Min posisjon", om man går til lokasjonssøk og deretter "Velg i kart" så skal utgangspunktet være på "Min posisjon".
- [ ] Om man i "Velg i kart" flytter bildet til å være sentrert et annet sted enn "Min posisjon" så skal stedsnålen posisjon evalueres til en adresse.
- [ ] Søk med "Min posisjon" lagres ikke i de tre sist brukte reisesøk.
- [ ] "Min posisjon" kan ikke lagres som favoritt.
- [ ] "Min posisjon" brukes for å velge default tariffsone.
- [ ] Generell utforskende testing for å sjekke at det ikke er nyinnførte bugs på reisesøk og avganger v1/v2.

**Comment by tormoseng** [comment]
Denne ser veldig bra ut fra mitt ståsted. Testet Android + iOS + sjekket kall og koordinater i kall gjennom proxy. Digg å slippe alle kallene til geocoder reverse.

For faktiske avstander så bør denne saken testes mot Entur i Prod pga https://mittatb.slack.com/archives/CHLDG8C30/p1649840107654179
