### ISSUE TITLE
Språk for Billettering v2-1

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#2548]
Siden det er litt fram og tilbake med språk her, lager jeg en egen sak for å kunne dokumentere avklaringer her.

forslag, godkjent av Gunn:
```
availableTickets: {
  singleTicket: {
    title: _('Enkeltbillett', 'Single ticket'),
    description: _(
      'Gyldig i 90 minutter og opp til 5 timer',
      'Valid for 90 minutes up to 5 hours',
    ),
    transportModes: _('Buss/trikk', 'Bus/tram'),
  },
  periodTicket: {
    title: _('Periodebillett', 'Periodic ticket'),
    description: _(
      'Velg mellom 7, 30, 60 og 90 dager',
      'Choose between 7, 30, 60 and 90 days',
    ),
    transportModes: _('Buss/trikk', 'Bus/tram'),
  },
  summerPass: {
    title: _('AtB SommerPass', 'AtB Summer Pass'),
    description: _(
      'Utforsk Trøndelag med buss, tog, hurtigbåt, ferge og trikk i sju dager. Reis så mye du vil!',
      'Explore Trøndelag by bus, train, tram, passenger boat or ferry, for 7 days. Travel as much as you like!',
    ),
    transportModes: _('Flere reisemåter', 'Several travel modes'),
  },
},

```

[Simen Strøm Braaten [09:59]:](https://mittatb.slack.com/archives/C036F9Q15R8/p1650614374660349)
Angående enkeltbilletten så fikk jeg svar fra Gunn nå, og vi kjører på med det forslaget som jeg skreiv i markdown-fila oppi der (“Gyldig i 90 minutter og opp til 5 timer”).
Bakgrunnen:

- Å reise i én sone gir en gyldighet på 90 minutter, Deretter er det 1 time ekstra pr sone
- Maks reise du kan ta fra nord til sør er på 6 soner, altså 90 min for sone 1 + 5 t for de neste 5 sonene, men det er ikke en lett reise å få til akkurat
- Derfor ville det vært mer realistisk å si “..opp til 4 timer”, gjennom 4 soner, men muligheten burde jo være der for dem som vil prøve seg på en sånn “ekstremreise”
- I tillegg til det her så vil det nok bli påvirka av den utvidelsen til 3 timer gyldighet, som skal gjelde i helgene og utafor rushtid, og da kan det nok teknisk sett bli mer enn 5 timer gyldighet, men tror nok det uansett er noe vi må komme tilbake til, og heller oppdatere ved behov.

**Comment by gorandalum** [comment]
Lukker siden den er løst i andre saker og det ikke er knyttet opp noen PR.
