### ISSUE TITLE
Update Ticketing for design system v4

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/mittatb-app#2563]
Noen  utestsående oppgaver for å fullføre at Ticketing bruker designsystem v4
Ticketing mergest til master før DS v4 er final, så disse oppgavene må gjøres før vi gjør app v1.18
Disse oppgavene er også [nevnt i PR](https://github.com/AtB-AS/mittatb-app/pull/2562) 
Disse oppgavene kan løses som egnte pullrequests som tagges med #2110 

- [ ] src/components/section/link-items.tsx [65] -> oppdater etter design system v4
- [ ] src/reference-data/types.ts -> durationDays settes til Number istedet for hardkodede verdier, for mer fleksibilitet i firestore
- [ ] src/screens/Ticketing/Tickets/RecentTickets/RecentTicketComponent.tsx [81] -> tekster bør håndtere nye modes uten at logikken må endres hver gang `text = t(RecentTicketsTexts.transportModes[mode.mode]) ?? t(RecentTicketsTexts.transportModes['unknown'])`
- [ ] ~~src/screens/Ticketing/Tickets/AvailableTickets/Ticket.tsx -> Ta i bruk interactiveColor for accented tickets~~
- [x] src/screens/Ticketing/Tickets/AvailableTickets/Ticket.tsx [112] -> ta i bruk Label fra design system
- [x] Dark mode ticket illustrations

**Comment by tormoseng** [comment]
Testet gjennom QA på 1.18, og testet ellers ved QA av UX.
