### ISSUE TITLE
Wrong translation in english in "My profile" -> "Ticket Inspection"

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/mittatb-app#2566]
I norsk versjon står det at mindreårige over 15 får bot. I engelsk at mindreårige under 15 får bot. Den norske versjonen er riktig.

The norwegian translation is correct, but the english is wrong:
Change
"Minors under 15 years [...]" -> "Minors over 15 years [...]"

**Comment by tormoseng** [comment]
Testet OK i staging
