### ISSUE TITLE
Endre ikon for driftsavvik i app

### ISSUE THREAD

**Issue by JuliaOppegard** [AtB-AS/mittatb-app#2589]
Endre kjegla som brukes oppe til høyre til standard ikon brukt for driftsavvik.
Bakgrunnen for at vi ønsker å endre er å ha helhetlig ikonbruk på tvers av digitale og statiske flater.

- [ ] legg ikon inn som mono-ikon i designsystem
- [ ] bytt ut eksisterende med nytt ikon

Endre fra (ikonet oppe til venstre):
![FF144DC9-656D-444F-BFD6-F48C5BDC1D2F](https://user-images.githubusercontent.com/84782769/165923969-85061397-147e-474b-a9bc-009adfdc4afe.jpeg)

Endre til (kan brukes uten sirkel):
![image](https://user-images.githubusercontent.com/84782769/165924314-173eae28-b547-4ca6-9ef8-b763d9c6ed28.png)

Ikonet kan lastes ned her: https://www.atb.no/profilhandbok/ikoner/
direktelink: https://www.atb.no/getfile.php/13535-1510218427/Ikoner/a-varsel.svg

**Comment by rosvik** [comment]
Lukker denne siden det ble avklart at vi beholder ikonet inntil videre. Se [slack](https://mittatb.slack.com/archives/C02EEG7D8EL/p1651662203678049?thread_ts=1651214699.381859&cid=C02EEG7D8EL).
