### ISSUE TITLE
[BUG] Fjerne billetterings-varsler fra Reis-app

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#2602]
**Describe the bug**
En reise med Nordland Fylkeskommune sin hurtigbåtrute fra Bodø til Grønnøy gir feilmelding om at billetten må kjøpes hos en annen aktør. Kan muligens sees i sammenheng med #2601 .

![image](https://user-images.githubusercontent.com/21310942/166194897-3f85371b-c183-41fc-8491-4735b677a064.png)

**Application version**
Trolig 1.17

**To Reproduce**

**Expected behavior**
Her er jeg litt usikker på om vi bare skal fjerne denne varslingen når enable_ticketing er false, eller om dette er et problem vi uansett må løse når Nordland aktiverer billettering.

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by toretefre** [comment]
Løst her: https://github.com/AtB-AS/mittatb-app/pull/2607

**Comment by tormoseng** [comment]
Testet OK (for AtB). Testet med å endre `enable_ticketing` i Rem.Conf.
