### ISSUE TITLE
Manglende S på "intermediate stops" og NFK typo

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#2604]
**Describe the bug**
NFK har enkelte skrivefeil i sin app jeg skal fikse

Under Trip details: 
«8 intermediate stop» bør være «8 intermediate stops»
![image](https://user-images.githubusercontent.com/21310942/166197488-5404c8e7-247a-4256-b90f-c42a1bb09c14.png)

Under Tickets: Organize skrives med z og ikke s. 
![image](https://user-images.githubusercontent.com/21310942/166197423-3eb75766-6c81-443e-8dfd-4552476e7e7b.png)

**Application version**
Version number: [e.g. 1.2.3]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tormoseng** [comment]
Testet OK for AtB.
