### ISSUE TITLE
Update NFK colors after design system v4

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#2618]
**Describe the bug**
The introduction of interactive colours and renaming of some background colours in the design systems have led to some colours in the Reis NFK app to default to white. A picture sometimes tells more than 1000 words:

![image](https://user-images.githubusercontent.com/21310942/166697628-4b1ea3f4-4abf-4296-a8c0-b4bc471604b4.png)

**Application version**
1.18

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by toretefre** [comment]
Awaiting updated colour values from the NFK designer, expected before lunch the upcoming Monday.

**Comment by tormoseng** [comment]
@HanneLH Denne er mer NFK-relevant, men sjekk at menypunktene i AtB-appen er som de skal være (spesielt at "Reisesøk" / "Assistant" er korrekt) i både light/dark mode.

**Comment by HanneLH** [comment]
Menypunktene i AtB-appen er som de skal være i light og dark mode.
![IMG_0019](https://user-images.githubusercontent.com/104772494/169039809-61a898b2-34fe-4337-9f58-9b7b9147e94a.PNG)
![IMG_0018](https://user-images.githubusercontent.com/104772494/169039821-8b861189-921b-4294-b95f-daa062b1625f.PNG)
![IMG_0016](https://user-images.githubusercontent.com/104772494/169039829-f796b252-c5a2-4559-84d3-bdcd2c49e00b.PNG)
![IMG_0014](https://user-images.githubusercontent.com/104772494/169039851-cc5ac60a-af00-462c-9448-bd2d8079d759.PNG)

**Comment by HanneLH** [comment]
Regression test on iPhone 11 Pro - Ok.
