### ISSUE TITLE
Evaluate standalone remote/on-prem CI with Fastlane

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#263]
AppCenter has been good to us in an early phase of development, with ease of build setup and distribution to the stores.

It does have a few limitations that makes it necessary to evaluate other options though:
- Impossible to setup builds on PR
- Impossible to setup different build types on the same branch (necessitates the `alpha-release` branch in our workflow)
- Impossible to automatically retrieve (and reupload) bitcode dSYMs for iOS builds
- Manual process handling certificates and provisioning profiles
- Builds have become pretty slow, even with no significant changes in our pipeline 

This does not necessarily mean we cut AppCenter completely, the distribution pipeline is still pretty good. Both for distribution to stores, but also for QA/Ad hoc builds. It also handles CodePush, if we ever want to go that way.

Evaluation criteria for new CI:
- Supports Fastlane
- Supports React Native
- Supports E2E-tests for React Native
- Supports secrets/env variables
- Able to build PRs
- Able to setup multiple builds for the same branch
- Supports build notifications
- (Optional): Supports Slack bot
- (Optional): Integrates well with AppCenter for distribution
- (Optional): Has build badges

Candidates: 
- On-premise box (Mac mini or similar)
- CircleCI
- Bitrise
- Travis CI
- Azure DevOps
- Nevercode
- Github Actions

**Comment by gorandalum** [comment]
Closing as this has been moved to Github Actions.
