### ISSUE TITLE
Language / locales in app

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#264]
Requested features:
- Easy-to-use language file format
- Code is still readable. No need to refer to language files to understand the context. Preferably displaying fallbacks in code.
- Re-render components if language preference changes
- Components inside translations texts, since words do not map one-to-one, and sometimes you need to make a certain word bold or something.
- Editing language makes app hot reload 
- Supports string interpolation
- Detect system language
- Format numbers and dates correctly
- Handle none, singular and plural 
- (Optional): Language file format supported by translation editor software

**Comment by gorandalum** [comment]
Done
