### ISSUE TITLE
Hide login features for NFK

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#2642]
## Origin

_Links to received feedback, user research or other findings._

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by HanneLH** [comment]
Regression test av AtB appen og verifiser at endringene ikke har påvirket den.

**Comment by HanneLH** [comment]
For AtB appen så er "min konto" og logging funksjonaliteten på plass (på begge plassene), så endringen fra NFK har ikke påvirket AtB appen. 
![IMG_0028](https://user-images.githubusercontent.com/104772494/169253298-69632557-8386-43cf-b6e3-9963f1b61507.PNG)
![IMG_0027](https://user-images.githubusercontent.com/104772494/169253310-5688ad1c-15f2-48e2-8abb-271371973788.PNG)
![IMG_0026](https://user-images.githubusercontent.com/104772494/169253314-21023a09-104c-471a-b573-fc9b55994a93.PNG)
![IMG_0025](https://user-images.githubusercontent.com/104772494/169253322-59c20fd1-c7be-42c0-9903-0fba72d66540.PNG)
![IMG_0024](https://user-images.githubusercontent.com/104772494/169253329-aa730ee7-a862-42a0-8305-c68aae851ff8.PNG)
![IMG_0023](https://user-images.githubusercontent.com/104772494/169253331-2c2e3286-c74f-4920-b1d4-944550519c05.PNG)
![IMG_0022](https://user-images.githubusercontent.com/104772494/169253334-025a065b-2924-489c-b7d9-f802dfca74dc.PNG)

**Comment by HanneLH** [comment]
Regression testing on iPhone 11 Pro - Ok.
