### ISSUE TITLE
Remove NFK specific "My Reis" references

### ISSUE THREAD

**Issue by toretefre** [AtB-AS/mittatb-app#2650]
## Origin

NFK wants "My Reis" replaced with My Profile. Makes it more in line with the AtB app, which is always a good thing.

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-mobile-application)

**Comment by toretefre** [comment]
Solved in #2660

**Comment by tormoseng** [comment]
@HanneLH Se at "Min profil" / "My profile" fortsatt ligger som eget menypunkt i appen. Sjekk også at det ser bra ut (likt som de andre menypunktene) i både light/dark mode.

**Comment by HanneLH** [comment]
For Atb appen versjonen ligger "Min profil"/"My Profile" som et eget menypunkt og ser lik ut som de andre menypunktene i light og dark mode. 
![IMG_0003](https://user-images.githubusercontent.com/104772494/169036021-ccf9d0b0-65b2-4940-93ed-9d38fc7ab007.PNG)
![IMG_0004](https://user-images.githubusercontent.com/104772494/169036027-bf377361-efac-49a8-9c97-e51d75933797.PNG)

**Comment by HanneLH** [comment]
Regression test on iPhone 11 Pro - Ok.
