### ISSUE TITLE
[BUG] For avganger&reisesøk så mangler "Forrige" og "Neste" teksten for ved Lightmode 

### ISSUE THREAD

**Issue by HanneLH** [AtB-AS/mittatb-app#2700]
**Describe the bug**
For avganger siden og lyst utseendet så er fargen på knappene "Forrige" og "Neste" hvit så de vises ikke, for dark modus så er de synlig.

**Application version**
Version number: 1.18

**To Reproduce**
1. Go to Avganger
2. Click on en reise fra gjeldene stoppet 
4. See error at "knappene" mangler pga. farge

**Expected behavior**
Vil se "Neste" og "Forrige" teksten.

**Screenshots**
![IMG_4012](https://user-images.githubusercontent.com/104772494/169031161-36588535-1f92-4905-9938-80e2e67c026d.PNG)
![IMG_4013](https://user-images.githubusercontent.com/104772494/169031170-a96f30c5-0c16-4c81-bafb-c0cb540bddab.PNG)
![IMG_4014](https://user-images.githubusercontent.com/104772494/169031178-2661823e-59d6-4bb5-a4aa-70d8380a8536.PNG)

**Smartphone (please complete the following information):**
- Iphone 13 Pro

**Comment by toretefre** [comment]
This one is already fixed in #2684 which is not merged into master yet. Expecting merge this week.

**Comment by HanneLH** [comment]
**Test**
- [ ] Lyst utseende 
    - [ ] Neste/Next vises for avganger og reisesøk 
    - [ ] Forrige/ Previous vises for avganger og reisesøk
- [ ] Mørkt utseende 
    - [ ] Neste/Next vises for avganger og reisesøk 
    - [ ] Forrige/ Previous vises for avganger og reisesøk

**Comment by toretefre** [comment]
Ser ut som dette løses i #2684 ja. Ligger foreløpig på branch "tefre/correct-colours"

**Comment by HanneLH** [comment]
Testet/Verifiser på iPhone 11 pro og nå er Neste/next og Forrige/previous synlig ved lyst utseende på appen og uendret for mørkt utseende.
![IMG_0041](https://user-images.githubusercontent.com/104772494/169467375-1a1421b3-222b-4e76-8864-2680f5e044e3.PNG)
![IMG_0040](https://user-images.githubusercontent.com/104772494/169467393-c11ddeb1-7e3c-47a9-8dd7-b996b9e414ee.PNG)
![IMG_0039](https://user-images.githubusercontent.com/104772494/169467399-080dbbe3-9160-4374-b23d-59f1f3c81463.PNG)
![IMG_0038](https://user-images.githubusercontent.com/104772494/169467402-4e6c43f7-3cfa-4d41-8afd-0889eae4c46b.PNG)
![IMG_0037](https://user-images.githubusercontent.com/104772494/169467405-1fffff39-2218-4d05-8764-bc675212d43b.PNG)
![IMG_0036](https://user-images.githubusercontent.com/104772494/169467407-47c8ade0-14e4-462c-b7c6-cbd23e6aabca.PNG)
![IMG_0035](https://user-images.githubusercontent.com/104772494/169467409-519e1b85-8b8f-45cc-afb1-ce09f4f85c56.PNG)
![IMG_0034](https://user-images.githubusercontent.com/104772494/169467411-4511315c-f2ba-4893-8e8c-3b148e933c76.PNG)
