### ISSUE TITLE
Contribute RN + TypeScript specific SVGR cli changes back upstream

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#295]
Currently patching: 

* https://github.com/AtB-AS/mittatb-app/blob/master/patches/%40svgr%2Bbabel-plugin-transform-react-native-svg%2B5.4.0.patch
* https://github.com/AtB-AS/mittatb-app/blob/master/patches/%40svgr%2Bbabel-plugin-transform-svg-component%2B5.4.0.patch

These are a bit hackish, but basically you want to import `SvgProps` and use that instead of `React.SVGProps<>` if we're converting for RN + TypeScript.

Should contribute these back upstream to https://github.com/gregberge/svgr

**Comment by gorandalum** [comment]
Closing as we do not have any patches for svgr currently.
