### ISSUE TITLE
[Ticketing] Add support for enabling ticketing feature for specific users

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/mittatb-app#301]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
The ticketing feature is currently disabled in production using the feature toggling added in https://github.com/AtB-AS/mittatb-app/issues/191. We want to be able to enable the ticketing feature for specific users first. We therefore need a mechanism for enabling this feature on specific installations of the app in production.

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
Ideas that has been mentioned: 

- Add input field in the "Mitt AtB" tab for a "pilot code" that enables the tickting feature. This code can in the simplest possible implementation be just a shared secret.  
- Add a "secret gesture" that enables the ticketing feature.
- Add login and user permissions.

Other ideas should also be considered in order to solve this issue with as little effort as possible.

**Comment by mikaelbr** [comment]
@cbrevik This can be closed, no?

**Comment by cbrevik** [comment]
Yes I'm unsure why I've moved it to ready for work.
