### ISSUE TITLE
Scooter cluster click sometimes zooms too close

### ISSUE THREAD

**Issue by KristianSelnas** [AtB-AS/mittatb-app#3356]
When clicking a cluster of e-scooters you expect the map to zoom into the scooters comprising that cluster. At (seemingly random) occurrences the map zooms in way to much and the scooters in the cluster end up outside the visible bounds.

**Comment by KristianSelnas** [comment]
The bug occurs when clusters are reported to have only one child (even though they in fact have more). The current fix flies to the clicked cluster but does not change the zoom. The fix is not optimal, but a more thorough fix will require more work.

**Comment by tormoseng** [comment]
Tested OK!
