### ISSUE TITLE
[Feature] Show departures from a stop place that is a part of a route suggestion

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#351]
## Origin
_Links to received feedback, user research or other findings._

Feedback from user:

> Forbedringsforslag: Når du går inn på fanen «Avganger» dukker en liste potensielle avganger opp. Om du klikker på en bestemt avgang vil holdeplasslisten vises. Det er her jeg savner en mulighet til å kunne klikke videre på holdeplassene og få opp avganger fra valgt holdeplass.

> Årsaken er todelt egentlig.
> 1) Om jeg allerede sitter på bussen og ønsker fortløpende å sjekke overgangsmuligheter, eller til planlegging av reise.
> 2) Reiser fra hjem/jobb, men tenker å ta et kort stopp på Sirkus Shopping. Sjekket da neste mulighet for å komme meg videre ved denne metoden. Trenger ikke reiseplanlegger for det, kun sanntid da jeg allerede er kjent med hvilke linjer jeg kan bruke.

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

**Comment by hildeor** [comment]
Løst av #944
