### ISSUE TITLE
[Feature] Add support for bike route suggestions

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#352]
## Origin
_Links to received feedback, user research or other findings._

Feedback from user:
> Kjempefint at gåtid vises i app’en! Men hva med tid for sykkel??

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

**Comment by gorandalum** [comment]
Closing until this come up more often in Intercom feedback.
