### ISSUE TITLE
[Feature] Calendar event

### ISSUE THREAD

**Issue by haugsand** [AtB-AS/mittatb-app#360]
## Origin
_Links to received feedback, user research or other findings._

Tilbakemelding fra bruker:

> Evt. også mulighet for å legge reisen inn i kalender-appen for å lettere kunne planlegge gjøremål, møter og fritidsaktiviteter opp mot kollektivreisen til og fra.

> I forhold til det med kalenderhendelsen tenkte jeg at man da får muligheten til å legge den inn som en kalenderhendelse når man planlegger turen, og om man planlegger en tur vil kalenderhendelsen først bare gi et estimat i forhold til hvor lang turen vil være men at den oppdateres etterhvert som turen nærmer seg slik at man får det nyeste estimatet inn i kalenderen. En link inne på eventen som tar en til en sanntidstabell på atb.no for den aktuelle reisen eller liknende hadde også vært stilig. Kanskje muligheten til å legge inn en «fast» kalenderhendelse for de som reiser til det samme stedet til ca. samme tid til jobb og liknende hadde vært noe?

> På lengre sikt kunne man jo evt. også gjort det slik at atb appen kommer med forslag til når en bør reise hjemmefra i tilknytning til kalenderhendelser man har som f. eks. møter eller fritidsaktiviteter med bestemte lokasjoner/destinasjoner knyttet til dem.

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

**Comment by gorandalum** [comment]
Closing until we receive more feedback about this from Intercom.
