### ISSUE TITLE
[BUG] More visible stop names in nearby

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#362]
**Describe the bug**
> Hadde vært fint om man kunne gjøre holdeplassnavnet altså i dette tilfellet (Ringve Skole) litt mer tydelig kanskje i bold og større skrift. Forsvinner litt synes jeg. Hadde også vært fint om man kunne f.eks.

Handled by another feedback (duplicate)
> Trykke på holdeplassnavnet for å så få en utvidet tabell, så man kan scrolle seg lengre ned i rutetabellen i stedet for at man kun kan se de 5 kommende bussene (egentlig sånn som dagens sanntidsapp har).

**Comment by gorandalum** [comment]
Closing as outdated.
