### ISSUE TITLE
Click header to scroll up?

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#377]
iOS supports clicking custom bar to scroll up, and that is the recommended pattern. 

Some apps like Twitter supports scrolling up when clicking the header in a screen (which is under the status bar). But that is not necessarily a pattern everyone uses.

But since our Assistant-header now includes the search parameters, would our users expect to scroll back to the search form on top when clicking the header?

![image](https://user-images.githubusercontent.com/4932625/89269308-05aea400-d63a-11ea-95be-5665c8e27fbd.png)

**Comment by gorandalum** [comment]
Closing until we receive more feedback about this from Intercom.
