### ISSUE TITLE
[Feature] Accessible app (technical)

### ISSUE THREAD

**Issue by rikkekantega** [AtB-AS/mittatb-app#391]
## Origin
_Links to received feedback, user research or other findings._

This is a requirement. Application content must be accessible, at least WCAG 2.1 level AA compliant.

## Motivation
_A short description of what user needs or business goals this feature will solve._

The application must be accessible for users, regardless of functional impairments

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

[See Difis list on requirements here](https://uu.difi.no/krav-og-regelverk/wcag-20-standarden) (use frontend/backend filter to get the most relevant results)  

Minimum technical requirements include:
- Provide alternative text and/or role/purpose for elements, where this is not given by the native type.
- Provide alternative text/label to elements that elsewise require visual interpretation
- Make sure elements are focusable when they can be interacted with.
- Provide shortcuts to navigation and main content
- Make sure zoom to at least 200% (or equivalent font resizing) work on all views

**Comment by gorandalum** [comment]
Closing as we have improved the accessibility in app.
