### ISSUE TITLE
[BUG] Non-optimal trip pattern suggested for what should be a basic trip 

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#403]
**Describe the bug**

Context: https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/4168300/conversations/159245400000166

> Hvorfor ikke bytte i Tonstadkrysset der jeg ikke hadde hatt behov for å krysse veien?

![image](https://user-images.githubusercontent.com/4932625/90866970-ee3f1d00-e394-11ea-9139-9ee13a7428b7.png)

**Application version**
Version number: 1.0

**To Reproduce**
1. Search from "Okstadplassen"
2. To "Prinsens gate"
3. Note that one of the alternatives is to switch bus at Rostengrenda

**Expected behavior**
Switching at the stop before, Tonstadkrysset, is a much better alternative since you don't have to walk as nearly far.

**Comment by gorandalum** [comment]
Utdatert
