### ISSUE TITLE
[Feature] More advanced favorites

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#420]
## Origin
User test 2020-09-02 https://www.figma.com/file/nFD6PySDnHKSBO1aRINFn2/Brukertesting-02092020?node-id=95%3A59

> - Flere ville opprette/stjerne favoritter direkte fra søk eller søkeresultat 
> - Noen ønsker å lagre strekninger, eller linjer, eller reisesøk som favoritt

[Usability test with Blindeforbundet, 29.10.2020](https://github.com/AtB-AS/innsikt/blob/master/brukertester/2020-10-29_Blindeforbundet.md#favoritter). 

> Kunne velge plattform som favoritt

> Kunne legge til favoritter fra kontekst (eks: fra reiseassistent adressesøk eller i avganger: rute, plattform)

> Ønsker å redigere rekkefølgen på favorittene

Feedback via Intercom

> Savner muligheten til å lagre favorittreiser

> Men av og til vil man bare se én bestemt linje. Jeg søkte eksempelvis fra P2 til Østmarkveien og da vil jeg bare se treff for linje 20

> Er det mulig å legge inn filter på vis avganger slik at jeg kan toggle mellom visning av «mine avganger» og «alle avganger». Eks som regel er jeg bare interessert i linje 3 fra K1, men av og til vil jeg se alle avgangene

> Mulighet for å sortere rekkefølgen på favorittsteder hadde også vært kjekt

> Ønsker en mulighet for å kunne filtrere hvilke busser jeg vil se. F.eks kan jeg bare ta en buss hjem fra Hesthagen, og hvis det er 10 min til bussen går kommer den ikke opp på listen blant alle bussene fordi det er så mange som passerer holdeplassen. Jeg trenger ofte de 10 minuttene for å komme meg dit, så hadde vært fint med en enklere måte å finne "min" buss på.

> Hadde vært kjekt med ny type widget slik at favorittreise kan vises widget

See #320

## Motivation
During user tests, several users have commented that they'd like more options with favorites. We are also seeing feedback coming via Intercom about filtering options that aren't relevant.

## Hypotheses and assumptions
- Users who travel with the same lines or stops every day want a quick way to search for trip patterns or see departures
- Starring/saving favorites directly from search result seems like a pattern which users are familiar with from other apps like AtB Reise, Bartebuss, Entur and Ruter
- Other apps have other options when saving favorites as well, like only certain lines for certain stops which are frequently used
- The needs differs per user depending on how they usually travel. 
- Some users live near city centers, and use the same lines everyday, and might only be interested in seeing a few lines for certain stops in the Nearby-screen. They might not need to transfer between lines in their journey.
- Other users live further away from work or other activities, and might need to transfer between lines. The transfers might change depending on the time of the day, and they need to search in Assistant-view to find the optimal trip. These users might be more interested in saving a from/to-search as a favorite.  

## Proposed solution

We are expanding the favorite functionality, and therefore also differentiating between types of favorites.

### Steder (Places)
Context: In the context of performing a search.
What: Place, address, or stop
User motivation: Perform a search between places I often visit. See departures in proximity to places I often visit.
Possible explorations: Custom ordering of favorites

### Strekninger (Journeys)
Context: In context of journey results
What: Save search between two places (notice difference between saving a search and a specific search result. The latter would have an expiry.)
User motivation: Reuse a journey search
Possible explorations: Favorite journeys as widgets

### Departures
Context: In context of departures from a specific quay
What: A line from a specific quay
User motivation: Filter away lines that aren't relevant. See preferred routes from different stops.
Possible explorations: Next departures on favorite lines as widget, shortcuts from landing page in app - view next departures from my favorite lines, service messages based on favorite lines.

### Tickets
Context: In context of journey results and departures
What: number, type, category, zone
User motivation: Buy often used ticket combinations
Possible explorations: Buy favorite ticket - widget. Buy favorite tickets in context (e.g. travel search).

![Konsept - Favoritter - Favoritter](https://user-images.githubusercontent.com/8980523/98106352-92673900-1e99-11eb-8ad5-c35703cda867.jpg)

**Comment by pettersuul** [comment]
Foreslåtte løsninger er løst og i produksjon
