### ISSUE TITLE
[BUG] When deleting the profile, navigate to profile screen fails

### ISSUE THREAD

**Issue by jorelosorio** [AtB-AS/mittatb-app#4206]
**Describe the bug**
When trying to delete a user from my profile, it tries to redirect the user to the profile view, but it is failing and breaking the app, since the navigation is no longer on the same state due that as soon as the user in logout the state of the app is refreshed.

**Application version**
Version number:  1.47

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to My profile
2. Click on 'Edit My Profile'
2. Click on 'Delete My Profile'
4. App should crash

**Expected behaviour**
Go to Assistant / Profile tab

**Comment by Sebstorvik** [comment]
@tormoseng @HanneLH Could you test this and check which versions it happens on?

**Comment by tormoseng** [comment]
Tested:
- latest master in Staging: OK. Ends up on the frontpage
- latest 1.46 release in Prod: OK. Ends up on the frontpage

Adds a point to the 1.47 QA issue to test delete profile when 1.47 is ready.

**Comment by tormoseng** [comment]
Re-tested latest 1.47 in Staging now, and deleting an account works well.

Will re-test in Production when 1.47 is available there.
