### ISSUE TITLE
[Feature] More info about line transfers and available time in Assistant overview

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#421]
## Origin
_Links to received feedback, user research or other findings._

User test 2020-09-02 https://www.figma.com/file/nFD6PySDnHKSBO1aRINFn2/Brukertesting-02092020?node-id=95%3A59

> - De fleste uttrykte et ønske om å se bytte og/eller overgangstid i søkeresultat for å gjøre kjappe vurdering på alternativene. Noen nevnte spesifikt uten å måtte gå inn på detaljer. Bytte av buss ser ut til å være noe de ønsker god informasjon om.

## Motivation
_A short description of what user needs or business goals this feature will solve._

Some users who travel longer routes, and who usually have to transfer between buses, needs to quickly evaluate which of the suggested trips are the most optimal. With the updated design, we display most of the line transfer and transfer time information within the trip details. 

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

If the users have to navigate back and forth between the search results and trip pattern details to find the best trip, this might make for a worse user experience.

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

Either display more about line transfer and transfer times in the search results overview, or make it easier to navigate between trip pattern details to see different alternatives. One issue with the latter is that the information hierarchy in the detail screens is quite complex, so it might not be enough to give users a quick overview when browsing the alternatives.

**Comment by rikkekantega** [comment]
App 1.0 Design closes this, https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=0%3A1
