### ISSUE TITLE
[Feature] Add custom reload animation 

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#460]
## Origin

Extracted from #231. Write custom animation for loading indicator.

Example: 
![Searching](https://user-images.githubusercontent.com/606374/93430627-3fbec700-f8c3-11ea-8fd9-83a9080226ec.png)

See link: https://www.figma.com/file/P624oig7YgUQIbz7uFwdHw/App-0.9?node-id=0%3A1

**Comment by monopoint** [comment]
@mikaelbr @pettersuul 
Is this issue about animating a wave as a loading indicator as a replacement for the RN pull-down spinner?

**Comment by vidtil** [comment]
Tittelen må oppdateres til å uttrykke hva vi oppnår ved å prioritere denne saken.
