### ISSUE TITLE
[Feature] Change voiceover reading order on address search result

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#489]
## Origin
[Usability test with Blindeforbundet, finding 4.](https://github.com/AtB-AS/innsikt/blob/master/brukertester/2020-09-23_Blindeforbundet.md#4)

<img width="439" alt="Skjermbilde 2020-09-30 kl  10 01 13" src="https://user-images.githubusercontent.com/8980523/94659011-ef545a00-0303-11eb-86e1-72bafda51142.png">

> Voiceover leser først “flyplass, togstasjon, buss” før den kommer til navnet “Trondheim lufthavn”.

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

- Assume that station name is more relevant than type

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

Change the voiceover order to:
1. name ("Trondheim lufthavn")
2. place ("Stjørdal")
3. type ("train, airport, bus")
4. button

**Comment by monopoint** [comment]
saken er utdatert og ikke lenger aktuell
