### ISSUE TITLE
[Feature] Accessibility issues with favourites

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#491]
## Origin
[Usability test with Blindeforbundet, 23.09.2020, finding 8.](https://github.com/AtB-AS/innsikt/blob/master/brukertester/2020-09-23_Blindeforbundet.md#8)
> Problemer med både forstørring av tekst og bruk av voiceover: Lagrede favoritter er ikke synlig når tekst er forstørret veldig (blir dyttet ut av viewet). Horisontal scroll fungerer ikke i voiceover-modus. I tillegg forsvinner labels når tekst forstørres.

<img width="426" alt="scaling" src="https://user-images.githubusercontent.com/8980523/94661212-0e082000-0307-11eb-8041-d4a72c5dfd5a.png">

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

- The background should scale with text so that the button label is visible
- Horizontal scroll in voiceover mode

**Comment by monopoint** [comment]
saken er utdatert og ikke lenger aktuell
