### ISSUE TITLE
[UserNeed] Ønsker å se avganger lenger fram i tid

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#492]
## Origin
1. [Usability test with Blindeforbundet, 23.09.2020, finding 10.](https://github.com/AtB-AS/innsikt/blob/master/brukertester/2020-09-23_Blindeforbundet.md#10)

> Synes det er vanskelig at det er så få avganger som vises under "Vis flere" på plattformen. Ønsker å kunne bla langt frem i tid.

2. Feedback via intercom

> Har enda et ønske! Digger at dere har lagt til knapp for «se flere avganger» men kunne ønske meg at man kan trykke på denne knappen et uendelig antall ganger så man kan bla seg langt ned, foreløpig er det kun mulig å trykke 3 ganger. 😉
[Intercom](https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400000332#part_id=comment-159245400000332-6592587287)

> Liker ikke at man bare kan se ett visst antall adganger! pluss veldig knotete at begge plattformene er under hverandre. Begge går i motsatt retning, så ikke nødvendig å se plattformen jeg ikke skal gå på!
[Intercom](https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400000349#part_id=comment-159245400000349-6592574449)

> Forbedringsforslag: når man søker opp avganger eller reisesøk, så bør det være mulig å bla langt nedover for å se flere forslag. Nå vises kun de ti første.

## Motivation
The user wants to be able to plan trips well in advance

## Hypotheses and assumptions
Todays departures is limited to 15 departures pr. platform. This user need is probably not solved entirely by just increasing the number of items in the departures list, but might work as a short term relief. 

## Proposed solution
Suggest that we explore alternative ways of solving this need by design. Some ideas to explore:
- Horizontal departures sorted by line. E.g. one row would consist of bus line nr. 2, with departure times in a horizontal layout.
- Adding a time-filter

**Comment by vidtil** [comment]
Lukker denne siden den er gammel, og refererer til et tidligere design som har blitt endret. Forbedring av avganger-bildet basert på gjeldende design følges opp i denne saken: https://github.com/AtB-AS/mittatb-app/issues/1394
