### ISSUE TITLE
[Feature] Add voiceover hint that journey summaries and departures are clickable for details

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#493]
## Origin
[Usability test with Blindeforbundet 23.09.2020, finding 11.](https://github.com/AtB-AS/innsikt/blob/master/brukertester/2020-09-23_Blindeforbundet.md#11)

> Ikke intuitivt for alle at man kan trykke på avgangen for å få opp info om traséen.

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

Tiltak Legge på voiceover-hint om at man kan klikke på både reiseruter og avganger for å få opp detaljer om reisen

Add voiceover hint that indicates that both journey summaries and departures are clickable for more details.

**Comment by mikaelbr** [comment]
Wonder if this might be fixed now?

**Comment by hildeor** [comment]
Seems this is fixed.
