### ISSUE TITLE
[Feature] Voiceover adjustments to "add favorite" form

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#494]
## Origin
[Usability test with Blindeforbundet, 23.09.2020, finding 13.
](https://github.com/AtB-AS/innsikt/blob/master/brukertester/2020-09-23_Blindeforbundet.md#13)

~Ulogisk rekkefølge på voiceover. Label for "sted" leses opp etter adressen.~
~Dropdown for å velge ikon mangler beskrivende voiceover. Ikke tydelig hva denne gjør.~

[Usability test with Blindeforbundet, 29.10.2020]()

> Ikon-select skalerer ikke opp slik som de andre inputfeltene ved tekstforstørring

> Følgende knapper mangler rollen "knapp": "Legg til favorittsted", "Lagre favorittsted", "Slett favorittsted".

~Får ikke til å velge emoji~

~Etter man har skrevet inn og valgt adresse så hopper fokus forskjellige steder. testet 2 ganger og ene gangen hoppet fokus til Ikon-velger, andre gangen hoppet fokus til Avbryt-knapp~

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

- Change voiceover for Ikon-select:
"Ikon for favoritt, {nedtrekksliste}(or whatever is the word corresponding to the correct role here). Dobbeltrykk for å redigere"

- Select/dropdown should scale up in size as the input fields for Sted and Navn does.

- Add roles to the following buttons:
"Legg til favorittsted"
"Lagre favorittsted"
"Slett favorittsted"

- Make emojis selectable with screen reader

- After selecting address when adding new favorite, focus should jump to the next hierarchical element (Navn).

**Comment by monopoint** [comment]
testet, og denne er fortsatt aktuell.
Flytte til Ready?

**Comment by hildeor** [comment]
Virker som det meste her er fikset.
