### ISSUE TITLE
[Feature] Components screen in app (for QA purposes)

### ISSUE THREAD

**Issue by rikkekantega** [AtB-AS/mittatb-app#507]
## Origin
_Links to received feedback, user research or other findings._
Discussed in #60 . A proposed improvement for design QA on app components could be outputting common components in a dedicated app screen. 

## Motivation
_A short description of what user needs or business goals this feature will solve._

Easier or more efficient design QA
Automated testing

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

One app screen that uses all common components will serve as future code documentation of which components are common/reusable (look up usage)

One app screen that display all common components will establish a better shared understanding between designers and developers on which design elements serve as common components and not.

One shared screen alllows for faster QA on changes to components

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

Perhaps to be discussed further before proposing how to solve this.

**Comment by cbrevik** [comment]
Løst delvis via Design System-knappen i Profil
