### ISSUE TITLE
Emoji rendering on Android 4.4 is not working

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#52]
**Describe the bug**
Right now no emojis are shown on Android 4.4. Seems to be an issue with showing Unicode Emojis all together, even though we are limiting the emoji version, Android 4.4 won't show any emoji code from React Native.

Not sure why this is the case yet, but prioritizing progress for now and noting this as an issue we will need to consider in the not distant future.

**To Reproduce**
1. Go to Mitt AtB
2. Click on Legg til favorittsted
3. Click on Symbol
4. See missing emojis.

**Expected behavior**
Emojis should be visible

**Screenshots**
<img width="490" alt="Screenshot 2020-03-12 at 09 39 42" src="https://user-images.githubusercontent.com/606374/76503060-6946f380-6445-11ea-9de9-82d14cd4a582.png">

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android KitKat 4.4

**Comment by gorandalum** [comment]
Closing this as it will probably not be prioritised the next months/year. Reopen if users report that this is not working.
