### ISSUE TITLE
[BUG] Intermittently slow geolocation on iOS

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#561]
**Describe the bug**
From Intercom: https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400000356#part_id=comment-159245400000356-6674848573

> Har lagt merke til at det tar lang tid for appen å finne posisjonen min siden forrige oppdatering.

**Application version**
Version number: 1.0

**To Reproduce**
Unsure yet how to reproduce. I have noticed it most when I haven't used the device in a while. It seems to be related to upgrade to iOS 14.  

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 14.0+

**Additional context**

**Comment by vidtil** [comment]
Lukket saken siden vi ikke har fått flere henvendelser om dette.
