### ISSUE TITLE
[Feature] Navigation and setting focus

### ISSUE THREAD

**Issue by rikkekantega** [AtB-AS/mittatb-app#562]
## Origin
_Links to received feedback, user research or other findings._

We are observing several problems on how focus is set after navigation and upon opening modals:

iOS observations:

- When navigating between onboarding screens: 
Voiceover focus is moved to the element closest to the previous clicked element, not to the views first accessible element or header (as would be expected)

- After opening a new modal, previous focused element in last screen regains focus for a brief moment, before contents in opened modal gains focus (read further on these observations: #552 and #545)

Both platforms observations:
- First focused element isn't always what would be expected or user friendly (back-/close icon)

## Motivation
_A short description of what user needs or business goals this feature will solve._

Useability and accessibility is the main motivation. 
At least we need to be compliant with WCAG 2.0, where guideline **[2.4 Navigable](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=243#navigable)**, and especially **2.4.3 Focus order level A** are especially relevant. 

_Note that the WCAG guidelines are written with web in mind. By definition of the Norwegian law, our app is considered a "web page". So we need to translate/understand the intention of the guidelines to what applies when in app context_

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

Focus in an order that preserves meaning and operability is extra important for:
- Visually impaired users
- People navigating using assistive technologies 

View header is considered the main/first logical element of a view. 
When a view header does not exist, the first upper left visible accessible element should logically be the first element in focus.
A back/close button should never be considered the main/first focusable element after navigating into a view

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

After navigating from one screen to another, the focus is moved to the main element of the new view.

**Comment by pettersuul** [comment]
Håndteres via #1073
