### ISSUE TITLE
[Feature] Indicate outcome of clicking favorite in "Mitt AtB" tab

### ISSUE THREAD

**Issue by rikkekantega** [AtB-AS/mittatb-app#572]
## Origin
_Links to received feedback, user research or other findings._

Found when testing screen reader support:
When a favorite is selected, the name and address is read out loud, but there is no hint on what clicking/activating it will do. Activating the favorite navigates to the "Avganger" screen, using the favorite as location.

![Screenshot_1602666841](https://user-images.githubusercontent.com/61825573/95969277-c9a07800-0e0e-11eb-906e-7ec38dc176f0.png)

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

**Comment by mikaelbr** [comment]
This should no longer be valid
