### ISSUE TITLE
[BUG] Excessive battery usage and background gps with map?

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#588]
**Describe the bug**

Issue detected by user:
> Ville bare nevne at jeg får varsel på min Samsung om at appen bruker mye batteri i bakgrunnen. Dette er uheldig da mange er veldig påpasselig med hvilke apper de bruker og kan fort avinstallere om appen bruker mye strøm. Det virker som om appen fortsatt "tracker" (gps/posisjon) i bakgrunnen om jeg legger ned appen mens den er i kart-modus.

Seems to use a lot of battery and also when inactive. This is not intended behavior. Also seem to use GPS when inactive. Also not as intended. Might be the implementation of MapBox which causes this behavior. 

**Application version**
Version number: 1

**Smartphone (please complete the following information):**
 - Device: Samsung - SM-G950F
 - OS: Android 7.0

**Comment by monopoint** [comment]
Klarer heller ikke å gjenskape denne hverken på emulatorer eller hardware. Posisjonering er kun aktivt når appen har fokus og er i forgrunnen. med en gang appen legges ned, stanser posisjonering.
Det tyder på at dette nok er spesifikt for denne brukeren, og denne saken kan lukkes.
