### ISSUE TITLE
[BUG] Skjermleser håndterer ikke endrede avgangs-/ankomsttider på en forståelig måte

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#621]
## Origin
_Links to received feedback, user research or other findings._

[Usability test with Blindeforbundet, 29.10.2020](https://github.com/AtB-AS/innsikt/blob/master/brukertester/2020-10-29_Blindeforbundet.md#5)

> Tidsendringer leses opp etter hverandre uten noe skille på hva som er hva. For eksempel hvis man gjør et reisesøk og man venter noen minutter så har tidspunktene oppdatert seg. Tidspunktene blir da lest opp som: 12:42 12:39.
![IMG_DB8A2ADBBE30-1](https://user-images.githubusercontent.com/8980523/97706900-b8b26080-1ab6-11eb-9afb-57a2419b7804.jpeg)

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

Screen readers should ignore times that are outdated. Most important is the new time.

**Comment by hildeor** [comment]
Må sjekke om dette fortsatt er tilfelle

**Comment by monopoint** [comment]
denne er fikset i en tidligere commit
