### ISSUE TITLE
[Improvement] Ta bort knapp pil-knapp for å autofylle inn tekst fra søkeresultat

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#627]
### Observasjon
Bedre synlighet på "fyll inn"-knapp/ikon. Kan den gjøres større? Annen bakgrunnsfarge?
Justere størrelse på fokusflaten. Slik det er nå så må man treffe veldig presist i høyre kant av skjermen for å få aktivert knappen. 

### Avklaring
Det er uklart hvor nyttig denne knappen er, og vi antar at den fører til mer støy enn nytte. Knappen fjernes.

**Comment by vidtil** [comment]
Skalerer nå med tekststørrelse. Nytteverdien og "forståelighet" av denne knappen bør avklares.

**Comment by hildeor** [comment]
Foreslår å fjerne denne funksjonaliteten da den ikke virker å være et spesielt innarbeidet mønster?

**Comment by monopoint** [comment]
Fjerner knappen

**Comment by tormoseng** [comment]
Testet OK i staging på iOS og Android
