### ISSUE TITLE
[BUG] Skjermleseren annonserer at søkeresultater er lastet når man nullstiller søket

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#631]
### Observasjon
Nå man klikker ATB-logoen etter å ha gjort et søk, sier skjermleseren at søkeresultater er lastet inn

1. aktiver skjermleser
2. Naviger til reiseassistent
3. Gjør et søk med fra og til 
4. Observer at skjermleseren sier "søkeresultater er lastet inn"
5. Klikk ATB-logoen
6. Observer at Søkeresultatene lukkes og du er tilbake til startsiden for Reiseassistent og at ingen søkeresultater vises
7. Observer at Skjermleseren feilaktig sier "Søkeresultater er lastet inn" 

### Analyse
Skjermleseren annonseser søkestatus når state endrer seg. Når vi resetter søket, setter vi 'fra' som geoposisjon og 'til' som null. det tolker søkemotoren som at det ikke skal søkes, og Assistenten tolker det som at vi skal lukke søkeresultatene og gå tilbake til start. Skjermleseren tolker det som at state er endret, og annonserer siste søkestatus som ofte er "Søkeresultatene er lastet".

### Løsning
Når søke-komponenten tolker det slik at et søk ikke skal utføres selv om state er endret, settes søkestatus til tom streng for å resette søkestatus.

**Comment by tormoseng** [comment]
Ser/Høres greit ut på iOS og Android
