### ISSUE TITLE
[Feature] Communicate upcoming features in beta to engage users

### ISSUE THREAD

**Issue by rikkekantega** [AtB-AS/mittatb-app#635]
## Origin
_Links to received feedback, user research or other findings._

Many user seem to quit using the app.
## Motivation
_A short description of what user needs or business goals this feature will solve._

Improve user retention
Engage users

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

Communicate upcoming / in work features, perhaps through the open space on app front page
Figma / App 1.0 / Assistant: https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=2172%3A0
Figma / Components 1.0 / Infobox: https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components-1.0?node-id=838%3A20

![image](https://user-images.githubusercontent.com/56530785/100353515-e5db2b80-2fee-11eb-8cb0-80f71079489d.png)

**Comment by pettersuul** [comment]
![Screenshot 2020-11-24 at 11 54 18](https://user-images.githubusercontent.com/56530785/100085000-ca83eb00-2e4b-11eb-9993-8ec3c1bb466f.png)

**Comment by pettersuul** [comment]
If we are using illustration with AtB-colors, we may need to have both dark- and light-mode versions available.

**Comment by pettersuul** [comment]
![Uploading image.png…]()

**Comment by gorandalum** [comment]
Some conclusions after a talk at the office:
- First version only text, no image.
- Use Firebase as source.
- Provide Norwegian and English version of the text.
- Allow optional link, and Norwegian and English link text. Not support inline links, but a "Read more" link at the bottom.

Thing mentioned, but not implemented for the first version:
- Image
- Possibility for the user to cross out the message box
- Different styling for more important/critical messages
