### ISSUE TITLE
BFF data wash requirements

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#66]
Reference issue for stuff the app might need from BFF when discussing future work on the API:
- Fix lat/long coordinates to a standardized format, to avoid bugs: https://github.com/AtB-AS/mittatb-app/pull/54#discussion_r393708771
- Consider another API payload format for bus/legs which includes sane paths for bus name retrieval: https://github.com/AtB-AS/mittatb-app/blob/c22346ef07d4db99f4a13881dc35786c0733d627/src/screens/Planner/Overview/ResultItem.tsx#L51

**Comment by gorandalum** [comment]
Closing as it is not actively used as a reference issue.
