### ISSUE TITLE
[Designsync] Update assistant input pattern

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/mittatb-app#668]
- More padding on input
- Move swap button
- More padding between inputs and buttons
- Update buttons (see issue #667)

Figma / Components 1.0 / Inputs https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components-1.0?node-id=0%3A1
Figma / App 1.0 / Assistant https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=0%3A1

![image](https://user-images.githubusercontent.com/56530785/98684765-dad59980-2366-11eb-8a7c-e100ea5c875b.png)

**Comment by mikaelbr** [comment]
Missing new button color scheme system with accent. Marking as blocked for now.

**Comment by mikaelbr** [comment]
@rikkekantega Did you look into this with the button color for new date input? Is that part of the designsync meeting this week? As in, should we close this in favor of #675

**Comment by rikkekantega** [comment]
> @rikkekantega Did you look into this with the button color for new date input? Is that part of the designsync meeting this week? As in, should we close this in favor of #675

Yes, I did, should be solved by #675

**Comment by mikaelbr** [comment]
Perfectos!
