### ISSUE TITLE
[Designsync] Update departure input pattern

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/mittatb-app#669]
- More padding on input

Figma / Components 1.0 / Inputs https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components-1.0?node-id=0%3A1
Figma / App 1.0 / Departures https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=4%3A982

![image](https://user-images.githubusercontent.com/56530785/98684910-0789b100-2367-11eb-97bf-5278eeeb4c3b.png)

**Comment by mikaelbr** [comment]
@pettersuul Isn't this solved in 1.4 (in Store) now?
