### ISSUE TITLE
[Feature] Go straight to search when adding favorite

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/mittatb-app#674]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

Simplify process of adding a favorite

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

The only required field for a favorite place is a place. By sending the user directly to the place-search we may avoid misunderstandings about which inputs to use.

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

When the user adds a new favorite, the first step of the process is to search for a place/stop

Figma / App 1.0 / Action / Favorite https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=8%3A1529

![image](https://user-images.githubusercontent.com/56530785/98686555-fcd01b80-2368-11eb-8068-296382bdda0a.png)

**Comment by mikaelbr** [comment]
Blocked as part of changes from #755
