### ISSUE TITLE
[Feature] New datetime view

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/mittatb-app#675]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

Make selecting a time and date more accessible and consistent across platforms.

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

Current method of datetime selection is not accessible on android (also not great on iOS). By placing this on its own page it will be simpler to use native pickers.

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

During a journey-search, the user may press a button (default: "Avreise nå (##:##)") to open a view/subview which contains controls to select a departure or arrival time.

Figma / App 1.0 / Action / Datetime https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=1818%3A491

![image](https://user-images.githubusercontent.com/56530785/98686911-6d773800-2369-11eb-84dd-49a639fed4ea.png)

**Comment by rikkekantega** [comment]
Waiting on button design sync to complete this
