### ISSUE TITLE
[Feature] Expandable stops on departure view

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/mittatb-app#676]
## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

Avoid overloading the user with irrelevant info.

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

If the user searches for departures using GPS, we assume the most relevant result is the closest. By hiding the contents of the other results we also make it easier for the user to select more relevant stops.

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

When listing results for a departure-search using GPS, expand first result and minimize others. When user expands other results, minimize previously expanded result.

Figma / App 1.0 / Departures https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=4%3A982

![image](https://user-images.githubusercontent.com/56530785/98687153-b4652d80-2369-11eb-975c-59bafd93719e.png)
****

**Comment by mikaelbr** [comment]
Should be solved as a part of #775.
