### ISSUE TITLE
[BUG] Status message in service journey details does not wrap properly

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#679]
**Describe the bug**

> Feilmeldingen kommer utenfor skjermen, kunne også sett for meg bedre synlighet over hvilken holdeplass som er stengt, som å stryke over, annen skriv eller noe lignende

![image](https://user-images.githubusercontent.com/606374/98730376-7af9e580-239c-11eb-9069-2a71394845a5.png)

**Comment by hildeor** [comment]
@gorandalum Har du observert om dette fortsatt er tilfellet?

**Comment by mikaelbr** [comment]
Antar denne er fikset
