### ISSUE TITLE
[Feature] Add favorite departures

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/mittatb-app#680]
## Origin
_Links to received feedback, user research or other findings._

See issue #420 

## Motivation
_A short description of what user needs or business goals this feature will solve._

Allow the user to save a frequently used departure.

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

Many users use the same line every day from the same stop, and want to easily find these departures.

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

## Acceptance Criteria
- [ ] Able to add favorite.
- [ ] Favorites are persisted after app restart.
- [ ] I can remove favorite by toggling star.
- [ ] Able to filter on favorites nearby, by address search and from different quays.
- [ ] Able to add favorites from all types of transportation modes and quays.
- [ ] As a user of screen reader I can navigate and easily understand favorites and how to toggle between.
- [ ] Works as expected in dark mode.
- [ ] (Is translatable to English)
- [ ] Does not drain battery
- [ ] Works in up to 200% font size

Adding:
- "Star" from departures view
![image](https://user-images.githubusercontent.com/56530785/98776519-5da23700-23ef-11eb-8d43-1f2deb55ebc9.png)

Using:
- Filter toggle on departures screen
- Toggle only shown if current results contain a favorite
![image](https://user-images.githubusercontent.com/56530785/98776574-7874ab80-23ef-11eb-9de8-2b128dfa7454.png)

Figma / App 1.0 / Favorite https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=8%3A1529
Figma / App 1.0 / Departure https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=4%3A982

**Comment by mikaelbr** [comment]
Should split into two tasks: "Mitt AtB" and Departures view.

**Comment by mikaelbr** [comment]
[Relevant feedback for work](https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400001475):
> På passeringstider. Er det hensiktsmessig å visse 6 passeringer på den ene plattformen før man presenterer første avgangpå den man står på.

**Comment by rikkekantega** [comment]
The last 4 (5) acceptance criterias should probably just be provided be as defaults in the issue template! :D
