### ISSUE TITLE
[Ticketing] Rewrite "time left" bar on ticket to include animation etc 

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#698]
Leftover from #601 Rewrite "time left" bar to include diagonal lines and animate, to match actual https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=1786%3A5496

**Comment by gorandalum** [comment]
@pettersuul made an animated prototype here:
https://www.figma.com/proto/WI8NjHPW8ZchtTHn96ATtp/Ticketing?node-id=150%3A4827&viewport=1333%2C868%2C1.6716327667236328&scaling=min-zoom
