### ISSUE TITLE
[Feature] Mulighet for å lagre planlagt reise som favoritt

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#713]
### Tilbakemelding

https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/4207849/conversations/159245400000934

> 2. Når jeg planlegger enkeltreiser frem i tid så savner jeg muligheten til å lagre selve reisen som favoritt, slik at jeg lett finner den igjen. Slik det er nå må jeg drive å ta skjermdump. Bergen sin app har dette alternativet, og er kjempenyttig!

**Comment by vidtil** [comment]
Dekkes muligens av https://github.com/AtB-AS/mittatb-app/issues/957?

**Comment by monopoint** [comment]
ja, jeg oppdaterer #957 og lukker denne.
