### ISSUE TITLE
[Improvement] Gjøre det enklere å velge ikon for favorittsted

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#718]
## Origin
_Links to received feedback, user research or other findings._
Feedback from Intercom:

> Når jeg skal velge ikon under favorittsted burde det komme vanlig tastatur for emojis som når man velger navn på linja over. Det er vanskelig og tungvint å navigere i emojisene når man ikke kam velge emojikategori, om du skjønner. Man må scrolle heeele veien ned for å finne et hus f.eks :)

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

An improved solution for picking emojis could be a search field and/or include emoji categories.

**Comment by monopoint** [comment]
For å bøte på denne konkrete tilbakemeldingen fra bruker kan vi sortere om kategoriene for emojis, slik at Reise og aktiviteter kommer i toppen.
Forøvrig har emoji-keyboardet vi bruker et par mangler. 
- På android vises ikke alle emojiene, men man får et kryss istedet. Dette gir et dårlig inntrykk av kvalitet.
- Det er ikke mulig å søke
- Det er ikke mulig å navigere mellom kategorier, man må alltid scrolle scrolle scrolle for å finne rett kategori og emoji

Jeg foreslår at vi leter etter et alternativ til dette emoji-keyboardet

**Comment by hildeor** [comment]
Jeg tenker denne ikke er så viktig å prioritere til juni? @vidtil

**Comment by monopoint** [comment]
Denne har et knippe accessibility problemer som bør fikses og oversettelser mangler.
Og fikse denne skikkelig er et litt mer omfattende arbeid, men vi kan quickfixe a11y og oversettelser.
