### ISSUE TITLE
[BUG] Navigating in map without location activated?

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#722]
**Describe the bug**
Intercom: https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/4207849/conversations/159245400000995

> [...] mulighet til å scrolle i kart uten å dele posisjon

No further details. Need to investigate if this is the case.

**Smartphone (please complete the following information):**
```
 Atb device location enabled
false
 Atb device type
sm6150
 Atb app location status
denied
 Atb build number
1602503787
```

**Additional context**

**Comment by cbrevik** [comment]
Dette ser ikke ut til å være et problem lengre
