### ISSUE TITLE
[Bug] Sikre at de øverste inputfeltene på reisesøkbildet vises riktig på mobiler med liten skjermstørrelse

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#746]
There are a lot of animation timing issues causing different rendering bugs for both assistant view and departure view as it is now. One problem is that we always have to use the Y translated header container and also do scrolling-handling. To solve this we should separate the concepts.

One way to do this is to use shared elements and add new navigation point. This will also allow for pressing "back" on Android.

**Comment by monopoint** [comment]
This needs to be detailed a bit more before we can work on it. 

- What are the specific problems we are trying to solve?
- what are the acceptance criteria for this issue?
- what functional requirements of the animated header to we need to preserve?

**Comment by tormoseng** [comment]
https://mittatb.slack.com/archives/C018UPET2Q2/p1622640525117800

**Comment by monopoint** [comment]
> https://mittatb.slack.com/archives/C018UPET2Q2/p1622640525117800

denne er fikset på #1359 

@cbrevik jeg synes denne saken er litt uklar, men den berører i hvert fall en god del av det som ble fikset i #1359. skal vi kaste denne saken og si at resten ligger i bøtta som heter "skrive om disappearing header"?
