### ISSUE TITLE
[Feature] Add map over route to departures

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#747]
## Origin
_Links to received feedback, user research or other findings._

The need for a map when exploring departures has been reported in both usability tests and via Intercom. 

## Motivation
_A short description of what user needs or business goals this feature will solve._

- Users wants to view the route on a map in case they are not very familiar in the area
- Users wants to view the route on a map when they are not familiar with the quay names
- Users wants to use the map as a planning tool

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

- Add map in travel details (clicked a departure):
![Details](https://user-images.githubusercontent.com/8980523/100607758-af155600-330b-11eb-98fe-9c4040a05f2e.png)

Figma: https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=963%3A1990

**Comment by mikaelbr** [comment]
QA: Verified functionality. There are some improvements to the map generally that could be done. Specifically more prominent quays. But this is already a task in the backlog https://github.com/AtB-AS/mittatb-app/issues/959
