### ISSUE TITLE
[Designsync] Update journey details

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/mittatb-app#748]
## Acceptance criteria

- [ ] Details contents can be perceived by using a screen reader
- [ ] Details contents can be operated using a sceeen reader
- [ ] Details contents and functions are accessible for font size up to 200%
- [ ] Changes to journey details and trip details match design (see exceptions below)
- [ ] Elements displayed properly when dark theme is switched on

Exceptions to design:
- Map is left out of the trip details view, as this is described in a separate issue 
- Pagination is left out of the trip details view, as currently not decided what to paginate from the different views (trip details is a shared component opened from both nearby and journey details)
- Date in journey details: Was not shown in figma design at the time of development. Could possibly be kept out for now and described as a separate issue (perhaps even as a "quick win")

## Origin
_Links to received feedback, user research or other findings._

## Motivation
_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

Figma / App 1.0 / Assistant: https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=963%3A0
Figma / App 1.0 / Departures: https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=963%3A1990
FIgma / Components 1.0 / List-items: https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components-1.0?node-id=547%3A6037
FIgma / Components 1.0 / List-groups: https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components-1.0?node-id=547%3A6287

![image](https://user-images.githubusercontent.com/56530785/100985226-07d33180-354c-11eb-828e-9cc17b5a3a88.png)

**Comment by rikkekantega** [comment]
Bumped the priority of this issue due to #622 being dependant on new design.

**Comment by rikkekantega** [comment]
Departures update:
I am leaving out two things 
1. The map in departures view. Already described in a separate issue #747 
2. Pagination in departures view: Not entirely sure _what _ to paginate when departures view is opened from assistant/journey planner. From "closest departures" i expect this the pagination to be between departures from a specific quay on a specific line. I suggest we describe the functionality as a separate issue. 

Component design for both 1 and 2 should be synchronized and ready to use

**Comment by hildeor** [comment]
QA:

- Stops are not aligned with graphic (not blocking release though)
![IMG_0779](https://user-images.githubusercontent.com/8980523/103623348-4c316300-4f38-11eb-81d7-42fbebbe3fa9.jpg)

**Comment by mikaelbr** [comment]
QA

- Missing date from pagination header.

**Comment by rikkekantega** [comment]
> QA:
> 
> * Stops are not aligned with graphic (not blocking release though)
>   ![IMG_0779](https://user-images.githubusercontent.com/8980523/103623348-4c316300-4f38-11eb-81d7-42fbebbe3fa9.jpg)

This should already be resolved in current QA version of the app, are you testing on QA or testflight version? :)

**Comment by rikkekantega** [comment]
> QA
> 
> * Missing date from pagination header.

Wasn't a part of the Figma design when implementet, so we should agree on whether this is to be fixed here or as a separate issue. And also, what does this date/time show, departure time or arrival time?

**Comment by mikaelbr** [comment]
Yeah, I know. Just thought I'd mention it, but also saw after the fact that you had a comment in the description specifically on this 😬 . Can have a separate issue on it, and it is not blocking, but it is also a quick fix I think. I think the most natural date to show is the departure time, tbh

**Comment by rikkekantega** [comment]
> I think the most natural date to show is the departure time, tbh

I agree
