### ISSUE TITLE
[Feature] Tariff zone selection in ticket buy process

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#761]
## Origin
Selecting from/to tariff zones is a requirement in regards to how ticket pricing is structured. 

## Motivation
This feature will let users select the correct zones they are traveling within/to, in an intuitive way which will hopefully prevent incorrect purchases.

## Hypotheses and assumptions
- Many users travel within just one zone
- Many users travel from one zone to another
- Users probably travel within the same set of zones multiple times, without changing the pattern often
- Not all users know the name of the zones they travel within
- Some users want to select zones by name
- Some users want to select zones by clicking on a map
- Some users want to select zones by searching for the locations they travel from/to

## Proposed solution
Let users select from/to zones by name, or by searching up stop places. Wait with map-implementation on zone-selection.

![image](https://user-images.githubusercontent.com/56530785/101025452-e424e100-3575-11eb-88e9-2b3618e4aaea.png)

**Comment by pettersuul** [comment]
![image](https://user-images.githubusercontent.com/56530785/102351109-34ecfe80-3fa6-11eb-94b8-c0bbf769d2e1.png)

Removed text from back-button.
How does this behave if you have selected something but use the back-button instead of "save"? Is it clear enough that the back-navigation is destructive if the selection is removed?

**Comment by gorandalum** [comment]
When using "Min posisjon", should the inferred venue be shown to the user? I remember talking about this, as we always use a venue as the source for zone selection, and the closest venue may not always be the one the user wants. Or is just showing "Min posisjon" good enough for now?

**Comment by pettersuul** [comment]
This is something that we probably should test. I think that for now we use the same behaviour as the other searches, and show the selected address or venue when activating the input field.
Perhaps it should say "Min posisjon (Sone *)" so that the user may check that it is the correct zone? Although if the default destination is "Samme sone (Sone *)" it may be unnecessary.

**Comment by cbrevik** [comment]
Could use something like this to display a list of stops "nearest" your position in the search results if "Min posisjon" is chosen: https://api.dev.mittatb.no/bff/v1/stops/nearest?lat=63.37019082600564&lon=10.37677809375802&distance=200

**Comment by gorandalum** [comment]
Yeah. That could be possible.

I've looked at that endpoint now (and the Entur sdk endpoint it uses) and it does not seem that it is possible to make it only include stops within AtB tariff zones. Would it be better to use the geocoder reverse endpoint with the parameter `tariff_zone_authorities` set to _ATB_?

**Comment by cbrevik** [comment]
Definitely!

**Comment by gorandalum** [comment]
Doh! Not supported by entur/sdk. Even though it is not "officially supported" in the interface types, it still works for `GetFeatures` as all additional parameters are [forwarded](https://github.com/entur/sdk/blob/master/src/geocoder/index.ts#L130) to the rest endpoint. However this is not done for [GetReverseFeatures](https://github.com/entur/sdk/blob/master/src/geocoder/index.ts#L171).

Whats the best way to approach this:
1. Use the stops/nearest endpoint, and filter stops after retrieving from Entur. We then probably have to use a larger limit when asking for stops, to account for stops not belonging to an AtB tariff zone. 
2. Create a PR to Entur for supporting `tariff_zone_authorities`. I've looked at the code and creating a PR fixing this is no big task. However I don't know how fast Entur releases new version of the sdk.

**Comment by pettersuul** [comment]
Made a simple prototype for selecting zone in a map: https://www.figma.com/proto/gOfqWNXyeCxa1zzVocrD8W/Zone-selection?node-id=1%3A386&viewport=1697%2C940%2C0.45766493678092957&scaling=min-zoom

User should be able to move and zoom map freely, and select a zone by tapping inside the zone polygon.

To confirm selection the user taps the input at the top labeled with the selected zone.
- Will this be confusing? Will tap the back-arrow and expect the selection to be saved?

**Comment by gorandalum** [comment]
Closing this. Making a new issue for the remaining tariff zone map selection functionality.
