### ISSUE TITLE
Research mobile token in Entur SDK

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#763]
- [ ] Try out new customer service endpoint to create mobile token
- [ ] Attempt attestation of mobile token through SDK

**Comment by vidtil** [comment]
Jeg har oppdatert vår fork av repoet fra Entur som inneholder idbasert-bibliotekene som er laget for apper: https://github.com/AtB-AS/abt-mobile

Her er Enturs forklaring til hvordan opprettelse og innrullering av token skal skje: https://enturas.atlassian.net/wiki/spaces/kb/pages/834273359/Klientsikkerhet+-+krav+til+apper#Klientsikkerhet-kravtilapper-Innledning
