### ISSUE TITLE
[Feature] Language preference selection in "Mitt AtB"

### ISSUE THREAD

**Issue by rikkekantega** [AtB-AS/mittatb-app#780]
## Origin
_Links to received feedback, user research or other findings._

Default app criteria, English and Norwegian language support

## Motivation
_A short description of what user needs or business goals this feature will solve._

We only support English and Norwegian, and decide on which to use based on system language settings (phone settings). In cases where system language is set to something else than the supported languages, we choose a default on the users behalf. The user should be able to override this default language, so he/she doesn't need to change the language of their entire system to change preference for the app. 

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

- The user may be more familiar with the one or other of the supported languages, without using it as a system language on his/her phone
- Easily accessed language switch in app may enable the possibility for foreigners to practice their norwegian skills
- Learning mobility related terminology may be easier having an easily accessed translation in app

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

A switch for language in "Mitt AtB" screen, that explicitly sets system language settings. Option to use system settings if desired.

**Comment by mikaelbr** [comment]
This isn't included in 1.4 as of now (example ios tag to see latest commit for 1.4 release https://github.com/AtB-AS/mittatb-app/tree/alpha-ios-1608299094). Not doing QA for this in TestFlight for 1.4
