### ISSUE TITLE
[Feature] Ensure icon/color support for all transport modes

### ISSUE THREAD

**Issue by rikkekantega** [AtB-AS/mittatb-app#787]
## Origin
_Links to received feedback, user research or other findings._
Suddenly realized there weren't sufficient handling of the transport mode "coach" in the app
![image](https://user-images.githubusercontent.com/61825573/102601044-eb282380-411f-11eb-9a85-94a522a64828.png)

"Coach" was added to "bus" switch cases on transportation colors and icons, as it is a type of bus.

Then also found that there are several more unhandled modes: Bicycle, car, cable, lift, metro, and funicular. None of which seem likely for our usage right now, but we sure need to handle them for if and when they appear

## Motivation
_A short description of what user needs or business goals this feature will solve._

In rare cases unusual transport modes appear, and we need to display something more useful than an empty icon.

## Hypotheses and assumptions
_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution
_A coarse description of a proposed solution, that may include wireframes and graphic design._

**Comment by cbrevik** [comment]
Skal være løst
