### ISSUE TITLE
[BUG] "Min" is shown twice in travel suggestions

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#809]
**Describe the bug**

It seems that travel suggestions including changing of buses displays waiting time as "Vent i 1 min min". 

![IMG_0772](https://user-images.githubusercontent.com/8980523/103513230-79174480-4e6a-11eb-9156-89284ff2acc5.PNG)

**Application version**
Version number: [e.g. 1.2.3]

**To Reproduce**
1. Search any travels that includes more than 1 leg
2. Click on travel details

**Expected behavior**

**Comment by rikkekantega** [comment]
Closing this, since the bug seems to be fixed by new details design:

![Screenshot_1609762251](https://user-images.githubusercontent.com/61825573/103534015-66af0200-4e8e-11eb-890a-40b92262c223.png)
