### ISSUE TITLE
[Improvement] Sikre at kartikoner for bussholdeplasser vises minst like godt som kartikoner for togstasjoner

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#887]
## Origin

_Links to received feedback, user research or other findings._

Feedback via Intercom:

> Ser at Entur sitt kartgrunnlag som vi nyttar i appen har mest fokus på tog. Ser dette spesielt når ein zoomar ut er det kun ikona for tog-stasjon som viser. Burde dette ikkje heller td vore våre AtB sine definerte knutepunkt?
![Screenshot_20210128-124647](https://user-images.githubusercontent.com/8980523/106256668-ddd07f80-621b-11eb-960f-b9b6768a24c2.png)

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

Når man åpner kartet i dag fra f. eks reisesøk eller avganger, så vises togstasjoner som store ikoner ved et visst zoomnivå, mens bussholdeplasser må man zoome inn mye lengre for at de skal dukke opp som ikoner. 
Foreslår at disse vektes likt, eventuelt at buss og trikk vektes høyere enn tog. 

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by tormoseng** [comment]
@monopoint Ser fortsatt togstasjonene vesentlig bedre enn bussholdeplasser. Er det noe som ikke er oppdatert enda?
![131816551_534190447764882_3893344618025230538_n](https://user-images.githubusercontent.com/5812433/122736977-dec48500-d280-11eb-8b38-56c8960d764f.jpg)

**Comment by monopoint** [comment]
Neida, det ser rett ut det der.
Det gjøres en del vekting for hva som skal vises i hvilke zoom nivå. her er du så langt ut at vanlige bussholdeplasser begynner å bi irrelevante. på dette zoom-nivået er det langdistanse-holdeplasser som blir prioritert. Så her vises Buss-terminaler (Trondheim S), og togholdeplasser. Men det som er viktig å få med seg akkurat her, er at Buss-terminalen legger seg over Togstasjonen. tidligere så ble bussholdeplasser og -terminaler skjult ved at togstasjonene kunne legge seg over.

**Comment by tormoseng** [comment]
Aha. Da er denne grei både på iOS og Android i staging.
