### ISSUE TITLE
[Feature] Handle multimodal StopPlaces

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#888]
## Origin

_Links to received feedback, user research or other findings._

Via feedback from Intercom we have been made aware that there are two types of StopPlaces: regular stopPlaces which most are defined as, and multimodal stopPlaces. The latter is the case of "St. Olavs Hospital" and "Trondheim S". 
It means that "St. Olavs Hospital" is the overarching stopPlace, which consists of two sub-stopPlaces (St. Olavs Hospital øst and St. Olavs Hospital vest). These sub-stopPlaces in turn has two quays. 

Seems like this has been recommended structure from Entur, but it has some in-app consequences for these two particular stopPlaces:

- In the Departures-view we do not support multimodal stopPlaces. These are therefore displayed incorrectly where stopPlaces are viewed as platforms/quays. This causes the view on these mulitmodal stops to become unnecessarily complex and displays more quays than desired. 
- It is also harder for users to decide direction on buslines.

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

Need to research how we can approach this: 
- Can we read these data differently from Entur?
- Do we need to make exceptions for these stops?
- ??

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by hildeor** [comment]
Tonstadkrysset is also a multimodal stopPlace. See Slack thread on this topic: https://mittatb.slack.com/archives/CS3JNRXEV/p1612949773019000

**Comment by hildeor** [comment]
@mikaelbr With this issue, will "St. Olavs hospital vest" become searchable? As it is now only "St. Olavs hospital" is searchable, but some people will want to search for only "St. Olavs hospital vest" or "St. Olavs hospital øst".

**Comment by mikaelbr** [comment]
No, that's a separate issue that we need to talk to Entur about.

**Comment by mikaelbr** [comment]
@hildeor What do you think is natural here? Only show children? So not `St. Olavs hospital` but only `St. Olavs hospital vest` or `St. Olavs hospital øst`? For St.Olavs that is probably best, but Tonstadkrysset is a bit odd. But I'm leaning towards showing only children. I think that would actually solve this issue also, thinking about it.

**Comment by mikaelbr** [comment]
Related: https://github.com/AtB-AS/atb-bff/pull/68

**Comment by mikaelbr** [comment]
This should be solved for future multimodal stop places now and for St. Olavs and Tonstadkrysset particularly. We've added search on Child level for the BFF and Tonstadkrysset and St. Olavs are made into non-multimodal stop places. Multimodal stop places should only be used for stop places serving different transportation modes (bus, train, etc).
