### ISSUE TITLE
ReferenceError in src/screens/Ticketing/Ticket/Details/DetailsScreen.tsx:43

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#940]
## Error in MittAtb

**ReferenceError** in **src/screens/Ticketing/Ticket/Details/DetailsScreen.tsx:43**
Property 'React' doesn't exist

[View on Bugsnag](https://app.bugsnag.com/atb-as/mittatb/errors/603528ce9f236b001bc3c2d7?event_id=603528ce00715e8cf3770000&i=gh&m=ci)

## Stacktrace

    src/screens/Ticketing/Ticket/Details/DetailsScreen.tsx:43 - anonymous

[View full stacktrace](https://app.bugsnag.com/atb-as/mittatb/errors/603528ce9f236b001bc3c2d7?event_id=603528ce00715e8cf3770000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gorandalum** [comment]
This was fixed.
