### ISSUE TITLE
[Feature] Navigate to quay from Departure Details

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#944]
## Origin

There's been a lot of feedback on different channels for this, but the most recent one: 
https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/4207849/conversations/159245400004209

## Motivation

_A short description of what user needs or business goals this feature will solve._

Users use Departure details as a means to see what stop place they want to go to, but the journey might not end there. They are interested in seeing departures from that stop place. Now they have to remember the destination stop place, go to the departure screen and search for said stop place.

## Proposed solution

Adding a link/navigation point from Stop Place list in departure detail screen:

<img width="568" alt="Screenshot 2021-02-26 at 10 00 24" src="https://user-images.githubusercontent.com/606374/109278956-73f6c600-7819-11eb-97b8-ab8664e15915.png">

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [x] Renders colors as expected in dark and light mode.
- [x] Is translatable to English and Norwegian.
- [x] Does not drain battery
- [x] Works in up to 200% font size
- [x] Is operable and perceivable using screen reader
- [x] Supports deep linking for departure screen.

**Comment by hildeor** [comment]
One comment we got from Intercom also regarding this is that it would be useful to have departures listed in both directions when navigating to a new stop. 
https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/conversation/159245400003619#part_id=comment-159245400003619-8206316121

**Comment by tormoseng** [comment]
Testet OK på Android emulator + iPhone real/simulator

**Comment by tormoseng** [comment]
Testet OK i QA med iOS og Android

**Comment by hildeor** [comment]
@gorandalum VOiceover:
- Er det mulig å få "1 av 7" til å leses før "neste"? Nå leses "neste" først og så "1 av 7" som oppleves litt ulogisk

**Comment by gorandalum** [comment]
Det er ikke stort nok til at vi gjør noe med dette nå før release, så det bør opprettes egen sak på. Men det er en nok en quick win til neste release.
