### ISSUE TITLE
[Feature] Mulighet for å dele reiseforslag med andre

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#958]
## Origin

_Links to received feedback, user research or other findings._

## Motivation

_A short description of what user needs or business goals this feature will solve._

User story (Norwegian)
> Som en bruker vil jeg kunne sende planlagte reiser til andre for å hjelpe de komme seg fra A til B på en best mulig måte.

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by monopoint** [comment]
samler fetures som er under scope "mine reiser" i samme sak for konseptutvikling
#957
