### ISSUE TITLE
[Feature] Find Quays in Map

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#959]
## Origin

_Links to received feedback, user research or other findings._

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

> Som en reisende vil jeg kunne enkelt se hvilke plattformer som er relevante for meg og være trygg på at det er denne plattformen jeg er på.﻿

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by vidtil** [comment]
Kanskje dekket godt nok allerede?

**Comment by hildeor** [comment]
Usikker på om det er tenkt noe utvidet funksjonalitet med denne, sånn som f. eks å kunne trykke på quay i kart og se avganger derfra? @mikaelbr Hvis ikke, så er de allerede synlig i kartene vi har nå hvis man zoomer inn tilstrekkelig. Lurer på om denne er verdt å ta vare på eller om den bør lukkes.
