### ISSUE TITLE
Auto-generate screeenshots from app

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/mittatb-app#96]
This usually takes a lot of time if you want to support screenshots from many different devices. It's a good idea to do, since it increases adoption of app.

Can potentially use fastlane (it's installed on AppCenter) along with:
- snapshot (iOS):  https://docs.fastlane.tools/getting-started/ios/screenshots/
- screengrab (Android): https://docs.fastlane.tools/getting-started/android/screenshots/

They are native specific though, so might be another way to go about this with React Native. Potentially with Detox, which internally has a `takeScreenshot`-function on the AppleSimUtils-tool.

**Comment by gorandalum** [comment]
Closing as it will not be worth the time investment.
