### ISSUE TITLE
SIGSEGV in /system/vendor/lib64/egl/libGLESv2_adreno.so:1097248

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/mittatb-app#975]
## Error in MittAtb

**SIGSEGV** in **/system/vendor/lib64/egl/libGLESv2_adreno.so:1097248**
Segmentation violation (invalid memory reference)

[View on Bugsnag](https://app.bugsnag.com/atb-as/mittatb/errors/604120b157ac330017712e67?event_id=604120b10072f391c3660000&i=gh&m=ci)

## Stacktrace

    /system/vendor/lib64/egl/libGLESv2_adreno.so:1097248 - EsxFramebufferObject::DetachAll(EsxContext*)

[View full stacktrace](https://app.bugsnag.com/atb-as/mittatb/errors/604120b157ac330017712e67?event_id=604120b10072f391c3660000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gorandalum** [comment]
Utdatert
