### ISSUE TITLE
Improvements on ticketing experience

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#996]
## Origin

_Links to received feedback, user research or other findings._

We have gotten some feedback from those who have tested out the first version of ticketing:
- It can be hard to hit the plus/minus icons when choosing ticket categories due to small hit area
- "Vis for kontroll"-button is confusing when it is disabled. Reported as a bug. Functionality behind this button will be part of the next release.
- Default choice of adult-category: users using VoiceOver and wants another ticket category reported this as very troublesome as it requires more effort and time when using assistive technology. This has also been reported to be hard to spot, so that a user does not discover that this has been pre-selected. This may cause incorrect purchases for the user. 
- Annoying that the active-tab is shown when navigating to tickets and you have no active tickets.
- Ticketing and travel assistant are disconnected. Want a more integrated experience.

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

- Increase padding and area that is registered as touch for +/- according to sketches in Figma: https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/App-1.0?node-id=3578%3A18125
- Default ticket category implemented as a setting in "Mitt AtB". When using settings, it will override the "1 adult" default. "1 adult" is OK for those with no settings.
- Button from travel suggestion to ticketing, with pre-selected zones based on travel search.

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by hildeor** [comment]
@gorandalum Updated default ticket category after discussion today.

**Comment by gorandalum** [comment]
> It can be hard to hit the plus/minus icons when choosing ticket categories due to small hit area

Fixed by increasing spacing and increasing minus/pluss button hitboxes in https://github.com/AtB-AS/mittatb-app/pull/1025

**Comment by hildeor** [comment]
Disse er fikset allerede, har egen issue på å koble sammen reisesøk og billettkjøp.
