### ISSUE TITLE
[Feature] Sikre at "gyldig til" vises tydelig før kunden kjøper billetten

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/mittatb-app#999]
## Origin

_Links to received feedback, user research or other findings._

Based on feedback from Intercom, not everyone is aware of how long a given ticket is valid. Displaying both valid from and valid to date and time, makes it more predictable for the users before purchase. 

## Motivation

_A short description of what user needs or business goals this feature will solve._

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

- Display "valid to" date and time on ticket summary (before payment). 
- Add this on one line below the existing valid-to line
- Discuss design with @pettersuul 

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [] Renders colors as expected in dark and light mode.
- [] Is translatable to English and Norwegian.
- [] Does not drain battery
- [] Works in up to 200% font size
- [] Is operable and perceivable using screen reader

**Comment by hildeor** [comment]
@gorandalum Check how this can be implemented

**Comment by gorandalum** [comment]
@mjenssen Can we return the validity period for an offer to the app? Do you have a suggestion how to model this?

**Comment by vidtil** [comment]
Også diskutert her: https://mittatb.slack.com/archives/C012725S7MJ/p1620221906260300
